// prettier-ignore
/* eslint-disable */

// AUTO-GENERATED by scripts/gen-agents-md.ts — do not edit manually

// ── Chunks ──────────────────────────────────────────────────────────────────

const CHUNK_00_BACKLOG = `## Backlog

If \`docs/backlog/\` exists, it holds work that was deliberately deferred — one Markdown file per
item, written at the moment the problem was understood, by whoever had just finished investigating
it.

**Search it before you start investigating anything.** Search the bodies, not just the filenames:

\`\`\`bash
rg -i "<symptom or subsystem>" docs/backlog/
\`\`\`

Do this before debugging a defect, before a performance or correctness investigation, before
writing a plan, before proposing a design change, and whenever the user asks why something is the
way it is. An entry may already hold the reproduction, the measurement, the approach that was tried
and failed, or the constraint that rules out the obvious fix.

A hit **re-opens the triage decision**, it does not close it. \`worth: later\` and \`worth: no\` were
judgments made under the circumstances of the \`added:\` date. Read the reasoning, check whether its
premises still hold, and say so rather than silently inheriting the old verdict.

Treat an entry as evidence, not as truth: verify its \`where:\` anchor before relying on it, because
the code may have moved since.

### Where a finding goes

Three places, and they are not interchangeable. Put a finding in exactly one:

| Place                | Holds                                                               | Test                                              |
| -------------------- | ------------------------------------------------------------------- | ------------------------------------------------- |
| \`AGENTS.md\`          | A rule a contributor must follow to work correctly **now**          | Not knowing it makes you do the wrong thing today |
| \`docs/backlog/\`      | Work on this repository that was deliberately deferred              | Somebody could pick it up and act on it           |
| Agent-private memory | How **this user** works — preferences, corrections, session context | It is about the person, not the codebase          |

Agent-private facts must never be committed. Conversely, a real finding must not be left in
agent-private memory, where the next contributor, the next agent and CI will never see it.

**The backlog is not a notebook.** It is not a place to park session notes, observations, ideas you
have not examined, or anything an agent wants to remember. Every entry is a claim that something
about this codebase is wrong or missing and that acting on it is possible. If a note fails that
test, it does not become a backlog entry just because it has nowhere else to go.

The \`backlog\` skill holds the format and the workflow.`;

const CHUNK_00_BASE = `**These rules are binding for every repository that references this file. Instructions placed above the reference to this file in the including \`AGENTS.md\` override matching rules here; all other rules below remain in full effect.**

## Language Policy

**All documentation, READMEs, code comments, commit messages, and identifiers (function/variable/type names) MUST be written in English only. No exceptions.** Non-English text is allowed only in explicit localization assets and tests that validate localized output.

## Code Commenting Guidelines

**Default to no comment.** Code that needs prose to be understood should be rewritten first — a clearer name, a smaller function, an extracted constant. A comment is the fallback for what genuinely cannot live in the code; it is never a way to describe code you just wrote.

Write one ONLY in these cases:

- **Non-obvious business logic** — a domain rule or algorithm whose *why* is not derivable from the code.
- **Architectural decisions** — why this approach, and over which specific alternative.
- **Workarounds** — name the bug, version, or constraint that forces the unusual shape.
- **Doc comments the language requires** — Go exported identifiers and packages (the shipped \`revive\` config enables \`exported\` and \`package-comments\`). Such a comment MUST say something the signature does not. \`// Foo does Foo\` satisfies the linter and is forbidden anyway, like any other restatement.

**Everything else is forbidden.** Never write a comment that:

- restates what the code does, in any form;
- states the obvious, labels a standard pattern (\`defer\`/\`finally\` cleanup, a loop, a getter), or captions a section of a function body;
- narrates the edit — what changed, what it used to be, what you decided while writing it. That belongs in the commit message and git history;
- repeats the signature: parameter names, types, or the return value.

**The test:** say what the comment adds that the line below it does not. If you cannot, delete it rather than reword it. Apply this to comments you are about to write, and to existing ones in code you are already changing.

## Testing

- All tests MUST be isolated — never modify workspace root or shared state
- Each package/module must be independently testable
- Clean test artifacts in teardown hooks (\`afterEach\` / \`afterAll\` / \`t.Cleanup\`)
- Mock external dependencies to prevent network calls or file system mutations outside test scope
- Never commit \`.only\`, \`.skip\`, or equivalent markers in test files

## Git Workflow

Follow GitHub Flow with feature branches from main.

**Never bypass commit hooks or verification — under any circumstances.** Do not pass \`--no-verify\` (or any equivalent skip flag) to \`git commit\`/\`git push\`, and never disable, uninstall, or work around pre-commit, commit-msg, or pre-push hooks. They run the same checks as CI; skipping them only pushes a known breakage downstream and burns the maintainer's time.

- A failing hook is a real signal, not an obstacle to route around. Fix the root cause — the code, the commit contents, or the local environment (e.g. a broken toolchain/store) — then commit again.
- **Commits must stay signed.** If commit signing is configured and signing fails (e.g. a passphrase-locked SSH key that is not loaded in the agent), STOP. Do not commit unsigned, and do not disable signing to get around it. Tell the user their commit signing needs attention and ask them to make it work so you can commit.
- If you cannot commit cleanly, stop and report exactly why. Never trade a clean history or a green CI for a shortcut that only looks green.

**Commit message format** (Conventional Commits):

- \`feat:\` new feature
- \`fix:\` bug fix
- \`docs:\` documentation only
- \`refactor:\` code restructuring (no behavior change)
- \`test:\` adding or updating tests
- \`chore:\` maintenance, dependency updates

## Dependency Management

- **Internal packages**: Always use workspace protocol references (\`workspace:*\`)
- **Peer dependencies**: Use caret ranges (\`^\`) for compatibility
- **Regular dependencies**: Pin exact versions for reproducibility
- After adding dependencies, run \`pnpm dm check\` to sync and validate

## Linting & Formatting

All linting and formatting runs through [datamitsu](https://datamitsu.com/) via one command: \`pnpm dm check\`. Do not configure or run individual linters/formatters directly — datamitsu manages the full toolchain.

## AGENTS.md Maintenance

**Keep AGENTS.md in sync with code changes.** Whenever you make changes to the codebase, update AGENTS.md:

1. **Add to "Known Pitfalls"** if you encountered an issue a contributor must know about to work
   correctly today. A real defect that nobody is fixing now is not a pitfall — it belongs in
   \`docs/backlog/\` (see the Backlog section)
2. **Update commands** if scripts change
3. **Add examples** for new patterns introduced
4. **Update architecture notes** for significant refactoring

**Golden Rule**: If you had to figure something out, document it so others (and future AI agents) don't have to — routed per the Backlog section, and never only in an agent's private memory.

## Verification Checklist

Before completing any task:

1. Run the test suite if tests exist
2. Run \`pnpm dm check\`
3. Verify build succeeds
4. Update AGENTS.md if a new pattern or pitfall was discovered

## TypeScript Configuration

When creating or modifying \`tsconfig.json\` files, consult the [TypeScript Configuration Guide](.datamitsu/tsconfig.md).`;

const CHUNK_00_CONFIG_INPUTS = `## Single Source for Constants, Env & Build Inputs

Every project (or set of apps in a monorepo) funnels its shared constants, environment variables, and build-time flags through ONE declared, validated access point. Reading these values ad-hoc anywhere else is forbidden. This holds when STARTING a project AND while MAINTAINING one: if you see a constant, a raw env read, or a build flag used inline where it belongs in the central point, STOP and tell the user before continuing.

### Constants

- Declare shared constants in a single module per project (Go: one package; JS/TS: one module). No magic values scattered across files.
- Constants that must be shared ACROSS languages (e.g. Go + JS in one monorepo): keep them in a single JSON manifest and generate the per-language files from it with a codegen script — do not maintain copies by hand.
  - Each generated file carries a header comment marking it as generated (naming the source manifest and the generator).
  - Prefer generating on demand at build time (the artifact need not be committed) over static committed copies. The manifest is the only source of truth.
  - The generator language is situational — TypeScript is a fine default.

### Environment Variables

One env module per project (Go: an \`env\` package; TS: an \`env.ts\`). ALL env access goes through it.

- Direct \`process.env\` (JS/TS) and \`os.Getenv\` (Go) are forbidden everywhere else — except the standard, non-app vars a child process genuinely needs (\`PATH\`, \`HOME\`, \`CI\`, …).
- Expose each value via an accessor (a function, not a bare mutable export): it cannot be reassigned by accident, and its default lives next to it.
- Do ALL parsing, normalization, and validation here — bool/int parsing, enum checks, coercion to the type the app expects. The rest of the app consumes an already-valid, typed value, never a raw string.
- Centralize the KEYS too, so renaming a variable is a one-line change.

### Build-Time Flags

Go \`ldflags\` and build tags, Rust \`build.rs\` / \`cfg\` / \`env!\`, and equivalents.

- Treat them exactly like env vars: funnel into one module with defaults, normalization, and typed accessors. Do NOT read raw ldflag-injected variables across the codebase.
- The app must not care whether a value came from an env var or a build flag — it reads one validated config surface.`;

const CHUNK_00_DEPENDABOT = `## Dependabot (public GitHub repos only)

Keep \`.github/dependabot.yml\` accurate **only when this is a public GitHub repository**. Confirm before acting — e.g. \`gh repo view --json visibility,isPrivate\`. If the repo is private, not on GitHub, or you cannot determine this, **do nothing** and leave the file absent.

When it is a public GitHub repo:

1. **Ensure the file exists** if the repo has any supported ecosystem (npm/pnpm, Go modules, pip/uv, Cargo, Terraform, Docker, GitHub Actions). A minimal \`version: 2\` file with an empty \`updates:\` list is enough to opt in — \`dm setup\` fills in the rest.
2. **Own the \`updates\` entries** (the "what"): the \`package-ecosystem\` values and their \`directory\`/\`directories\`. Keep these in sync with the project's real layout — add an entry when a new workspace/service/ecosystem appears, remove one when it goes away.
3. **Do NOT hand-tune policy fields.** \`commit-message\`, \`versioning-strategy\`, \`schedule\`, \`groups\`, and \`open-pull-requests-limit\` are owned by datamitsu and are normalized on every \`dm setup\` (conventional-commit prefixes such as \`chore(deps):\`, weekly cadence, grouped PRs). Editing them by hand is pointless — they will be overwritten.
4. **Run \`pnpm dm setup\` after editing** so datamitsu re-applies the managed policy. datamitsu never creates this file on its own; it only normalizes one that already exists.`;

const CHUNK_00_PRIVACY = `## Privacy and Attribution

Anything written into the repository is published: documentation, plans, backlog entries, commit
messages, PR descriptions, code comments, test fixtures, issue text. Treat every one of them as
public the moment it is written, not the moment it is pushed.

### Never write into the repository

- Absolute paths that name a person, machine, or organization (\`/home/<user>/…\`, \`C:\Users\…\`),
  hostnames, IP addresses, ticket URLs from a private tracker.
- Credentials, tokens, license keys, or the values of environment variables that hold them — an
  environment variable's **name** is fine, its **value** is not.
- Contents copied out of a private repository: file paths, package names, branch names, code
  excerpts, error messages that quote them.
- Customer, employer, or client names, and anything that identifies them indirectly (a product
  name, a distinctive dependency, a domain).

If a measurement, a bug report, or an example needs one of these to make sense, **anonymize it and
keep the shape**, which is what carries the meaning:

> ❌ \`Measured on acme-storefront: apps/landing/pages/sitemap.xml.tsx fails to typecheck.\`
> ✅ \`Measured on a private TypeScript monorepo (≈15k tracked files, ~60 workspace packages): one
package fails to typecheck because a generated file is missing.\`

### Naming other projects requires explicit permission

Do not name another project, repository, author, or product — or describe an approach as coming
from one — unless the user has explicitly said you may in this conversation. This applies to
private and public projects alike, and to links as much as to names.

Without that permission, describe the **idea** rather than its source:

> ❌ \`Backlog entries follow the format used by <author>/<repo>.\`
> ✅ \`Backlog entries carry \`worth\`/\`where\`/\`added\` frontmatter and a one-symptom title.\`

A user pasting a link is not the same as a user granting permission to cite it. If the attribution
genuinely matters — a license obligation, a quoted excerpt, a design credit — ask before writing it
down.

### Scope

These rules bind everything an agent writes into the repository and everything an agent copies into
it. When in doubt, anonymize.`;

const CHUNK_00_SCRIPTS = `## Project Scripts

Every package in the repository — regardless of language (TypeScript, Go, Python, Rust, Swift, Kotlin) — exposes a \`package.json\` with a unified set of scripts. This makes project entry points identical across the monorepo: the same command names work everywhere, and \`turbo\` orchestrates them from the root.

### Standard Scripts

Implement the relevant subset in each package. Names and meanings are fixed.

#### Run

- **\`dev\`** — Start everything required for the package to run: dev server, backend, infrastructure containers (without \`-d\`), workers. From the monorepo root, \`dev\` brings the whole project up. Persistent.
- **\`dev:mock\`** — Same as \`dev\`, with external dependencies mocked. Optional. Persistent.

#### Build

- **\`codegen\`** — Generate code from schemas: SDKs from OpenAPI/GraphQL/protobuf, DB types, i18n types. Idempotent.
- **\`build:lib\`** — Preparatory steps required before \`dev\` or \`build\`: asset prelinking, intermediate internal libraries, static preparation. Depends on \`codegen\`.
- **\`build\`** — Final application or library build. Depends on \`build:lib\`. Same name regardless of target (SPA, binary, npm package, WebAssembly artifact).

#### Test

- **\`test\`** — Fast tests: units, integration without infrastructure.
- **\`test:watch\`** — \`test\` in watch mode. Persistent. Fast tests only.
- **\`test:coverage\`** — Run tests with coverage collection.
- **\`test:e2e\`** — End-to-end tests: real browser, testcontainers, full infrastructure.
- **\`test:e2e:ui\`** — UI mode for the e2e runner, where supported.
- **\`test:e2e:install\`** — Install e2e runner dependencies (e.g., browsers). Idempotent.
- **\`test:snapshots\`** — Visual / screenshot tests.
- **\`test:snapshots:update\`** — Update screenshot baselines.
- **\`test:update\`** — Update inline snapshots.

#### Quality

Always run \`pnpm dm check\` after completing a task. This runs fixers (formatters, auto-fixes) followed by linters (type checking, ESLint). It should complete with no errors.

#### Misc

- **\`pull:*\`** — Fetch external artifacts (OpenAPI schemas, auth context, etc.).
- **\`upgrade:deps\`** — Update dependencies.

### Naming Rules

- A colon means specialization of an existing command. \`test:e2e\` is a kind of \`test\`. \`build:lib\` is a kind of \`build\`. New top-level names are not introduced.
- Environment is passed via variables, never encoded in the script name. No \`dev:fast\`, \`build:prod\`, \`test:ci\`.

### Complex Orchestration

When a script grows past a single command — multiple steps, parallelism, dependencies, conditions, intermediate variables — it moves to \`Taskfile.yaml\`. The \`package.json\` script becomes a thin entry point that delegates:

\`\`\`json
{
  "scripts": {
    "build": "pnpm dm exec task -- build",
    "build:lib": "pnpm dm exec task -- build:lib"
  }
}
\`\`\`

The standard names above never change — only what they delegate to.

#### Taskfile Conventions

- Every task has a \`desc\` field.
- \`deps\` for parallel prerequisites, \`cmds\` for sequential steps.
- Namespacing matches script names: \`build:*\`, \`test:*\`, \`dev:*\`.

\`\`\`yaml
version: "3"

tasks:
  build:
    desc: Full application build
    deps: [build:lib]
    cmds:
      - pnpm exec tsdown

  build:lib:
    desc: Generate SDK and build internal libraries
    deps: [codegen]
    cmds:
      - pnpm --filter @scope/shared build

  codegen:
    desc: Generate types from OpenAPI schema
    sources: [schema.yaml]
    generates: [src/generated/api.ts]
    cmds:
      - pnpm exec openapi-typescript ./schema.yaml -o ./src/generated/api.ts
\`\`\`

### Turborepo

Pipeline tasks are declared in \`turbo.json\`:

- \`dependsOn: ["^build"]\` for cross-package dependency ordering.
- \`"cache": false\` for non-cacheable tasks (\`dev\`, \`pull:*\`).
- \`"persistent": true\` for long-running tasks (\`dev\`, \`dev:mock\`, \`test:watch\`).
- \`"outputs"\` for cacheable build artifacts (\`dist/**\`, \`.next/**\`, etc.).

### Anti-Patterns

DO NOT:

- Invent script names outside the standard list (\`start\`, \`serve\`, \`compile\`, \`unit\`, \`typecheck\`, \`check\`, \`lint:fix\`, \`start:dev\`).
- Chain commands with \`&&\` in \`package.json\`. Move to Taskfile.
- Write \`.sh\` scripts for orchestration. Move to Taskfile.
- Use Makefiles. Use Taskfile.
- Encode environment in the script name. Use variables.
- Add a \`clean\` script. Use \`git clean -fdx\`.`;

const CHUNK_00_STACK = `## Preferred Stack

When creating a project, initializing an app, or adding a dependency, pick from this catalogue FIRST. Do not invent alternatives or reach for unmaintained/EOL packages. This is a priority list, not a hard mandate — if a project already uses a reasonable different choice, keep it.

### Version Policy

- If the library is already used in the repo, match that exact version.
- If it is not present, check the CURRENT latest stable release before adding. Never pick a stale major from memory — verify the version resolves first.
- Prefer runtimes and tools managed by \`datamitsu\`; do not hand-install what \`dm\` already provides.

### Invocation

Every datamitsu command follows the same rule:

- Inside a pnpm monorepo wired with this config: \`pnpm dm <command>\` — \`pnpm dm check\`, \`pnpm dm setup\`, and managed tools via \`pnpm dm exec <tool>\` (\`pnpm dm exec air\`, \`pnpm dm exec goose\`, \`pnpm dm exec task -- <task>\`, …).
- If the repo has no pnpm stack initialized: call the system-installed \`datamitsu\` binary directly — \`datamitsu check\`, \`datamitsu setup\`, \`datamitsu exec <tool>\`.

### Web

- App: Vite + React + TypeScript, with the React Compiler enabled.
- Data fetching: SWR.
- Routing: react-router with \`@ovineko/react-router\` — a type-safe React Router v7 wrapper (valibot-validated params, typed routes, automatic error handling).
- SPA resilience: \`@ovineko/spa-guard\` — a top-level guard for single-page apps that recovers from chunk-load failures after deploys (cache-busting + automatic retry), plus version checking and error reporting. Wire it via \`@ovineko/spa-guard-react\` (hooks + error boundaries) and the \`@ovineko/spa-guard-vite\` plugin; server side via \`@ovineko/spa-guard-fastify\` / \`-node\`.
- UI kit: admin panels → Ant Design; user-facing products → Mantine.
- Styling: vanilla-extract (Mantine ships a vanilla-extract integration).
- i18n: i18next.
- Component catalogue: Storybook.
- Emails: react-email. PDF: \`@react-pdf/renderer\` to generate, \`react-pdf\` to view.
- Prefer the ovineko ecosystem — consult https://ovineko.com/llms.txt first.
- **Banned: Tailwind CSS and anything built on top of it. Never introduce it.**

### Node

- Web framework: Fastify.
- Schemas/validation: \`typebox\` — the npm package \`typebox\` (https://www.npmjs.com/package/typebox), NOT \`@sinclair/typebox\`.
- Database: Kysely, a type-safe query builder (https://kysely.dev). Do NOT use TypeORM or any ORM — Kysely is a query builder, not an ORM.
- CLI: commander with \`@commander-js/extra-typings\`.

### Go

- HTTP router: \`github.com/go-chi/chi/v5\`.
- Logging: \`go.uber.org/zap\`.
- CLI: \`github.com/spf13/cobra\`.
- Database: sqlc — generate type-safe Go query functions from plain SQL. Pairs with goose for migrations. Run via \`pnpm dm exec sqlc -- generate\`.
- Dev/tooling: air (live reload), swag (Swagger), goose (DB migrations) — run via \`pnpm dm exec\`.

### Security & Hashing

- Password hashing: argon2id. Never bcrypt, plain SHA, or MD5 for passwords.
- Non-cryptographic hashing (cache keys, fingerprints, non-adversarial): consider \`github.com/zeebo/xxh3\` — fast. Never use it to verify external content; use a cryptographic hash (SHA-256 or stronger) there.

### Testing

- Unit: Vitest.
- E2E: Testcontainers (https://testcontainers.com); browser E2E → Playwright (https://playwright.dev).

### Monorepo

- Turborepo + pnpm workspace. Every package — including Go and Rust — carries a \`package.json\` so \`turbo run <script>\` orchestrates builds in dependency order.
- Script names follow the Project Scripts policy; heavy build logic goes to a Taskfile invoked via \`pnpm dm exec task -- <task>\`.

### Docs

- Documents: Typst. Presentations: Slidev. Run both via \`pnpm dm exec\`.`;

const CHUNK_10_DOCS = `## Documentation Policy

Documentation is a required deliverable for every user-facing change — not optional.

When implementing features or making changes, documentation MUST be updated in the same PR/commit:

- **User-facing features** → update docs with examples and guides
- **API changes** → update reference docs
- **CLI commands** → update the command reference
- **Configuration options** → update the config reference
- **Breaking changes** → document migration path

### Documentation Quality

- Review documentation changes with the same rigor as code
- Check for clarity, accuracy, and completeness
- **Test all code examples before merging** — examples that don't work erode trust

### Diagrams

- Use Mermaid for architectural diagrams — GitHub renders them natively in Markdown
- Keep diagrams as code for version control
- Prefer diagrams over lengthy textual explanations for flows, architecture, and data pipelines

### llms.txt Maintenance

If the project provides an \`llms.txt\` file (served via website or accessible via raw git URL, per [llmstxt.org](https://llmstxt.org/)):

- Keep it in sync with the actual documentation structure
- All links must point to valid, existing pages
- Update when adding new major sections, packages, or resources
- Do not add internal or draft documentation links`;

const CHUNK_20_DOCS_MARKDOWN = `## Documentation Surface

All user-facing documentation lives in Markdown files within the repository. Primary surfaces:

- **\`docs/\`** — detailed guides, API reference, architecture docs, command reference, config reference
- **\`README.md\`** — entry point; keep focused but may include more detail than a website-backed project

### README.md Scope

README serves as the primary documentation entry point. Include:

1. **What is this** — One paragraph description
2. **Quick install** — Single command
3. **Basic usage** — Minimal example (3-5 lines of code)
4. **Links** — Point to relevant \`docs/\` files for deeper topics

Keep README focused. Detailed architecture explanations and full API references belong in \`docs/\`, not inline.`;

const CHUNK_20_DOCS_WEBSITE = `## Documentation Surface

**All user-facing documentation lives in the documentation website. README.md files must remain minimal.** Reference pages, the command reference and the config reference all live there.

### README.md Scope

README must be kept **minimal** and focused on:

1. **What is this** — One paragraph description
2. **Quick install** — Single command or link to installation docs
3. **Basic usage** — Minimal example (3-5 lines of code)
4. **Link to full documentation** — Point to docs website

**Do NOT add to README.md:** detailed usage guides, configuration examples, architecture explanations, or API reference. These belong in the documentation website.

### Visual Documentation

- Add diagrams for complex architectural concepts
- Use screenshots for UI-related features — show, don't just tell
- Store screenshots in the website's static assets with descriptive names`;

// ── Joined combinations ─────────────────────────────────────────────────────
export const AGENTS_BASE = [CHUNK_00_BACKLOG, CHUNK_00_BASE, CHUNK_00_CONFIG_INPUTS, CHUNK_00_DEPENDABOT, CHUNK_00_PRIVACY, CHUNK_00_SCRIPTS, CHUNK_00_STACK].join("\n\n"); // prettier-ignore
export const AGENTS_DOCS_MARKDOWN = [CHUNK_00_BACKLOG, CHUNK_00_BASE, CHUNK_00_CONFIG_INPUTS, CHUNK_00_DEPENDABOT, CHUNK_00_PRIVACY, CHUNK_00_SCRIPTS, CHUNK_00_STACK, CHUNK_10_DOCS, CHUNK_20_DOCS_MARKDOWN].join("\n\n"); // prettier-ignore
export const AGENTS_DOCS_WEBSITE = [CHUNK_00_BACKLOG, CHUNK_00_BASE, CHUNK_00_CONFIG_INPUTS, CHUNK_00_DEPENDABOT, CHUNK_00_PRIVACY, CHUNK_00_SCRIPTS, CHUNK_00_STACK, CHUNK_10_DOCS, CHUNK_20_DOCS_WEBSITE].join("\n\n"); // prettier-ignore

// ── Chunk hashes (sha256, computed at build time) ────────────────────────────
export const CHUNK_00_BACKLOG_HASH = "8d8068ab184a1e2888d6fec12ef6e59fa172061cb712db734c42f7834a914209"; // prettier-ignore
export const CHUNK_00_BASE_HASH = "4191d3e2a7f26ef28ac76b141ef8747b65d5d2457a0800515969420a0be68986"; // prettier-ignore
export const CHUNK_00_CONFIG_INPUTS_HASH = "138dcb74fdd12336b8ccc87f1d589964996cc1e7d73f156b6870cb1ea6771542"; // prettier-ignore
export const CHUNK_00_DEPENDABOT_HASH = "b05aca84224760df0b9dae1f499a911c7c6531dd4623a7e55ab4d50b4f93f115"; // prettier-ignore
export const CHUNK_00_PRIVACY_HASH = "d8be582e591eb438952dd4173019ddb1f0f194260b04d1146526b6bd6afbd9f3"; // prettier-ignore
export const CHUNK_00_SCRIPTS_HASH = "2f7c6dcf065ff965f9f20b06768aad43fadadf0cad15f60bc72af10e750f1454"; // prettier-ignore
export const CHUNK_00_STACK_HASH = "bb04b25a48bec2084d5453936317e81529fdadd47d3b34e3d0c4cabcffebdb35"; // prettier-ignore
export const CHUNK_10_DOCS_HASH = "e4357d5d90b2f3e3f6cc982e821d3a76f92eee058311e7746ebb2937278a6d75"; // prettier-ignore
export const CHUNK_20_DOCS_MARKDOWN_HASH = "babafc853c28c64fc881f395c2a221a9639a1e34bfd8f219a50221e91e40dd05"; // prettier-ignore
export const CHUNK_20_DOCS_WEBSITE_HASH = "a9d1c1a59fa5b7ffd4c62819a84162113389675a4af72a7ab1e6eb0bfb325029"; // prettier-ignore

export const ALL_AGENTS_HASHES = [CHUNK_00_BACKLOG_HASH, CHUNK_00_BASE_HASH, CHUNK_00_CONFIG_INPUTS_HASH, CHUNK_00_DEPENDABOT_HASH, CHUNK_00_PRIVACY_HASH, CHUNK_00_SCRIPTS_HASH, CHUNK_00_STACK_HASH, CHUNK_10_DOCS_HASH, CHUNK_20_DOCS_MARKDOWN_HASH, CHUNK_20_DOCS_WEBSITE_HASH]; // prettier-ignore
