// prettier-ignore
/* eslint-disable */

// AUTO-GENERATED by scripts/gen-agents-md.ts — do not edit manually

// ── Chunks ──────────────────────────────────────────────────────────────────

const CHUNK_00_BASE = `**These rules are binding for every repository that references this file. Instructions placed above the reference to this file in the including \`AGENTS.md\` override matching rules here; all other rules below remain in full effect.**

## Language Policy

**All documentation, READMEs, code comments, commit messages, and identifiers (function/variable/type names) MUST be written in English only. No exceptions.** Non-English text is allowed only in explicit localization assets and tests that validate localized output.

## Code Commenting Guidelines

### When to Add Comments

1. **Non-obvious business logic**: Complex algorithms or domain-specific rules that aren't immediately clear
2. **Architectural decisions**: Why a particular approach was chosen over alternatives
3. **Workarounds**: Explaining why unusual code exists (e.g., working around library bugs)
4. **Public API documentation**: Exported functions, types, and packages should have doc comments

### When NOT to Add Comments

1. **Repeating what the code does**: Bad: \`// Create temp file\` above \`os.CreateTemp()\`
2. **Stating the obvious**: Bad: \`// Loop through items\` above a for-loop
3. **Explaining standard patterns**: Bad: \`// Close file\` in defer/finally statements
4. **Tracking changes**: Use git history instead of inline change logs

## Testing

- All tests MUST be isolated — never modify workspace root or shared state
- Each package/module must be independently testable
- Clean test artifacts in teardown hooks (\`afterEach\` / \`afterAll\` / \`t.Cleanup\`)
- Mock external dependencies to prevent network calls or file system mutations outside test scope
- Never commit \`.only\`, \`.skip\`, or equivalent markers in test files

## Git Workflow

Follow GitHub Flow with feature branches from main.

**Commit message format** (Conventional Commits):

- \`feat:\` new feature
- \`fix:\` bug fix
- \`docs:\` documentation only
- \`refactor:\` code restructuring (no behavior change)
- \`test:\` adding or updating tests
- \`chore:\` maintenance, dependency updates

## Dependency Management

- **Internal packages**: Always use workspace protocol references (\`workspace:*\`)
- **Peer dependencies**: Use caret ranges (\`^\`) for compatibility
- **Regular dependencies**: Pin exact versions for reproducibility
- After adding dependencies, run \`pnpm exec dm check\` to sync and validate

## Linting & Formatting

This project uses [datamitsu](https://datamitsu.com/) as the unified linting and formatting orchestrator. All checks run through a single command:

\`\`\`bash
pnpm exec dm check
\`\`\`

Do not configure or run individual linters/formatters directly — datamitsu manages the full toolchain.

## AGENTS.md Maintenance

**Keep AGENTS.md in sync with code changes.** Whenever you make changes to the codebase, update AGENTS.md:

1. **Add to "Known Pitfalls"** if you encountered issues
2. **Update commands** if scripts change
3. **Add examples** for new patterns introduced
4. **Update architecture notes** for significant refactoring

**Golden Rule**: If you had to figure something out, document it so others (and future AI agents) don't have to.

## Verification Checklist

Before completing any task:

1. Run the test suite if tests exist
2. Run \`pnpm exec dm check\`
3. Verify build succeeds
4. Update AGENTS.md if a new pattern or pitfall was discovered

## TypeScript Configuration

When creating or modifying \`tsconfig.json\` files, consult the [TypeScript Configuration Guide](.datamitsu/tsconfig.md).`;

const CHUNK_00_DEPENDABOT = `## Dependabot (public GitHub repos only)

Keep \`.github/dependabot.yml\` accurate **only when this is a public GitHub repository**. Confirm before acting — e.g. \`gh repo view --json visibility,isPrivate\`. If the repo is private, not on GitHub, or you cannot determine this, **do nothing** and leave the file absent.

When it is a public GitHub repo:

1. **Ensure the file exists** if the repo has any supported ecosystem (npm/pnpm, Go modules, pip/uv, Cargo, Terraform, Docker, GitHub Actions). A minimal \`version: 2\` file with an empty \`updates:\` list is enough to opt in — \`dm setup\` fills in the rest.
2. **Own the \`updates\` entries** (the "what"): the \`package-ecosystem\` values and their \`directory\`/\`directories\`. Keep these in sync with the project's real layout — add an entry when a new workspace/service/ecosystem appears, remove one when it goes away.
3. **Do NOT hand-tune policy fields.** \`commit-message\`, \`versioning-strategy\`, \`schedule\`, \`groups\`, and \`open-pull-requests-limit\` are owned by datamitsu and are normalized on every \`dm setup\` (conventional-commit prefixes such as \`chore(deps):\`, weekly cadence, grouped PRs). Editing them by hand is pointless — they will be overwritten.
4. **Run \`pnpm exec dm setup\` after editing** so datamitsu re-applies the managed policy. datamitsu never creates this file on its own; it only normalizes one that already exists.`;

const CHUNK_00_SCRIPTS = `## Project Scripts

Every package in the repository — regardless of language (TypeScript, Go, Python, Rust, Swift, Kotlin) — exposes a \`package.json\` with a unified set of scripts. This makes project entry points identical across the monorepo: the same command names work everywhere, and \`turbo\` orchestrates them from the root.

### Promise

Any package in this monorepo runs with \`pnpm install && pnpm dev\`, regardless of the language inside. New contributors do not need to learn the underlying toolchain (Go, Rust, Python, Swift) to start the happy path. Toolchain-specific knowledge is required only when working on optimizations, edge cases, or build internals.

### Standard Scripts

Implement the relevant subset in each package. Names and meanings are fixed.

#### Run

- **\`dev\`** — Start everything required for the package to run: dev server, backend, infrastructure containers (without \`-d\`), workers. From the monorepo root, \`dev\` brings the whole project up. Persistent.
- **\`dev:mock\`** — Same as \`dev\`, with external dependencies mocked. Optional. Persistent.

#### Build

- **\`codegen\`** — Generate code from schemas: SDKs from OpenAPI/GraphQL/protobuf, DB types, i18n types. Idempotent.
- **\`build:lib\`** — Preparatory steps required before \`dev\` or \`build\`: asset prelinking, intermediate internal libraries, static preparation. Depends on \`codegen\`.
- **\`build\`** — Final application or library build. Depends on \`build:lib\`. Same name regardless of target (SPA, binary, npm package, WebAssembly artifact).

#### Test

- **\`test\`** — Fast tests: units, integration without infrastructure.
- **\`test:watch\`** — \`test\` in watch mode. Persistent. Fast tests only.
- **\`test:coverage\`** — Run tests with coverage collection.
- **\`test:e2e\`** — End-to-end tests: real browser, testcontainers, full infrastructure.
- **\`test:e2e:ui\`** — UI mode for the e2e runner, where supported.
- **\`test:e2e:install\`** — Install e2e runner dependencies (e.g., browsers). Idempotent.
- **\`test:snapshots\`** — Visual / screenshot tests.
- **\`test:snapshots:update\`** — Update screenshot baselines.
- **\`test:update\`** — Update inline snapshots.

#### Quality

Always run \`pnpm dm check\` after completing a task. This runs fixers (formatters, auto-fixes) followed by linters (type checking, ESLint). It should complete with no errors.

#### Misc

- **\`pull:*\`** — Fetch external artifacts (OpenAPI schemas, auth context, etc.).
- **\`upgrade:deps\`** — Update dependencies.

### Naming Rules

- A colon means specialization of an existing command. \`test:e2e\` is a kind of \`test\`. \`build:lib\` is a kind of \`build\`. New top-level names are not introduced.
- Environment is passed via variables, never encoded in the script name. No \`dev:fast\`, \`build:prod\`, \`test:ci\`.

### Complex Orchestration

When a script grows past a single command — multiple steps, parallelism, dependencies, conditions, intermediate variables — it moves to \`Taskfile.yml\`. The \`package.json\` script becomes a thin entry point that delegates:

\`\`\`json
{
  "scripts": {
    "build": "pnpm dm exec task -- build",
    "build:lib": "pnpm dm exec task -- build:lib"
  }
}
\`\`\`

The standard names above never change — only what they delegate to.

#### Taskfile Conventions

- Every task has a \`desc\` field.
- \`deps\` for parallel prerequisites, \`cmds\` for sequential steps.
- Namespacing matches script names: \`build:*\`, \`test:*\`, \`dev:*\`.

\`\`\`yaml
version: "3"

tasks:
  build:
    desc: Full application build
    deps: [build:lib]
    cmds:
      - pnpm exec tsdown

  build:lib:
    desc: Generate SDK and build internal libraries
    deps: [codegen]
    cmds:
      - pnpm --filter @scope/shared build

  codegen:
    desc: Generate types from OpenAPI schema
    sources: [schema.yaml]
    generates: [src/generated/api.ts]
    cmds:
      - pnpm exec openapi-typescript ./schema.yaml -o ./src/generated/api.ts
\`\`\`

### Turborepo

Pipeline tasks are declared in \`turbo.json\`:

- \`dependsOn: ["^build"]\` for cross-package dependency ordering.
- \`"cache": false\` for non-cacheable tasks (\`dev\`, \`pull:*\`).
- \`"persistent": true\` for long-running tasks (\`dev\`, \`dev:mock\`, \`test:watch\`).
- \`"outputs"\` for cacheable build artifacts (\`dist/**\`, \`.next/**\`, etc.).

### Anti-Patterns

DO NOT:

- Invent script names outside the standard list (\`start\`, \`serve\`, \`compile\`, \`unit\`, \`typecheck\`, \`check\`, \`lint:fix\`, \`start:dev\`).
- Chain commands with \`&&\` in \`package.json\`. Move to Taskfile.
- Write \`.sh\` scripts for orchestration. Move to Taskfile.
- Use Makefiles. Use Taskfile.
- Encode environment in the script name. Use variables.
- Add a \`clean\` script. Use \`git clean -fdx\`.`;

const CHUNK_10_DOCS = `## Documentation Policy

Documentation is a required deliverable for every user-facing change — not optional.

When implementing features or making changes, documentation MUST be updated in the same PR/commit:

- **User-facing features** → update docs with examples
- **API changes** → update reference docs
- **Breaking changes** → document migration path

### Documentation Quality

- Review documentation changes with the same rigor as code
- Check for clarity, accuracy, and completeness
- **Test all code examples before merging** — examples that don't work erode trust

### Diagrams

- Use Mermaid for architectural diagrams — GitHub renders them natively in Markdown
- Keep diagrams as code for version control
- Prefer diagrams over lengthy textual explanations for flows, architecture, and data pipelines

### llms.txt Maintenance

If the project provides an \`llms.txt\` file (served via website or accessible via raw git URL, per [llmstxt.org](https://llmstxt.org/)):

- Keep it in sync with the actual documentation structure
- All links must point to valid, existing pages
- Update when adding new major sections, packages, or resources
- Do not add internal or draft documentation links`;

const CHUNK_20_DOCS_MARKDOWN = `## Documentation Surface

All user-facing documentation lives in Markdown files within the repository. Primary surfaces:

- **\`docs/\`** — detailed guides, API reference, architecture docs
- **\`README.md\`** — entry point; keep focused but may include more detail than a website-backed project

When implementing features or making changes, update the relevant \`docs/\` files or README in the same PR/commit:

- **CLI commands** → update command reference in \`docs/\`
- **Configuration options** → update config reference in \`docs/\`

### README.md Scope

README serves as the primary documentation entry point. Include:

1. **What is this** — One paragraph description
2. **Quick install** — Single command
3. **Basic usage** — Minimal example (3-5 lines of code)
4. **Links** — Point to relevant \`docs/\` files for deeper topics

Keep README focused. Detailed architecture explanations and full API references belong in \`docs/\`, not inline.`;

const CHUNK_20_DOCS_WEBSITE = `## Documentation Surface

**All user-facing documentation lives in the documentation website. README.md files must remain minimal.**

When implementing features or making changes, documentation MUST be updated in the same PR/commit:

- **User-facing features** → update website docs with examples and guides
- **API changes** → update reference pages
- **CLI commands** → update command reference
- **Configuration options** → update config reference
- **Breaking changes** → document migration path

### README.md Scope

README must be kept **minimal** and focused on:

1. **What is this** — One paragraph description
2. **Quick install** — Single command or link to installation docs
3. **Basic usage** — Minimal example (3-5 lines of code)
4. **Link to full documentation** — Point to docs website

**Do NOT add to README.md:** detailed usage guides, configuration examples, architecture explanations, or API reference. These belong in the documentation website.

### Visual Documentation

- Add diagrams for complex architectural concepts
- Use screenshots for UI-related features — show, don't just tell
- Keep diagrams as code (Mermaid preferred) for version control
- Store screenshots in the website's static assets with descriptive names`;

// ── Joined combinations ─────────────────────────────────────────────────────
export const AGENTS_BASE = [CHUNK_00_BASE, CHUNK_00_DEPENDABOT, CHUNK_00_SCRIPTS].join("\n\n"); // prettier-ignore
export const AGENTS_DOCS_MARKDOWN = [CHUNK_00_BASE, CHUNK_00_DEPENDABOT, CHUNK_00_SCRIPTS, CHUNK_10_DOCS, CHUNK_20_DOCS_MARKDOWN].join("\n\n"); // prettier-ignore
export const AGENTS_DOCS_WEBSITE = [CHUNK_00_BASE, CHUNK_00_DEPENDABOT, CHUNK_00_SCRIPTS, CHUNK_10_DOCS, CHUNK_20_DOCS_WEBSITE].join("\n\n"); // prettier-ignore

// ── Chunk hashes (sha256, computed at build time) ────────────────────────────
export const CHUNK_00_BASE_HASH = "783962987ce37124cfa3031f207b7ada24dc42f3cc809a7c0fdbf6617200d2d4"; // prettier-ignore
export const CHUNK_00_DEPENDABOT_HASH = "db054ec686a4cefaeaa60acf4f55fc22b84d9859b4c321a1ef838728cdd27e11"; // prettier-ignore
export const CHUNK_00_SCRIPTS_HASH = "211a1e7636bb583b8a2743b1937d61a203ab8d62940a186c0fbc0fcd156e5ec6"; // prettier-ignore
export const CHUNK_10_DOCS_HASH = "535b8ce9282c78a5328528d9455357584fe6f3021f1fda2150066f5e6c083137"; // prettier-ignore
export const CHUNK_20_DOCS_MARKDOWN_HASH = "00d40fa915002c384542cafda336e2fde0afa10de896f2e204494b46ea58e160"; // prettier-ignore
export const CHUNK_20_DOCS_WEBSITE_HASH = "072c1c9cff927e51063758ac779408cbc68b855e0f1e2cc6297365fd850ebd1e"; // prettier-ignore

export const ALL_AGENTS_HASHES = [CHUNK_00_BASE_HASH, CHUNK_00_DEPENDABOT_HASH, CHUNK_00_SCRIPTS_HASH, CHUNK_10_DOCS_HASH, CHUNK_20_DOCS_MARKDOWN_HASH, CHUNK_20_DOCS_WEBSITE_HASH]; // prettier-ignore
