/**
 * WASM output-parser module pin.
 *
 * Datamitsu turns a tool's machine-readable output into structured diagnostics with a signed
 * Rust→WASM parser module. Tools opt in by name via `outputParser` (see ./tools.ts); a module
 * declared but unreferenced is harmless.
 *
 * The single module dispatches every tool's parser by name, so one `parsers` entry ("core") serves
 * all of them. It is downloaded once and SHA-256 verified against `hash` before it is loaded into
 * the sandboxed WASM runtime.
 *
 * Sourced from the registry rather than a release asset. The module is delivered over two channels
 * — a GitHub release asset (`url`) and an OCI artifact (`oci`) — and an entry declares exactly one;
 * there is no fallback chain. `oci` is used because the registry copy always exists: unstable
 * builds reach npm and the registry without always getting a GitHub release cut, so the release
 * asset can 404 for a version that otherwise exists.
 *
 * `hash` does double duty on this channel: it is the module's SHA-256 _and_ the expected digest of
 * the artifact's single layer, so a manifest pointing at other content is rejected before a single
 * payload byte is requested.
 *
 * Generated by scripts/sync-parsers.ts from the pinned build's own `parsers-oci.json` — do not
 * edit. Both values change on every release even when the parser sources do not, because the
 * module's version string is compiled into it.
 *
 * Pinned to datamitsu unstable-20260926-c963f6f.
 */

const PARSERS_OCI_REF = "ghcr.io/datamitsu/datamitsu-parsers-unstable";
// Wrapped because prettier does: "sha256:" plus 64 hex characters always overruns the line width,
// and an unwrapped line here would leave every `task refresh` with a file the formatter rewrites
// and `validate:parsers` then rejects.
const PARSERS_OCI_DIGEST =
  "sha256:4da914c5ba6b1ef3b87f78ad393028f0e9be00dfdbd70ea0dc613abd8c3e1e66";

const CORE_PARSER_HASH = "ab00710ee054e152f64941c5072ba8334d3a579091af9e8fa5c8db3bc2afe051";

export const parsers: config.MapOfParsers = {
  core: {
    hash: CORE_PARSER_HASH,
    oci: {
      digest: PARSERS_OCI_DIGEST,
      ref: PARSERS_OCI_REF,
    },
  },
};
