/**
 * WASM output-parser module pin.
 *
 * Datamitsu turns a tool's machine-readable output into structured diagnostics with a signed
 * Rust→WASM parser module. Tools opt in by name via `outputParser` (see ./tools.ts); a module
 * declared but unreferenced is harmless.
 *
 * The single module dispatches every tool's parser by name, so one `parsers` entry ("core") serves
 * all of them. It is downloaded once and SHA-256 verified against `hash` before it is loaded into
 * the sandboxed WASM runtime.
 *
 * Sourced from the registry rather than a release asset. The module is delivered over two channels
 * — a GitHub release asset (`url`) and an OCI artifact (`oci`) — and an entry declares exactly one;
 * there is no fallback chain. `oci` is used because the registry copy always exists: unstable
 * builds reach npm and the registry without always getting a GitHub release cut, so the release
 * asset can 404 for a version that otherwise exists.
 *
 * `hash` does double duty on this channel: it is the module's SHA-256 _and_ the expected digest of
 * the artifact's single layer, so a manifest pointing at other content is rejected before a single
 * payload byte is requested.
 *
 * Generated by scripts/sync-parsers.ts from the pinned build's own `parsers-oci.json` — do not
 * edit. Both values change on every release even when the parser sources do not, because the
 * module's version string is compiled into it.
 *
 * Pinned to datamitsu 0.3.1.
 */

const PARSERS_OCI_REF = "ghcr.io/datamitsu/datamitsu-parsers";
// Wrapped because prettier does: "sha256:" plus 64 hex characters always overruns the line width,
// and an unwrapped line here would leave every `task refresh` with a file the formatter rewrites
// and `validate:parsers` then rejects.
const PARSERS_OCI_DIGEST =
  "sha256:144680b2443151421b6f10d73daed524fc178ef5be9800ec8cdde159e8b71830";

const CORE_PARSER_HASH = "fe25e350799945b6c8930632d14c98bd82838d03522a11d069cdd66bb608ae65";

export const parsers: config.MapOfParsers = {
  core: {
    hash: CORE_PARSER_HASH,
    oci: {
      digest: PARSERS_OCI_DIGEST,
      ref: PARSERS_OCI_REF,
    },
  },
};
