// prettier-ignore
/* eslint-disable */

// AUTO-GENERATED by scripts/gen-skills.ts — do not edit manually

// ── Skill: backlog ─────────────────────────────────────────────────────────

const SKILL_BACKLOG_INSTRUCTIONS = `# Backlog

Deferred work lives in \`docs/backlog/\`, one Markdown file per item, tracked in git alongside the
code it describes.

A backlog entry is what you write when you **stumble over something real and decide not to fix it
now**: a defect nobody has time for, a design that has drifted, an idea worth keeping. It is not a
plan. A plan (\`docs/plans/\`) is a sequence of tasks somebody is about to execute; a backlog entry
is a note to whoever arrives next, and its job is to stop the same finding from being rediscovered,
re-argued, and re-forgotten.

Writing one costs a minute. Not writing one costs the next person the whole investigation.

---

## Search it before you start

The backlog is worth more as a **thing you read** than as a thing you write. What makes an entry
valuable is _when_ it was written, not who wrote it: at the moment the problem was understood,
while the context that made it understandable still existed. That context is the expensive part,
it does not survive, and it sits in a directory nobody thinks to open.

Search before investigating a defect, before a performance or correctness investigation, before
writing a plan, before proposing a design change, and whenever the user asks why something is the
way it is:

\`\`\`bash
rg -i "<symptom>" docs/backlog/           # matching lines — read these, they are the point
rg -i "<subsystem or file>" docs/backlog/
rg -il "<term>" docs/backlog/             # just the filenames, when a term hits everywhere
ls docs/backlog/                          # the slugs alone are a table of contents
\`\`\`

\`rg\`, not \`grep\`: the two take different flags, \`grep\` is aliased on many machines, and ripgrep
recurses by default (no \`-r\`). If \`rg\` is genuinely unavailable, \`grep -ri\` is the equivalent — but
say which one you used, because a search that silently found nothing because of a flag is worse
than no search.

Read the **matching lines**, not just the filenames. The slug names one symptom; the body may
mention the same subsystem for a different reason, and that is often the useful hit — which is why
the plain form comes first and \`-l\` is the fallback for a term that matches everything.

### What a hit gives you

- **The investigation, already done.** A reproduction, a measurement, the approach that was tried
  and abandoned, the constraint that rules out the obvious fix. Re-deriving it costs hours.
- **A triage decision that is re-opened, not settled.** \`later\` and \`no\` were judgments made under
  the circumstances of the \`added:\` date. Circumstances change: a cost nobody noticed at 1,000
  files matters at 50,000; a fix blocked on an unreleased dependency stops being blocked once it
  ships. Read _why_ it was deferred and check whether that reason still holds.
- **A dead end worth respecting.** A \`no\` that explains itself saves you from re-arguing a finding
  that was already argued.

### What to do with a hit

1. **Verify the anchor.** The \`where:\` line may point at code that has since moved. If it has, say
   so — the entry is evidence, not truth, and a stale anchor changes how much of it to trust.
2. **Tell the user you found it**, with the \`added:\` date and the current \`worth:\`. Do not assume
   they know it exists — an entry may predate the current conversation by a year, and whether a
   person or an agent wrote it says nothing about whether it is still right.
3. **Say whether the triage still holds.** If the premise behind a \`later\` or a \`no\` has expired,
   name that explicitly rather than quietly proceeding as if the old verdict were binding, and
   propose re-triaging it.
4. **Fold its content into your work.** If you are writing a plan, the entry's measurements and
   dead ends belong in the plan's context section, with the entry named as their source.
5. **Sharpen the entry** if your work turned up detail it lacks, even when you are not fixing it.

A search that finds nothing costs seconds. A search skipped can cost a day spent rediscovering
something already written down.

---

## The format

\`docs/backlog/<slug>.md\`, where the slug names **the symptom, not the fix** — someone scanning the
directory should recognize a problem they have hit.

\`\`\`markdown
---
worth: yes | later | no
where: path/to/file.go:120
added: 2026-08-27
---

# One sentence naming the symptom

What happens, and where. Enough for a reader to find it without repeating the investigation.

Why it is not being fixed now, or what is unknown. For \`later\`, name the unresolved question
explicitly. For \`no\`, say why it was rejected.

Any direction worth preserving: a proposed approach, a measurement, a constraint that rules an
obvious fix out.

How it was found, if that context helps the next reader trust or re-check it.
\`\`\`

### Frontmatter

| Field   | Meaning                                                                                                                                                                                  |
| ------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| \`worth\` | \`yes\` — agreed worth fixing, unscheduled. \`later\` — the _value_ is undecided; the body must name what is unknown. \`no\` — decided against; the body must say why, so it is not re-argued. |
| \`where\` | Optional anchor, \`path:line\`. Omit when the item is not tied to one place.                                                                                                               |
| \`added\` | Creation date, \`YYYY-MM-DD\`. **Never modified** — its age is the signal.                                                                                                                 |

\`worth\` is a judgment about **value**, not urgency and not effort. An item that is clearly worth
fixing but will take a week is still \`yes\`.

### Body

Prose, not checklists. Short — a reader should absorb it in under a minute. Include a measurement
if one exists; a number is what turns "this feels slow" into something actionable later. Link to a
PR or issue if one exists.

Do not write an implementation plan. If the item is well-understood enough to plan, it does not
belong in the backlog — write the plan instead.

---

## Lifecycle

Entries are created as part of whatever work uncovered them, and deleted by \`git rm\` **in the same
commit as the work that resolves them**. The deletion is the record that it was done; git history
holds the rest. Do not add a \`status: done\` field and leave the file behind.

An item dropped as no-longer-relevant is removed the same way, with the reasoning in the commit
message.

---

## When not to write an entry

A backlog nobody reads is worse than no backlog: it also creates the false impression that
everything is written down. Every entry costs a reader attention, so the bar is that somebody could
pick it up and act on it.

Do not create an entry for:

- **Something you are fixing now.** Fix it. The commit is the record.
- **A preference.** "I would have structured this differently" is not a defect.
- **An unexamined hypothesis.** If you have not checked it, you are asking the next reader to do
  the investigation twice. Check it, or say plainly in the body that it is unverified and what
  would verify it.
- **Something already tracked** in an issue tracker or another entry. Link or sharpen instead.
- **A note to yourself.** Session context, user preferences and reminders belong to agent-private
  memory, not to a file every contributor pulls. The backlog is about the codebase, not about the
  work session.
- **Something understood well enough to plan.** That is a plan (\`docs/plans/\`), not a backlog entry.

If it does not clear the bar and you still think it matters, say so to the user rather than
committing it.

---

## Creating an entry

0. **Create \`docs/backlog/\` if it does not exist.** No README, no index — the directory listing is
   the table of contents, and an index file goes stale the first time somebody forgets it.
1. **Check for a duplicate first.** Match on the slug _and_ on \`where\`. If an entry already covers
   it, sharpen that one rather than adding a second — a backlog with two entries for one defect is
   how a backlog stops being read.
2. **Verify the anchor.** If you write \`where: path:line\`, open it and confirm the line still says
   what you claim. A stale anchor is worse than none.
3. **Pick \`worth\` honestly.** If you cannot tell whether it is worth fixing, that is \`later\`, and
   the body must say what would settle it.
4. **Apply the privacy rules.** Backlog entries are published. Measurements from a private
   repository keep their shape and lose their identity; another project is not named without
   explicit permission. See the Privacy and Attribution section of the shared agent rules.
5. **Do not commit unasked.** Write the file and report it. Committing is the user's call unless
   they have said otherwise.

---

## Working an entry

When asked to work on a backlog item, before touching anything:

1. Read the file and **verify the anchor still holds**. If the code moved, say so — the entry may
   be stale, and re-deriving it is part of the job.
2. Report four things, briefly: what it is, roughly what it takes, what it touches, and whether it
   still matters.
3. Ask what to do with concrete options — fix it now, re-triage it (\`worth\` changed), sharpen the
   entry, or drop it.

Only then start. When the work lands, \`git rm\` the entry in the same commit.

Working several items at once: verify every anchor first, name any ordering constraints between
them, then take them one at a time with visible progress. Re-verify immediately before each change
— an earlier item may have moved the code a later one points at. Run the project's tests and
linters as usual. Never commit automatically.

---

## Branch safety

Before writing or removing an entry, check the current branch against the repository's default
branch. If they differ, confirm with the user first — a backlog edit stranded on a feature branch
is invisible to everyone else, and one committed to the default branch by accident is noise in
someone's history.`;

const SKILL_BACKLOG_ADAPTER_CLAUDE = `---
name: backlog
description: Read, create, triage and work deferred-work items in docs/backlog/ — one Markdown file per item, tracked in git. Use this skill whenever the user wants to record something they have decided not to fix now ("add this to the backlog", "note it for later", "let's not solve this now, write it down"), or to act on what is already recorded ("what's in the backlog", "work the backlog", "pick up <slug>"). Also use it when you stumble over a real defect or design drift while doing something else and the user does not want to divert — the entry is how the finding survives.
---

# Backlog

Read \`.datamitsu/ai/skills/backlog/instructions.md\` from the project root and follow it precisely.

The instructions file is the source of truth for this skill — it is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current chunks.`;

const SKILL_BACKLOG_ADAPTER_CODEX = `# /backlog

Read, create, triage and work deferred-work items in \`docs/backlog/\` — one Markdown file per item, tracked in git.

Read \`.datamitsu/ai/skills/backlog/instructions.md\` from the project root and follow it precisely.

The instructions file is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current chunks.`;

// ── Skill: cleanup-agents-md ───────────────────────────────────────────────

const SKILL_CLEANUP_AGENTS_MD_INSTRUCTIONS = `# Cleanup AGENTS.md

You are about to clean up the project's \`AGENTS.md\`. The job has two halves:

1. **Remove what is already guaranteed elsewhere** — content covered by the shared chunks deployed
   via [datamitsu](https://datamitsu.com/) into \`.datamitsu/ai/agents/agents-*.md\`, and non-rule
   content (architecture docs, templates, release notes) that belongs in its own file.
2. **Compact what is left** — without changing what an agent reading the file would do.

The shared chunks are the **source of truth**. The project's \`AGENTS.md\` should contain only what is
specific to this project and not covered by the chunks. Additionally, \`AGENTS.md\` is for
**prescriptive rules** — descriptive documentation of internals belongs in dedicated docs files, not
in agent instructions.

The goal is **not** fewer lines. It is the smallest number of tokens an agent needs to reproduce the
same behavior — with every rule, condition, exception, exact literal and degree of obligation
intact. A cleanup that removes 60% of the lines and one unique rule is a failure.

This skill is destructive — it rewrites \`AGENTS.md\` and may create new files. Always follow the
propose → confirm → apply order. Never apply without explicit confirmation.

---

## Invariants

These hold at every step. If an action would break one, do not take it — report instead.

1. **No silent rule loss.** Every prescriptive statement in the original ends up with an explicit
   disposition (Step 6). "It disappeared" is not a disposition.
2. **No silent conflict resolution.** Similar-but-different statements are never canonicalized into
   one without proven equivalence. Report them; do not pick a winner.
3. **Normative strength is preserved.** \`NEVER\` does not become \`avoid\`; \`prefer\` does not become
   \`always\`.
4. **Exact literals are preserved.** Commands, flags, paths, package names, identifiers, config keys
   and versions are never rewritten from memory, "corrected", or normalized.
5. **The chunk is read-only.** Nothing under \`.datamitsu/\` is modified, ever.
6. **Project exceptions survive.** A rule that extends or contradicts a chunk rule is not a
   duplicate — it is the reason the project has an \`AGENTS.md\`.
7. **Propose before mutate.** No destructive change without explicit confirmation.
8. **Semantics over line count.** Quality is measured by behavior preserved, not by percentage
   removed.

---

## Step 1 — Discovery

1. Read \`AGENTS.md\` from the project root.
2. Find the **bootstrap line** — a single bold paragraph starting with \`**Read [.datamitsu/\`.
3. Parse the path inside the link to identify the active chunk file. Expected values:
   - \`.datamitsu/ai/agents/agents-base.md\`
   - \`.datamitsu/ai/agents/agents-docs-markdown.md\`
   - \`.datamitsu/ai/agents/agents-docs-website.md\`
4. Read the referenced chunk file. Treat it as read-only — never modify anything in \`.datamitsu/\`.
5. If the bootstrap line is missing or points outside \`.datamitsu/\`, abort:
   > This project's \`AGENTS.md\` does not reference any datamitsu chunk. This skill only works with
   > datamitsu-managed projects. Aborting.

If \`CLAUDE.md\` exists in the project root **as a real file** (not a symlink to \`AGENTS.md\`), note it
and report at the end — do not auto-merge.

Survey the project structure to determine extraction targets:

- Does \`docs/\` exist? If so, note subdirectories (e.g., \`docs/architecture/\`, \`docs/guides/\`,
  \`docs/templates/\`).
- Does \`CHANGELOG.md\` exist?
- Note the project name and purpose from \`package.json\`, \`README.md\`, or similar.

---

## Step 2 — Parse into regions

Identify three regions in this exact order:

1. **Override block** — everything between the \`# AGENTS.md\` heading and the bootstrap line. May be
   empty. Project-specific overrides of chunk rules live here. **Never modify.**
2. **Bootstrap line** — the one bold paragraph that references the chunk. **Never modify.**
3. **Project content** — everything below the bootstrap line. Split into sections by \`##\` (h2)
   headings. Subsections (\`###\` and deeper) belong to their parent section.

Sections are the unit of **structure and reporting**. They are not the unit of decision — that is
Step 3.

---

## Step 3 — Atomize

A whole section is too coarse to classify. One section routinely contains a prescriptive rule, a
paragraph of architecture, a rationale, an example, a project-specific exception and a chunk
duplicate — all at once, and each wants a different action.

Break the content down:

\`\`\`text
Section
  → semantic spans          (a contiguous run of lines that says one thing)
    → atomic statements     (one rule, one condition, one exception, one example)
\`\`\`

Assign every span a **role**:

| Role          | What it is                                                      | Can compact?                        |
| ------------- | --------------------------------------------------------------- | ----------------------------------- |
| \`rule\`        | Prescriptive — tells the reader to do or not do something       | Wording yes, meaning no             |
| \`condition\`   | When the rule applies                                           | Never drop                          |
| \`exception\`   | When the rule does not apply                                    | Never drop                          |
| \`rationale\`   | Why the rule exists                                             | Drop unless it resolves ambiguity   |
| \`example\`     | Shows the rule in use                                           | Drop unless it defines the contract |
| \`descriptive\` | How the system works; asks nothing of the reader                | Extract, do not compact             |
| \`literal\`     | An exact command, path, flag, identifier, config key or version | Never rewrite                       |

### Normative strength

Modality is part of a rule's meaning. These tiers are **not** interchangeable:

\`\`\`text
NEVER / MUST NOT  >  MUST / ALWAYS  >  SHOULD  >  PREFER  >  MAY  >  descriptive
\`\`\`

Record the tier of every \`rule\` span. Compaction may not weaken it and may not strengthen it.

> \`Prefer X.\` is not \`Always use X.\`
> \`Never bypass commit hooks.\` is not \`Do not normally bypass commit hooks.\`

### Exact literals

Record every literal verbatim: commands and their exact shape, paths, flags, script names, package
names, identifiers, config keys, versions, environment variable names, and any \`<!-- hits: N -->\`
markers.

\`pnpm exec dm check\` and \`pnpm dm check\` are **different strings**. Never "improve" a literal from
memory, and never reconcile two variants of one. If you believe a literal in the file is wrong,
report it as a conflict — fixing it is not this skill's job.

---

## Step 4 — Classify each span

Every span gets exactly one category. A single section may produce deletions, extractions and
retained rules simultaneously — that is normal and expected.

### Against the chunk

| Category              | Definition                                                | Action                         |
| --------------------- | --------------------------------------------------------- | ------------------------------ |
| \`duplicate-of-chunk\`  | Semantically covered by a rule in the active chunk        | Delete                         |
| \`project-unique-rule\` | Prescriptive rule specific to this project, not in chunks | Keep semantics (Step 5)        |
| \`project-exception\`   | Extends or contradicts a chunk rule for this project      | Keep; never treat as duplicate |

\`partial-duplicate\` is no longer a category — it was an artifact of classifying whole sections. At
span level a mixed section simply yields some \`duplicate-of-chunk\` spans and some kept ones.

### Against the rest of the project file

| Category                     | Definition                                                      | Action                                  |
| ---------------------------- | --------------------------------------------------------------- | --------------------------------------- |
| \`internal-duplicate\`         | Says the same thing as another span in this file                | Merge into one canonical spot           |
| \`internal-partial-duplicate\` | Overlaps another span but adds a condition or exception         | Merge, keeping every distinct condition |
| \`complementary\`              | Refines another span rather than repeating it                   | Keep both                               |
| \`potential-conflict\`         | Similar to another span but differs in a way you cannot resolve | Keep both, report (Step 4.1)            |

**Duplicate is not the same as complementary.** These two are not one rule:

\`\`\`text
Run tests before finishing.
Run integration tests when infrastructure changed.
\`\`\`

Merging them into "Run tests" silently deletes a condition. Keep both, or merge into a single
statement that still carries the condition.

### By content type

| Category               | Definition                                                                       | Action                             |
| ---------------------- | -------------------------------------------------------------------------------- | ---------------------------------- |
| \`pitfall\`              | A specific bug, race or footgun in this codebase                                 | Keep semantics; may compact        |
| \`deferred-work\`        | A defect, gap or drift recorded but not fixed — no rule for the reader to follow | Relocate to \`docs/backlog/\`        |
| \`architectural-detail\` | Descriptive documentation of a subsystem (not a rule)                            | Extract to docs file               |
| \`template-material\`    | Reusable template skeleton (e.g., installation tabs, annotation boilerplate)     | Extract to docs file               |
| \`release-note\`         | Description of a past migration or breaking change                               | Extract to docs or CHANGELOG       |
| \`migration-cruft\`      | Wrapper headings/boilerplate left from a CLAUDE.md→AGENTS.md migration           | Strip cruft, integrate content     |
| \`project-context\`      | README-style content (mission, package list, repo tree, key deps)                | Keep the minimum; extract the rest |

### Step 4.1 — Conflict detection

**Similarity is not equivalence.** Two statements are duplicates only if you can demonstrate they
mean the same thing. They are **not** duplicates if they differ in any of:

- command literal · path · flag · package name
- scope · condition · exception · negation
- normative strength

When they differ and the context does not let you prove which is correct, classify both as
\`potential-conflict\`:

\`\`\`text
pnpm exec dm check
pnpm dm check
\`\`\`

The skill does not pick a winner because the two commands resolve differently. Keep both spans in
place, list them under **Potential conflicts** in the proposal, and let the user decide. Destructive
canonicalization without sufficient grounds is forbidden.

### Classification rules

**Semantic, not textual.** Project spans often reword chunk rules in different words. Same intent
and content = duplicate, regardless of wording.

**Prescriptive vs descriptive distinguishes rule from architecture.** A 60-line description of how
the retry orchestrator works internally is \`architectural-detail\`. A 2-line statement "always call
\`markRetryHealthyBoot\` after a successful boot, otherwise X" is \`project-unique-rule\`. Length is not
the criterion — the question is "does this tell the agent what to do (rule)" or "does this describe
how the system works (architecture)".

**Pitfall detection.** A span is a \`pitfall\` if any of these match:

- Its heading contains: \`Pitfall\`, \`Known Pitfalls\`, \`Известные проблемы\`, \`Подводные камни\`,
  \`Gotcha\`, \`Common mistakes\`, \`Lessons learned\`
- It belongs to a parent section matching those patterns
- It describes a specific bug, race, footgun, or mistake to avoid in this codebase
- It contains \`<!-- hits: N -->\` markers — these are project state and must be preserved exactly

**Deferred work vs pitfall.** Both describe something wrong, and they are told apart by what the
reader is supposed to do:

- A **pitfall** tells the reader how to avoid stepping on something. It changes what they do today.
  "\`pnpm test\` must run with \`umask 022\` or the source-mode tests fail on the test binary's own
  mode" is a pitfall — knowing it changes the next command you type.
- **Deferred work** is a defect nobody is fixing right now, with nothing for the reader to do
  differently. "The store grows without bound; every config-hash change orphans a directory" is
  deferred work — there is no behavior it asks of the reader, only an action waiting for somebody.

Markers of \`deferred-work\`: "TODO", "FIXME", "not implemented yet", "should eventually", "known
limitation", "we plan to", a described bug with no workaround given.

Relocate these to \`docs/backlog/\`, one file per item, in the format the \`backlog\` skill defines.
**Never delete them.** They are the most expensive content in the file — written when the problem
was understood — and deleting them destroys exactly what the backlog exists to preserve. When in
doubt between \`pitfall\` and \`deferred-work\`, keep it as a pitfall: leaving it in \`AGENTS.md\` costs a
few lines, and losing it costs the investigation.

**Project context is judged by necessity, not by length.** Keep only the minimum context an agent
needs to interpret the prescriptive rules that follow; extract the rest regardless of how short it
is. "This repository contains the CLI and its documentation website" earns its place if later rules
say "CLI" and "website". A mission statement, a repo tree, a full package catalog, a dependency
list, or an architecture overview that prescribes nothing does not — a README-style paragraph does
not become an agent instruction by being 19 lines long.

**Migration cruft detection.** A section is \`migration-cruft\` if:

- Heading is "Migrated From CLAUDE.md", "From CLAUDE.md", or similar migration-provenance heading
- It contains only a child \`# CLAUDE.md\` heading and/or boilerplate like "This file provides
  guidance to Claude Code (claude.ai/code)..." with no prescriptive rules
- It wraps other sections that would otherwise be top-level — the wrapper itself is cruft, the
  wrapped content is classified independently

When stripping migration cruft: remove the wrapper heading and any boilerplate lines. Promote
wrapped subsections one heading level up (e.g., \`###\` under \`## Migrated From CLAUDE.md\` becomes
\`##\`). Preserve all prescriptive content inside.

**Misplaced overrides.** If a span explicitly contradicts or extends a chunk rule (e.g., "in this
fork, commits follow the upstream format, not Conventional Commits"), it is a legitimate override —
but it should live in the override block above the bootstrap line, not below. Classify as
\`project-exception\` and add a note: "Consider moving to override block above bootstrap line".

**Be conservative.** When in doubt between \`duplicate-of-chunk\` and \`project-unique-rule\`, choose
\`project-unique-rule\`. False positive (deleting useful project content) is worse than false negative
(leaving a small duplicate).

**Deletion is the only irreversible action this skill takes.** Every other category relocates its
content — to a docs file, to \`CHANGELOG.md\`, to \`docs/backlog/\` — and relocation is recoverable by
reading the new file. Only \`duplicate-of-chunk\` deletes, and it is safe solely because the content
still exists in the chunk. If a span does not fit a category, relocate it rather than delete it, and
say where it went.

### Extraction target selection

When a span is classified for extraction, choose a target file:

1. **\`architectural-detail\`** → \`docs/architecture/<slugified-heading>.md\`. If \`docs/architecture/\`
   does not exist but \`docs/\` does, create it. If \`docs/\` does not exist, use
   \`docs/<slugified-heading>.md\`.
2. **\`template-material\`** → \`docs/templates/<slugified-heading>.md\`. Same directory creation rules.
3. **\`release-note\`** → append to \`CHANGELOG.md\` if it exists, otherwise \`docs/changelog.md\`.
4. **\`project-context\`** (beyond the minimum) → \`docs/<slugified-heading>.md\`, or merge into
   \`README.md\` if the content is clearly README material.

Slugify: lowercase, replace spaces with hyphens, remove special characters. E.g., "Important
Implementation Details" → \`important-implementation-details.md\`.

If the target file already exists, append the extracted content under a new \`## <original heading>\`
at the end of that file.

---

## Step 5 — Compact what is retained

\`Keep\` means **preserve the semantics, not the wording**. A retained rule may be shortened,
normalized, merged with an equivalent local rule, or moved next to a related rule — provided its
scope, modality, conditions, exceptions and exact literals survive intact.

### Policy

1. Keep every unique prescriptive rule.
2. Keep its normative strength.
3. Keep scope, conditions, exceptions and negations.
4. Keep exact literals verbatim — the list in Step 3.
5. Drop rationale that does not change how the rule is interpreted.
6. Reduce rationale to one short clause when it is what removes an ambiguity.
7. Drop examples that only restate a rule that is already unambiguous.
8. Keep a minimal example when it is the actual syntax or behavior contract.
9. Merge only semantically equivalent statements.
10. Never merge statements because they use similar words.

A safe compaction:

\`\`\`text
Before:
It is very important that developers never use process.env directly throughout the
application. Instead, all environment variables should always be accessed through our
env module so that validation and parsing remain centralized.

After:
- Never read \`process.env\` outside the central env module.
\`\`\`

The obligation (\`never\`), the literal (\`process.env\`) and the scope (outside the env module) all
survive. The rationale is dropped because knowing _why_ does not change what the reader does.

### Order of optimization

Always in this order — each step shrinks the input to the next:

1. Remove what the active chunk already guarantees.
2. Remove internal semantic duplicates.
3. Extract non-prescriptive documentation.
4. Remove redundant rationale.
5. Remove redundant examples.
6. Compact the wording of retained rules.
7. Group retained rules that belong together.
8. Only then consider formatting and line count.

### Never optimize by

- Removing project-specific behavior, scope, conditions, exceptions or negations.
- Changing \`MUST\` / \`SHOULD\` / \`PREFER\` / \`NEVER\`.
- Changing an exact command, path, flag or identifier.
- Guessing between two conflicting variants.

### Pitfalls are protected, not frozen

\`Keep pitfall\` does not mean "keep every sentence verbatim". A pitfall compacts well into:

\`\`\`text
trigger/context → failure mode → required action
\`\`\`

A long history of how a bug was discovered can become:

\`\`\`text
- Before closing the DB, stop the checkpoint worker; otherwise shutdown races the WAL checkpoint.
\`\`\`

provided the history does not change what the reader does. \`<!-- hits: N -->\` markers are project
state and are carried across exactly.

### Wholesale restructuring is out of scope

Grouping related rules under one heading is allowed — that is step 7 of the order above.
Reorganizing the file's section structure wholesale is not: it buries the real changes in a diff the
user cannot review, and it recovers no tokens. Keep section order stable unless a section becomes
empty.

---

## Step 6 — Coverage audit

Run this **before writing anything**. It is the main defense against losing a rare but critical
instruction.

Every atomic prescriptive statement in the original must map to exactly one disposition:

\`\`\`text
Original atomic rule
  → retained (possibly reworded)
  → normalized into rule X
  → merged into equivalent rule X
  → guaranteed by chunk rule X
  → preserved as a project-specific exception
  → relocated to <file>
  → reported as a conflict
\`\`\`

There is no valid disposition "disappeared".

Then check literals: every exact literal recorded in Step 3 must appear verbatim in the result, in
the file it was relocated to, or in a reported conflict.

**If either check fails, abort before touching any file** and report which statement or literal has
no disposition. An incomplete audit is a bug in the analysis, not a reason to proceed carefully.

---

## Step 7 — Propose

Build a report and present it to the user. Do not apply yet.

Structure the report exactly like this:

\`\`\`text
## Cleanup plan for AGENTS.md

Active chunk: \`.datamitsu/ai/agents/agents-XXX.md\`
Project AGENTS.md: <M> sections, <R> prescriptive rules, <K> lines

### To delete (guaranteed by the chunk)

1. **"<heading>"** (lines a-b) — <N> spans
   Covered by: chunk § "<chunk section>"
   Why: <one-line semantic summary of the overlap>

### To merge (internal duplicates)

2. **"<heading>"** (lines a-b) + **"<heading>"** (lines c-d)
   Canonical location: <where the merged rule lands>
   Conditions preserved: <the distinct conditions that survive the merge>

### To compact

3. **"<heading>"** (lines a-b) → ~<n> lines
   Dropping: <rationale / examples being removed>
   Preserved: <modality, literals, conditions, exceptions>

### To extract (non-rule content → separate files)

4. **"<heading>"** (lines a-b) — <category>
   Target: \`<target file path>\`
   Why: <one-line reason>

### To move to the backlog (deferred work)

5. **"<heading>"** (lines a-b)
   Target: \`docs/backlog/<slug>.md\` — \`worth: <yes|later|no>\`
   Why: <one-line reason it is deferred work rather than a pitfall>

### To clean up (migration cruft)

6. **"<heading>"** (lines a-b)
   Action: <what will be stripped/promoted>
   Why: <one-line reason>

### To keep (project-unique rules, exceptions and pitfalls)

7. "<heading>" (lines a-b) — <category>

### Potential conflicts (no change made — your call)

8. **<short label>**
   A: \`<variant A>\` (line a) — <where it appears>
   B: \`<variant B>\` (line b) — <where it appears>
   Differs in: <literal | scope | condition | exception | negation | normative strength>
   Both kept. <one line on why they cannot be proven equivalent>

---

Summary

Semantic rules before:        <R>
Semantic rules after:         <R'>
Unique rules removed:         0
Chunk duplicates removed:     <N>
Internal duplicates merged:   <N>
Rationale/examples dropped:   <N> spans
Conflicts needing a decision: <N>

Files to create/update:
- \`<target file 1>\` (new) — <N> lines
- \`<target file 2>\` (append) — <N> lines

Line count (secondary): <K> → ~<K_after>

Apply changes? Reply: yes / no / show diff
\`\`\`

**\`Unique rules removed\` must be 0.** If it is not, the analysis is wrong — do not offer to apply.
Go back to Step 6, find the statement with no disposition, and fix the classification.

If the user replies \`show diff\`, print the unified diff between the current \`AGENTS.md\` and the
planned result, plus the content of each file to be created. Then ask again.

If the user replies \`no\`, abort. Do not modify anything.

If the user replies \`yes\`, proceed to Step 8.

---

## Step 8 — Apply

After explicit \`yes\`:

1. **Create extraction target files first.** For each extracted span:
   - Create parent directories if needed.
   - If the target file is new, write a \`# <heading>\` title and the extracted content.
   - If the target file exists, append \`\n\n## <heading>\n\n\` + content at the end.
2. **Write backlog entries.** For each \`deferred-work\` item, create \`docs/backlog/\` if absent and
   write one file per item in the format the \`backlog\` skill defines — slug naming the symptom,
   \`worth\`/\`where\`/\`added\` frontmatter, \`added\` set to today. Carry the original wording across;
   this is a move, not a summary. Apply the privacy rules: an item quoting a private path or another
   project is anonymized on the way over.
3. **Clean up migration cruft.** Strip wrapper headings and boilerplate, promote child sections.
4. **Apply deletes, merges and compactions** in order from **bottom to top** of \`AGENTS.md\` (so line
   numbers don't shift mid-edit).
5. **Remove extracted and relocated spans** from \`AGENTS.md\` (also bottom to top).
6. Preserve everything not touched: the override block, the bootstrap line, the \`# AGENTS.md\`
   heading, all \`potential-conflict\` spans, and section ordering elsewhere.
7. Write the result back to \`AGENTS.md\`.
8. **Verify after writing.** Re-read the written file and confirm every literal recorded in Step 3
   is present in it or in a file it moved to. If one is missing, say so immediately and loudly —
   the user still has the pre-run state in git.

Do not create backup files. Git is the backup. The user committed before running this — if they
didn't, that's user error and aborting too late won't help.

---

## Step 9 — Report

After writing, print a final summary:

\`\`\`text
Done.

Semantic rules: <R> → <R'> (0 unique rules lost)
AGENTS.md: <K_before> → <K_after> lines (-<delta>%)

- Deleted: <N> spans (chunk duplicates)
- Merged: <N> internal duplicates
- Compacted: <N> spans (rationale/examples dropped)
- Extracted: <N> spans → <N> files
- Moved to backlog: <N> items → \`docs/backlog/\`
- Cleaned up: <N> sections (migration cruft)

Files created/updated:
- \`<path>\` — <N> lines (new)
- \`<path>\` — <N> lines (appended)

Conflicts left for you (<N>):
- <short label>: \`<variant A>\` vs \`<variant B>\` — both kept, differs in <dimension>

[If a real CLAUDE.md was found:]

Note: project root contains a real CLAUDE.md file (not a symlink). Modern agents (Claude Code,
Codex CLI, OpenCode) all read AGENTS.md. Consider merging CLAUDE.md content into AGENTS.md and
deleting CLAUDE.md as a separate manual step.
\`\`\`

---

## What this skill does NOT do

- Does **not** modify anything in \`.datamitsu/\`. That directory is gitignored and regenerated by
  \`datamitsu\` itself. The chunks are read-only from this skill's perspective. Optimizing the shared
  chunks themselves is a different task with a different risk profile and is not this skill's job.
- Does **not** resolve conflicts on its own. Two plausible variants of a command are reported, never
  silently reconciled.
- Does **not** summarize. It normalizes under the invariants above — a summarizer is allowed to lose
  detail, and this is not.
- Does **not** touch symlinks like \`CLAUDE.md\`, \`GEMINI.md\`, \`.cursorrules\`, \`.windsurfrules\`. They
  reflect \`AGENTS.md\` automatically.
- Does **not** add tracking markers, version numbers, or state files. The chunks are the source of
  truth on every run; if a chunk grows, the next run picks it up.
- Does **not** validate the contents of the override block. The author wrote it; the skill respects
  it.
- Does **not** modify \`README.md\` or \`CHANGELOG.md\` unless extracting content there (append only,
  never rewrites existing content).

---

## Edge cases

**No \`AGENTS.md\` in project root.** Abort with message: "No AGENTS.md found in project root."

**Multiple bootstrap lines.** Use the first one. Warn that subsequent ones are ignored — this is
malformed input.

**Bootstrap line points to a file outside \`.datamitsu/\`.** Abort. This skill is only for
datamitsu-managed projects.

**Active chunk file does not exist on disk** (\`.datamitsu/\` was deleted or never generated). Abort:
"Active chunk file \`.datamitsu/ai/agents/agents-XXX.md\` not found. Run \`pnpm dm\` (or your
equivalent) to regenerate \`.datamitsu/\`, then re-run this skill."

**\`AGENTS.md\` is empty or has only the bootstrap line.** Nothing to clean. Print: "AGENTS.md has no
project content beyond the bootstrap. Nothing to do." Exit cleanly.

**Pitfall span without an explicit "Known Pitfalls" parent heading.** If individual spans describe
specific bugs/footguns scattered through the file, still classify them as \`pitfall\` based on
content. Pitfalls are content-defined, not structurally-defined.

**A span matches a chunk rule but adds a project-specific exception.** The rule half is
\`duplicate-of-chunk\`; the exception half is \`project-exception\`. Delete the first, keep the second.

**Two spans conflict and one is obviously stale** (e.g. it names a script that no longer exists in
\`package.json\`). Still report it as a conflict — but say which one the repository supports, and why.
The evidence goes in the report; the decision stays with the user.

**Extraction target directory does not exist.** Create it. The skill creates \`docs/architecture/\`,
\`docs/templates/\`, etc. as needed.

**Extraction target file already exists.** Append to it — never overwrite. Add a blank line
separator and a \`## <heading>\` before the appended content.

**Nothing to delete, extract or merge, but rules are verbose.** That is still a valid run: propose
compaction only. Print the plan with an empty delete section.

**All spans are project-unique rules and pitfalls, already tight.** Print: "AGENTS.md is already
clean — all content is project-specific rules or pitfalls, and no span compacts without losing
meaning. Nothing to do." Exit cleanly.

---

## Interaction style

- Be terse. Reports are scannable, not narrative.
- Quote line numbers from the current \`AGENTS.md\` exactly.
- Quote chunk section names exactly as they appear in the chunk.
- One-line "why" justifications. Do not explain the obvious.
- Never apologize for findings. The duplicates are facts, not the author's failure.
- Report conflicts flatly, without recommending a winner unless the repository itself provides the
  evidence.`;

const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CLAUDE = `---
name: cleanup-agents-md
description: Cleanup and compact the project AGENTS.md — remove duplicates of the shared datamitsu chunks and of other rules in the same file, extract non-rule content (architecture docs, templates, release notes) to separate files, strip migration cruft, move deferred work to docs/backlog/, and shrink the rules that remain without losing a single rule, condition, exception, obligation or exact command. Use this skill whenever the user asks to compress, clean up, deduplicate, slim down, sync, compact, or reduce the token cost of AGENTS.md against the datamitsu config — even if they describe it informally as "AGENTS.md got too big", "remove duplicates from AGENTS.md", "fix my agents file", or "extract architecture from AGENTS.md".
---

# Cleanup AGENTS.md

Read \`.datamitsu/ai/skills/cleanup-agents-md/instructions.md\` from the project root and follow it precisely.

The instructions file is the source of truth for this skill — it is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current chunks.`;

const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CODEX = `# /cleanup-agents-md

Cleanup and compact the project AGENTS.md — remove duplicates of the shared datamitsu chunks and of other rules in the same file, extract non-rule content (architecture docs, templates, release notes) to separate files, strip migration cruft, move deferred work to \`docs/backlog/\`, and shrink the rules that remain without losing a single rule, condition, exception, obligation or exact command.

Read \`.datamitsu/ai/skills/cleanup-agents-md/instructions.md\` from the project root and follow it precisely.

The instructions file is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current chunks.`;

// ── Skill: scaffold-stack ──────────────────────────────────────────────────

const SKILL_SCAFFOLD_STACK_INSTRUCTIONS = `# Scaffold Preferred Stack

You are about to scaffold a new project/app/library — or add a major dependency to an existing one — using the preferred stack for this ecosystem.

The **source of truth** for library choices is the \`## Preferred Stack\` section of the agent rules already loaded in this session (from \`.datamitsu/ai/agents/*.md\`, referenced by the project's \`AGENTS.md\`). Do NOT hardcode the catalogue into this skill or reconstruct it from memory — read it from the loaded rules every run so it stays current as the catalogue evolves. The \`## Single Source for Constants, Env & Build Inputs\` rules apply to everything you scaffold.

This skill installs dependencies and writes files. Always follow the propose → confirm → apply order. Never install or write without explicit confirmation.

---

## Step 1 — Read the source of truth

1. Locate the \`## Preferred Stack\` section in the loaded agent rules. If it is not present, abort:
   > Preferred Stack rules not found in the loaded agent rules. Ensure \`AGENTS.md\` references \`.datamitsu/ai/agents/*.md\` and run \`pnpm dm init\` to regenerate \`.datamitsu/\`, then re-run this skill.
2. Note the picks relevant to what you are about to build (Web / Node / Go / Testing / Docs / Monorepo), the Version Policy, the Invocation rule, and the bans (e.g. Tailwind is forbidden).

Do **not** hardcode the catalogue. If it gains or drops a library, this skill must pick that up automatically by re-reading the loaded rules.

---

## Step 2 — Understand the request and detect context

Determine WHAT is being scaffolded and WHERE:

- **Target kind:** Go service, Node service, Vite + React web app, shared library, monorepo root, or docs (Typst / Slidev). Ask the user if genuinely ambiguous.
- **Invocation mode:** is there a pnpm stack wired with this config (a \`package.json\` exposing the \`dm\`/\`datamitsu\` bin, a \`pnpm-workspace.yaml\`, or an existing \`.datamitsu/\`)?
  - Yes → drive managed tools via \`pnpm dm exec <tool>\`.
  - No → drive the system-installed \`datamitsu\` binary directly, or offer to initialize a pnpm stack first if the target belongs in one.
- **Monorepo:** if inside (or creating) a Turborepo + pnpm workspace, every package — including Go and Rust — needs a \`package.json\` with standard script names so \`turbo run <script>\` can orchestrate it. Confirm placement.

---

## Step 3 — Resolve versions

For every library you intend to add, apply the Version Policy:

1. If it is already used elsewhere in the repo, reuse that exact version.
2. Otherwise, check the CURRENT latest stable release from the registry (npm, the Go module proxy, crates.io) — do not guess a major from memory. Record the resolved version.
3. Never introduce an unmaintained/EOL package or a stale major. If a catalogue pick looks abandoned at scaffold time, stop and flag it to the user rather than silently substituting.

---

## Step 4 — Propose

Present a plan and do not write yet. Structure it:

\`\`\`
## scaffold plan

Building: <e.g. "Vite + React + TS web app inside the existing pnpm monorepo">
Invocation: <pnpm dm exec | direct datamitsu>

Libraries (catalogue → resolved version):
- <lib> — <version> (<reused from repo | latest stable>)
- …

Structure:
- <files/dirs to create, package.json wrapper, standard scripts, Taskfile tasks, turbo wiring>

Config inputs (per the Single Source rule):
- <env module / constants module / build-flag module to create, if any>

Commands to run:
- <exact install/scaffold commands>

Apply? Reply: yes / no / show details
\`\`\`

- \`no\` → abort, write nothing.
- \`show details\` → print full file contents / exact commands, then ask again.
- \`yes\` → Step 5.

---

## Step 5 — Apply

After explicit \`yes\`:

1. Run the scaffold/install commands exactly as proposed.
2. Create the \`package.json\` wrapper with standard script names; move any multi-step build logic into a \`Taskfile.yml\` invoked via \`pnpm dm exec task -- <task>\`.
3. Set up the single env / constants / build-flag entry points per the Single Source rules — do not scatter \`process.env\` / \`os.Getenv\` / raw constants.
4. Do not create backup files. Git is the backup.

---

## Step 6 — Report

\`\`\`
Done.

Scaffolded: <what>
Libraries: <lib@version, …>
Invocation: <mode>

Next steps:
- Run \`pnpm dm check\` (or \`datamitsu check\`) to fix + lint.
- <if monorepo:> add the new package to the workspace / turbo pipeline if needed.
- <if a runtime like Go/Rust is required:> ensure the toolchain is installed.
\`\`\`

---

## What this skill does NOT do

- Does NOT pick libraries outside the loaded Preferred Stack catalogue without telling the user. If a needed capability is not covered, surface it and ask.
- Does NOT introduce Tailwind or anything built on it — it is banned.
- Does NOT bump or change versions of libraries already pinned in the repo.
- Does NOT run \`dm setup\` or mutate managed configs beyond what is proposed.

---

## Edge cases

- **Capability not in the catalogue.** Do not guess a trendy package. Propose the closest ecosystem fit, mark it "not in catalogue", and ask the user to confirm or add it to \`datamitsu-config\`.
- **Existing project already uses a non-preferred library** for the same concern. Keep it (the catalogue is a priority list, not a forced migration). Note the divergence in the report; migrate only if the user asks.
- **No pnpm stack and the target does not need one** (e.g. a standalone Go binary). Use the direct \`datamitsu\` binary; do not force a pnpm workspace onto it.
- **Ambiguous target kind.** Ask; do not scaffold on a guess.

---

## Interaction style

- Be terse. The plan is scannable, not narrative.
- Cite the catalogue pick you are applying; one-line justifications.
- Report resolved versions as facts; never invent a version you did not verify.`;

const SKILL_SCAFFOLD_STACK_ADAPTER_CLAUDE = `---
name: scaffold-stack
description: Scaffold or extend a project using the preferred stack — pick libraries from the Preferred Stack catalogue, resolve the correct versions (match the repo, else latest stable), and wire the pnpm-workspace / Turborepo / Taskfile conventions. Detects what is being built (Go service, Node service, Vite+React web app, monorepo, Typst/Slidev docs) and whether a pnpm stack is present (choosing \`pnpm dm exec\` vs a direct \`datamitsu\` call). Use whenever the user asks to create, init, scaffold, bootstrap, or set up a new app/service/library/monorepo, or to add a major library to an existing one — even phrased informally as "start a React app", "new Go service", "set up a monorepo", "add a database layer".
---

# Scaffold Preferred Stack

Read \`.datamitsu/ai/skills/scaffold-stack/instructions.md\` from the project root and follow it precisely.

The instructions file is the source of truth for this skill — it is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it always reflects the current Preferred Stack rules.`;

const SKILL_SCAFFOLD_STACK_ADAPTER_CODEX = `# /scaffold-stack

Scaffold or extend a project using the preferred stack: pick libraries from the Preferred Stack catalogue, resolve the right versions (match the repo, else latest stable), and wire the pnpm-workspace / Turborepo / Taskfile conventions.

Read \`.datamitsu/ai/skills/scaffold-stack/instructions.md\` from the project root and follow it precisely.

The instructions file is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it always reflects the current Preferred Stack rules.`;

// ── Skill: setup-tsconfig ──────────────────────────────────────────────────

const SKILL_SETUP_TSCONFIG_INSTRUCTIONS = `# Setup TypeScript Config

You are about to configure or fix \`tsconfig.json\` in this project so that it extends the correct preset from \`@shibanet0/datamitsu-config/tsconfig/*\` according to the rules in \`.datamitsu/tsconfig.md\`.

\`.datamitsu/tsconfig.md\` is the **source of truth** for which preset applies to which project type. It is regenerated from the central \`datamitsu-config\` repository and may be more current than these instructions — when in doubt, defer to its preset table and warnings.

This skill is destructive — it writes \`tsconfig.json\`. Always follow the propose → confirm → apply order. Never apply without explicit confirmation.

---

## Step 1 — Read the source of truth

1. Read \`.datamitsu/tsconfig.md\` from the project root.
2. If the file is missing, abort:
   > \`.datamitsu/tsconfig.md\` not found. Run \`pnpm dm init\` (or your equivalent) to regenerate \`.datamitsu/\`, then re-run this skill.
3. Parse the "Quick Selection" table — it maps project type + monorepo flag → preset filename.
4. Parse the "Configuration Descriptions" section — it lists what each preset adds on top of \`base.json\`.
5. Parse the "Common Mistakes" section — these are the negative checks you will apply in Step 3.

Do **not** hardcode the preset list from memory. Read it from the file every run. If \`.datamitsu/tsconfig.md\` adds a new preset or removes one, this skill must pick that up automatically.

---

## Step 2 — Inspect the project

Gather these signals (do all reads in parallel where possible):

**\`package.json\` (project root):**

- \`dependencies\` + \`devDependencies\` + \`peerDependencies\` — look for: \`next\`, \`react\`, \`react-dom\`, \`vite\`, \`express\`, \`fastify\`, \`hono\`, \`@nestjs/core\`, \`aws-lambda\`, \`@aws-sdk/*\`, \`@pulumi/pulumi\`, \`@pulumi/*\`, \`@cloudflare/workers-types\`, \`wrangler\`, \`vitest\`, \`playwright\`, \`@playwright/test\`, \`tsx\`, \`tsdown\`, \`tsup\`.
- \`bin\` field — CLI tool.
- \`main\` / \`module\` / \`exports\` / \`types\` fields — library that publishes artifacts.
- \`private: true\` + \`workspaces\` field — monorepo root.
- \`peerDependencies\` containing \`react\` (without it being in \`dependencies\`) — strong signal of a React library.

**Workspace detection (monorepo or not):**

- Walk up from the project to find the nearest of: \`pnpm-workspace.yaml\`, \`lerna.json\`, \`nx.json\`, \`turbo.json\`, or a parent \`package.json\` with a \`workspaces\` field.
- If found and the current \`package.json\` is one of the workspace members, this is a **package inside a monorepo**.
- The monorepo flag affects library presets: \`library.json\` → \`shared-library.json\`, \`react-library.json\` → \`shared-react-library.json\`.

**File markers (project root):**

- \`next.config.{js,mjs,ts,cjs}\` → Next.js app
- \`vite.config.{js,mjs,ts,cjs}\` → Vite-based app
- \`Pulumi.yaml\` / \`Pulumi.*.yaml\` at the root → Pulumi IaC project
- \`wrangler.toml\` / \`wrangler.jsonc\` → Cloudflare Workers service
- \`astro.config.*\` → Astro app (not in the table — flag, do not auto-pick a preset)
- \`playwright.config.*\` without app code under \`src/\` → E2E test project
- \`index.html\` at the root with a Vite config → SPA

**Existing \`tsconfig.json\`:**

- If present, read it. Capture the current \`extends\`, \`compilerOptions.types\`, \`compilerOptions.jsx\`, \`compilerOptions.noEmit\`, \`compilerOptions.composite\`, \`include\`, \`exclude\`.
- If \`extends\` already points to a \`@shibanet0/datamitsu-config/tsconfig/*.json\`, that is the current preset.
- If \`extends\` points to anything else (\`@tsconfig/*\`, a local file, nothing), note it — this is a candidate for replacement.

**Source code spot-check (only if needed to disambiguate):**

- If you cannot tell service vs library from \`package.json\` alone, grep for \`node:\` imports in \`src/\` — their presence + no React strongly suggests \`service.json\`.

Do **not** read more files than needed to make the call. The signals above are usually enough.

---

## Step 3 — Pick the preset

Apply the rules from \`.datamitsu/tsconfig.md\` to the signals you gathered. The canonical decision order:

1. **Pulumi / IaC** (\`Pulumi.yaml\`/\`Pulumi.*.yaml\` at the root, or \`@pulumi/*\` in deps) → \`infra-pulumi.json\`. This is a **standalone** preset (does not extend \`base.json\`) and is the **only** preset that permits non-erasable syntax — Pulumi compiles via its own ts-node runtime, so decorators/\`enum\` are legal here.
2. **Next.js** (any \`next.config.*\` or \`next\` in deps) → \`nextjs.json\`.
3. **React library** (peerDep on \`react\` + no app markers + has \`main\`/\`exports\`):
   - monorepo → \`shared-react-library.json\`
   - standalone → \`react-library.json\`
4. **React app** (dep on \`react\` + Vite/CRA markers, no \`peerDep\` on react) → \`base.json\`.
5. **Backend service** (server framework dep, or Lambda/serverless markers, or \`node:*\` imports without React):
   - Cloudflare Workers (\`wrangler.toml\`/\`wrangler.jsonc\`, or \`@cloudflare/workers-types\` in deps) → \`service-worker.json\`
   - otherwise (Node.js runtime) → \`service.json\`
6. **Node library** (publishes artifacts via \`exports\`/\`main\`/\`types\`, no React, no server framework):
   - monorepo → \`shared-library.json\`
   - standalone → \`library.json\`
7. **Node CLI** (\`bin\` field, no other strong signals):
   - if it imports \`node:*\` heavily → \`service.json\`
   - otherwise → \`base.json\`
8. **E2E tests** (only test code, no app source) → \`base.json\`.
9. **Cannot determine** → do not guess. Ask the user which category their project falls into and re-run the decision with that input.

### Apply the "Common Mistakes" checks

Before finalizing the preset, validate against the negative rules in \`.datamitsu/tsconfig.md\`:

- **DOM types in a Node project.** If picked preset is \`react-library.json\`/\`shared-react-library.json\` but no React deps exist, downgrade to \`library.json\`/\`shared-library.json\` and note the correction.
- **\`library.json\` in a monorepo.** If picked preset is \`library.json\` but the project is inside a monorepo, upgrade to \`shared-library.json\` (so project references work). Same for \`react-library.json\` → \`shared-react-library.json\`.
- **Missing \`types: ["node"]\`.** If the picked preset is \`base.json\` or one of the library presets, but the source imports \`node:*\` modules, add \`compilerOptions.types: ["node"]\` to the override block of \`tsconfig.json\`.
- **Node types in a Cloudflare Worker.** If the project has \`wrangler.*\` or \`@cloudflare/workers-types\` but was assigned \`service.json\` (Node types), switch to \`service-worker.json\`. \`@types/node\` globals (\`process\`, \`Buffer\`, etc.) don't exist on the Workers runtime.
- **TypeScript version.** If \`typescript\` in devDependencies is \`< 6.0.0\`, flag it — \`.datamitsu/tsconfig.md\` requires TS 6.0+. Do not bump it automatically; surface it in the report so the user can update intentionally.

### Compute the override block

The presets in \`@shibanet0/datamitsu-config/tsconfig/*\` are designed to be extended with minimal overrides. Default to just:

\`\`\`json
{
  "extends": "@shibanet0/datamitsu-config/tsconfig/<preset>.json"
}
\`\`\`

Only add \`compilerOptions\` overrides when one of these applies:

- \`types: ["node"]\` required (per the mistake check above).
- Project layout deviates from \`src/\` → \`dist/\` and needs explicit \`rootDir\`/\`outDir\`.
- \`include\`/\`exclude\` need to deviate from the preset defaults (e.g., include a generated \`.d.ts\` file).

Never add overrides that just restate the preset defaults. The "Explicit Configuration" philosophy lives **inside** the preset, not in each consumer.

---

## Step 4 — Propose

Build a report and present it to the user. Do not write yet.

Structure the report exactly like this:

\`\`\`
## tsconfig setup plan

Detected project type: <human-readable label, e.g. "React library inside a pnpm monorepo">
Signals:
- <signal 1, e.g. "package.json peerDependencies: react ^19">
- <signal 2, e.g. "parent pnpm-workspace.yaml at ../../pnpm-workspace.yaml">
- <signal 3, e.g. "no next.config.* or vite.config.* found">

Picked preset: \`@shibanet0/datamitsu-config/tsconfig/<preset>.json\`
Why: <one-sentence justification, citing the row in the table>

### Current tsconfig.json

<one of:>
- Does not exist — will create.
- Extends \`<current extends>\` — will switch to \`<picked preset>\`.
- Already extends \`<picked preset>\` — no \`extends\` change needed.

### Override block (compilerOptions etc.)

<show the exact JSON that will be written, or "none — preset defaults are sufficient">

### Warnings

<list any of these that apply; omit section if none:>
- TypeScript version is \`<x.y.z>\`, preset requires >= 6.0.0. Update with \`pnpm add -D typescript@latest\`.
- Source imports \`node:*\` but \`types: ["node"]\` was not previously set. Will add it.
- Existing \`tsconfig.json\` had \`<surprising option>\` that the preset does not include. Will be removed unless you object.

### Diff

<unified diff of current vs proposed tsconfig.json, or full file if creating new>

Apply changes? Reply: yes / no / show details
\`\`\`

If the user replies \`show details\`, print the full proposed file content and the relevant excerpt from \`.datamitsu/tsconfig.md\` for the chosen preset. Then ask again.

If the user replies \`no\`, abort. Do not write anything.

If the user replies \`yes\`, proceed to Step 5.

---

## Step 5 — Apply

After explicit \`yes\`:

1. Write the new \`tsconfig.json\` content.
2. Preserve any keys from the existing \`tsconfig.json\` that are clearly user intent and not preset duplication: \`references\`, \`files\`, custom \`include\` patterns (e.g., generated \`.d.ts\` paths), \`ts-node\`/\`tsx\`-specific sections.
3. Drop keys that the preset already sets to the same value — the philosophy is explicit-in-preset, minimal-in-consumer.
4. Sort \`compilerOptions\` keys alphabetically and root-level keys in this order: \`$schema\`, \`extends\`, \`compilerOptions\`, \`include\`, \`exclude\`, \`references\`, \`files\`. This matches the project's existing style (see the project's own \`tsconfig.json\`).
5. Do not create backup files. Git is the backup.

Do not touch any other tsconfig files in the repo (\`tsconfig.eslint.json\`, \`tsconfig.build.json\`, package-level configs in a monorepo) unless the user explicitly asked you to set those up too. Each is a separate run.

---

## Step 6 — Report

After writing, print a final summary:

\`\`\`
Done.

tsconfig.json: <created | updated>
Preset: \`@shibanet0/datamitsu-config/tsconfig/<preset>.json\`

Next steps:
- Run \`pnpm tsc --noEmit\` to verify the new config compiles.
- <if monorepo + shared-*:> Add a \`references\` entry from consumer packages to this package.
- <if TS version was flagged:> Update TypeScript: \`pnpm add -D typescript@latest\`.
\`\`\`

---

## What this skill does NOT do

- Does **not** install or update TypeScript itself. The version check is informational.
- Does **not** modify \`package.json\`, \`tsdown.config.*\`, bundler configs, ESLint configs, or any other file. tsconfig only.
- Does **not** set up project \`references\` in a monorepo. Reports the recommendation; the user wires the references because correct wiring requires knowing the dependency graph.
- Does **not** delete or modify alternate tsconfig files (\`tsconfig.build.json\`, etc.).
- Does **not** add path aliases. Per \`.datamitsu/tsconfig.md\`, the presets intentionally avoid path aliases — use relative paths.
- Does **not** modify anything under \`.datamitsu/\`. That directory is read-only from this skill's perspective.

---

## Edge cases

**No \`package.json\` in project root.** Abort: "No \`package.json\` found. This skill expects a Node/TypeScript project."

**Multiple \`tsconfig*.json\` files in root.** Operate only on \`tsconfig.json\`. If it does not exist but \`tsconfig.base.json\` does, surface it in the report and ask whether the user wants \`tsconfig.json\` created as a thin extender of the picked preset, or whether \`tsconfig.base.json\` should be modified instead.

**\`tsconfig.json\` is a JSON5 file with comments.** Preserve user comments where possible by treating the file as text rather than re-serializing. If overrides need to be added/removed, do minimal textual edits.

**Project already has the correct preset and no warnings apply.** Print: "tsconfig.json already extends the correct preset. Nothing to do." Exit cleanly.

**Project is inside a monorepo but the user wants standalone behavior** (e.g., the package is published independently from a turborepo). Surface the monorepo detection in the proposal and let the user override the preset choice when they reply.

**Mixed signals (React + server framework, e.g. Next.js API routes).** Next.js wins — use \`nextjs.json\`. The Next plugin handles both client and server.

**Astro / SvelteKit / SolidStart / other frameworks not in the table.** Do not pick a preset. Report the detected framework and ask the user to either pick manually from the table or open an issue against \`datamitsu-config\` to add a preset.

---

## Interaction style

- Be terse. Reports are scannable, not narrative.
- Quote the row of the "Quick Selection" table verbatim when justifying a preset choice.
- One-line "why" justifications. Do not restate what the preset adds — the user can read \`.datamitsu/tsconfig.md\`.
- Never apologize for warnings. They are facts, not the author's failure.`;

const SKILL_SETUP_TSCONFIG_ADAPTER_CLAUDE = `---
name: setup-tsconfig
description: Configure or fix the project's tsconfig.json to extend the correct preset from @shibanet0/datamitsu-config/tsconfig/* based on the rules in .datamitsu/tsconfig.md. Detects project type (Next.js app, React app, React library, Node library, backend service, CLI, E2E tests) and monorepo status, picks the matching preset (base/library/service/nextjs/react-library/shared-library/shared-react-library), and rewrites tsconfig.json with a minimal override block. Use this skill whenever the user asks to set up, configure, fix, switch, migrate, or pick a TypeScript config — even if they describe it informally as "what tsconfig should I use", "my tsconfig is wrong", "extend datamitsu tsconfig", "set up TS for this package".
---

# Setup TypeScript Config

Read \`.datamitsu/ai/skills/setup-tsconfig/instructions.md\` from the project root and follow it precisely.

The instructions file is the source of truth for this skill — it is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current presets and rules in \`.datamitsu/tsconfig.md\`.`;

const SKILL_SETUP_TSCONFIG_ADAPTER_CODEX = `# /setup-tsconfig

Configure or fix the project's \`tsconfig.json\` to extend the correct preset from \`@shibanet0/datamitsu-config/tsconfig/*\` based on the rules in \`.datamitsu/tsconfig.md\`.

Read \`.datamitsu/ai/skills/setup-tsconfig/instructions.md\` from the project root and follow it precisely.

The instructions file is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current presets and rules.`;

// ── Exports ─────────────────────────────────────────────────────────────────

export interface SkillDefinition {
  adapters: {
    claude: string;
    codex: string;
  };
  instructions: string;
  name: string;
}

export const SKILLS: SkillDefinition[] = [
  {
    adapters: {
      claude: SKILL_BACKLOG_ADAPTER_CLAUDE,
      codex: SKILL_BACKLOG_ADAPTER_CODEX,
    },
    instructions: SKILL_BACKLOG_INSTRUCTIONS,
    name: "backlog",
  },
  {
    adapters: {
      claude: SKILL_CLEANUP_AGENTS_MD_ADAPTER_CLAUDE,
      codex: SKILL_CLEANUP_AGENTS_MD_ADAPTER_CODEX,
    },
    instructions: SKILL_CLEANUP_AGENTS_MD_INSTRUCTIONS,
    name: "cleanup-agents-md",
  },
  {
    adapters: {
      claude: SKILL_SCAFFOLD_STACK_ADAPTER_CLAUDE,
      codex: SKILL_SCAFFOLD_STACK_ADAPTER_CODEX,
    },
    instructions: SKILL_SCAFFOLD_STACK_INSTRUCTIONS,
    name: "scaffold-stack",
  },
  {
    adapters: {
      claude: SKILL_SETUP_TSCONFIG_ADAPTER_CLAUDE,
      codex: SKILL_SETUP_TSCONFIG_ADAPTER_CODEX,
    },
    instructions: SKILL_SETUP_TSCONFIG_INSTRUCTIONS,
    name: "setup-tsconfig",
  },
];

// ── Removed skills (auto-cleanup on dm init) ────────────────────────────────

export const REMOVED_SKILLS: string[] = [];

// ── Hashes (sha256, computed at build time) ────────────────────────────────
export const SKILL_BACKLOG_INSTRUCTIONS_HASH = "58242e544744f1c611638ba10c38ef65c5efe70e60604b8ac11fa6766897db08"; // prettier-ignore
export const SKILL_BACKLOG_ADAPTER_CLAUDE_HASH = "1e13794a51fe1b104c87a556145626df9d71f513f8355c6ac2a85f4aadbc7391"; // prettier-ignore
export const SKILL_BACKLOG_ADAPTER_CODEX_HASH = "84ee9c13520e092e58b370bed9de566d96632870fc011c9f12b6a63c7e962ac0"; // prettier-ignore
export const SKILL_CLEANUP_AGENTS_MD_INSTRUCTIONS_HASH = "622d852ca069742cf6dd803d5744b008e6f9480c75c74b42c4884b06bfddf3ce"; // prettier-ignore
export const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CLAUDE_HASH = "ba21e41a641e6c6f01309fe6563e0c961a4acbd9b55c9eabadb2c8459d55dda2"; // prettier-ignore
export const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CODEX_HASH = "85dab71e883e003e2ee4a9d3f3728c30e0d4535c6062956b412e6e50a5287b9c"; // prettier-ignore
export const SKILL_SCAFFOLD_STACK_INSTRUCTIONS_HASH = "28a9581cf58b87bd81913b052637f4fd08b624c23f904acddb8492a31d224d1f"; // prettier-ignore
export const SKILL_SCAFFOLD_STACK_ADAPTER_CLAUDE_HASH = "eb18cf165f1f7e2a8910c8a50a6974e9b7c867e66cfa335675e05b03b2238236"; // prettier-ignore
export const SKILL_SCAFFOLD_STACK_ADAPTER_CODEX_HASH = "b0deeb09ffdc91f7ae267fecb849ca1dd9e530304502492601f6caa345ee22aa"; // prettier-ignore
export const SKILL_SETUP_TSCONFIG_INSTRUCTIONS_HASH = "749b019af80df9646f8d1f1491c091b93cf9a7f1dbf2966943aa31c76160eaf9"; // prettier-ignore
export const SKILL_SETUP_TSCONFIG_ADAPTER_CLAUDE_HASH = "923a388c3ec8d1ab8bb8859c2c4ed13ead607d253aec01a428d0df654bc23911"; // prettier-ignore
export const SKILL_SETUP_TSCONFIG_ADAPTER_CODEX_HASH = "b47e306d7f1804b6907cd262893d71b39ba82c13f7cdbb810fc695526f4a519c"; // prettier-ignore
