// prettier-ignore
/* eslint-disable */

// AUTO-GENERATED by scripts/gen-skills.ts — do not edit manually

// ── Skill: cleanup-agents-md ───────────────────────────────────────────────

const SKILL_CLEANUP_AGENTS_MD_INSTRUCTIONS = `# Cleanup AGENTS.md

You are about to clean up the project's \`AGENTS.md\` by removing sections that are already covered by the shared chunks deployed via [datamitsu](https://datamitsu.com/) into \`.datamitsu/ai/agents/agents-*.md\`, and by extracting non-rule content (architecture docs, templates, release notes) to separate files where it belongs.

The shared chunks are the **source of truth**. The project's \`AGENTS.md\` should contain only what is specific to this project and not covered by the chunks. Additionally, \`AGENTS.md\` is for **prescriptive rules** — descriptive documentation of internals belongs in dedicated docs files, not in agent instructions.

This skill is destructive — it rewrites \`AGENTS.md\` and may create new files. Always follow the propose → confirm → apply order. Never apply without explicit confirmation.

---

## Step 1 — Discovery

1. Read \`AGENTS.md\` from the project root.
2. Find the **bootstrap line** — a single bold paragraph starting with \`**Read [.datamitsu/\`.
3. Parse the path inside the link to identify the active chunk file. Expected values:
   - \`.datamitsu/ai/agents/agents-base.md\`
   - \`.datamitsu/ai/agents/agents-docs-markdown.md\`
   - \`.datamitsu/ai/agents/agents-docs-website.md\`
4. Read the referenced chunk file. Treat it as read-only — never modify anything in \`.datamitsu/\`.
5. If the bootstrap line is missing or points outside \`.datamitsu/\`, abort:
   > This project's \`AGENTS.md\` does not reference any datamitsu chunk. This skill only works with datamitsu-managed projects. Aborting.

If \`CLAUDE.md\` exists in the project root **as a real file** (not a symlink to \`AGENTS.md\`), note it and report at the end — do not auto-merge.

Survey the project structure to determine extraction targets:

- Does \`docs/\` exist? If so, note subdirectories (e.g., \`docs/architecture/\`, \`docs/guides/\`, \`docs/templates/\`).
- Does \`CHANGELOG.md\` exist?
- Note the project name and purpose from \`package.json\`, \`README.md\`, or similar.

---

## Step 2 — Parse the project AGENTS.md

Identify three regions in this exact order:

1. **Override block** — everything between the \`# AGENTS.md\` heading and the bootstrap line. May be empty. Project-specific overrides of chunk rules live here. **Never modify.**
2. **Bootstrap line** — the one bold paragraph that references the chunk. **Never modify.**
3. **Project content** — everything below the bootstrap line. Split into sections by \`##\` (h2) headings. Subsections (\`###\` and deeper) belong to their parent section.

---

## Step 3 — Classify each project section

For each \`##\` section in project content, assign exactly one category:

| Category               | Definition                                                                   | Action                               |
| ---------------------- | ---------------------------------------------------------------------------- | ------------------------------------ |
| \`duplicate-of-chunk\`   | Section is semantically covered by a rule in the active chunk                | Delete from AGENTS.md                |
| \`partial-duplicate\`    | Part is covered, part is unique to this project                              | Rewrite to keep only unique part     |
| \`project-unique-rule\`  | Prescriptive rule specific to this project, not in chunks                    | Keep                                 |
| \`pitfall\`              | Belongs to "Known Pitfalls" / "Известные проблемы" / similar                 | Keep                                 |
| \`architectural-detail\` | Long descriptive documentation of a subsystem (not a rule)                   | Extract to docs file                 |
| \`template-material\`    | Reusable template skeleton (e.g., installation tabs, annotation boilerplate) | Extract to docs file                 |
| \`release-note\`         | Description of a past migration or breaking change                           | Extract to docs or CHANGELOG         |
| \`migration-cruft\`      | Wrapper headings/boilerplate left from a CLAUDE.md→AGENTS.md migration       | Strip cruft, integrate content       |
| \`overview\`             | README-style content (mission, package list, repo tree, key deps)            | Keep if ≤20 lines; extract if larger |

### Classification rules

**Semantic, not textual.** Project sections often reword chunk rules in different words. Same intent and content = duplicate, regardless of wording.

**Prescriptive vs descriptive distinguishes rule from architecture.** A 60-line description of how the retry orchestrator works internally is \`architectural-detail\`. A 2-line statement "always call \`markRetryHealthyBoot\` after a successful boot, otherwise X" is \`project-unique-rule\`. Length is not the criterion — the question is "does this tell the agent what to do (rule)" or "does this describe how the system works (architecture)".

**Pitfall detection.** A section is a \`pitfall\` if any of these match:

- Heading contains: \`Pitfall\`, \`Known Pitfalls\`, \`Известные проблемы\`, \`Подводные камни\`, \`Gotcha\`, \`Common mistakes\`, \`Lessons learned\`
- It belongs to a parent section matching those patterns
- It describes a specific bug, race, footgun, or mistake to avoid in this codebase
- It contains \`<!-- hits: N -->\` markers — these are project state and must be preserved

**Migration cruft detection.** A section is \`migration-cruft\` if:

- Heading is "Migrated From CLAUDE.md", "From CLAUDE.md", or similar migration-provenance heading
- It contains only a child \`# CLAUDE.md\` heading and/or boilerplate like "This file provides guidance to Claude Code (claude.ai/code)..." with no prescriptive rules
- It wraps other sections that would otherwise be top-level — the wrapper itself is cruft, the wrapped content is classified independently

When stripping migration cruft: remove the wrapper heading and any boilerplate lines. Promote wrapped subsections one heading level up (e.g., \`###\` under \`## Migrated From CLAUDE.md\` becomes \`##\`). Preserve all prescriptive content inside.

**Misplaced overrides.** If a project section explicitly contradicts or extends a chunk rule (e.g., "in this fork, commits follow the upstream format, not Conventional Commits"), it is a legitimate override — but it should live in the override block above the bootstrap line, not below. Classify as \`project-unique-rule\` and add a note: "Consider moving to override block above bootstrap line".

**Be conservative.** When in doubt between \`duplicate-of-chunk\` and \`project-unique-rule\`, choose \`project-unique-rule\`. False positive (deleting useful project content) is worse than false negative (leaving a small duplicate).

### Extraction target selection

When a section is classified for extraction, choose a target file:

1. **\`architectural-detail\`** → \`docs/architecture/<slugified-heading>.md\`. If \`docs/architecture/\` does not exist but \`docs/\` does, create it. If \`docs/\` does not exist, use \`docs/<slugified-heading>.md\`.
2. **\`template-material\`** → \`docs/templates/<slugified-heading>.md\`. Same directory creation rules.
3. **\`release-note\`** → append to \`CHANGELOG.md\` if it exists, otherwise \`docs/changelog.md\`.
4. **\`overview\`** (>20 lines) → \`docs/<slugified-heading>.md\` or merge into \`README.md\` if the content is clearly README material.

Slugify: lowercase, replace spaces with hyphens, remove special characters. E.g., "Important Implementation Details" → \`important-implementation-details.md\`.

If the target file already exists, append the extracted content under a new \`## <original heading>\` at the end of that file.

---

## Step 4 — Propose

Build a report and present it to the user. Do not apply yet.

Structure the report exactly like this:

\`\`\`
## Cleanup plan for AGENTS.md

Active chunk: \`.datamitsu/ai/agents/agents-XXX.md\`
Project AGENTS.md: <M> sections, <K> lines

### To delete (covered by chunks)

1. **Section "<heading>"** (lines a-b)
   Covered by: chunk § "<chunk section>"
   Why: <one-line semantic summary of the overlap>

2. ...

### To rewrite (partial duplicates)

3. **Section "<heading>"** (lines a-b)
   Partially covered by: chunk § "<chunk section>"
   Keep: lines c-d (<one-line summary of the unique part>)
   Drop: lines e-f, g-h (<summary of duplicated parts>)

### To extract (non-rule content → separate files)

4. **Section "<heading>"** (lines a-b) — <category>
   Target: \`<target file path>\`
   Why: <one-line reason>

### To clean up (migration cruft)

5. **Section "<heading>"** (lines a-b)
   Action: <what will be stripped/promoted>
   Why: <one-line reason>

### To keep (project-unique rules and pitfalls)

6. Section "<heading>" (lines a-b) — <category>

---

Summary
- Will delete: <N> sections, ~<L1> lines
- Will rewrite: <N> sections, ~<L2> → ~<L3> lines
- Will extract: <N> sections, ~<L4> lines → <N> new/updated files
- Will clean up: <N> sections (migration cruft stripped)
- Will keep untouched: <N> sections (project-unique + pitfalls)

Files to create/update:
- \`<target file 1>\` (new) — <N> lines
- \`<target file 2>\` (append) — <N> lines
...

Total AGENTS.md: <K> → ~<K_after> lines

Apply changes? Reply: yes / no / show diff
\`\`\`

If the user replies \`show diff\`, print the unified diff between the current \`AGENTS.md\` and the planned result, plus the content of each file to be created. Then ask again.

If the user replies \`no\`, abort. Do not modify anything.

If the user replies \`yes\`, proceed to Step 5.

---

## Step 5 — Apply

After explicit \`yes\`:

1. **Create extraction target files first.** For each extracted section:
   - Create parent directories if needed.
   - If the target file is new, write a \`# <heading>\` title and the extracted content.
   - If the target file exists, append \`\n\n## <heading>\n\n\` + content at the end.
2. **Clean up migration cruft.** Strip wrapper headings and boilerplate, promote child sections.
3. **Apply deletes and rewrites** in order from **bottom to top** of \`AGENTS.md\` (so line numbers don't shift mid-edit).
4. **Remove extracted sections** from \`AGENTS.md\` (also bottom to top).
5. Preserve everything not touched: the override block, the bootstrap line, the \`# AGENTS.md\` heading, all kept sections, all whitespace and section ordering elsewhere.
6. Write the result back to \`AGENTS.md\`.

Do not create backup files. Git is the backup. The user committed before running this — if they didn't, that's user error and aborting too late won't help.

---

## Step 6 — Report

After writing, print a final summary:

\`\`\`
Done.

AGENTS.md: <K_before> → <K_after> lines (-<delta>%)
- Deleted: <N> sections (chunk duplicates)
- Rewritten: <N> sections (partial duplicates)
- Extracted: <N> sections → <N> files
- Cleaned up: <N> sections (migration cruft)

Files created/updated:
- \`<path>\` — <N> lines (new)
- \`<path>\` — <N> lines (appended)
...

[If a real CLAUDE.md was found:]

Note: project root contains a real CLAUDE.md file (not a symlink). Modern agents (Claude Code, Codex CLI, OpenCode) all read AGENTS.md. Consider merging CLAUDE.md content into AGENTS.md and deleting CLAUDE.md as a separate manual step.
\`\`\`

---

## What this skill does NOT do

- Does **not** modify anything in \`.datamitsu/\`. That directory is gitignored and regenerated by \`datamitsu\` itself. The chunks are read-only from this skill's perspective.
- Does **not** touch symlinks like \`CLAUDE.md\`, \`GEMINI.md\`, \`.cursorrules\`, \`.windsurfrules\`. They reflect \`AGENTS.md\` automatically.
- Does **not** add tracking markers, version numbers, or state files. The chunks are the source of truth on every run; if a chunk grows, the next run picks it up.
- Does **not** validate the contents of the override block. The author wrote it; the skill respects it.
- Does **not** modify \`README.md\` or \`CHANGELOG.md\` unless extracting content there (append only, never rewrites existing content).

---

## Edge cases

**No \`AGENTS.md\` in project root.** Abort with message: "No AGENTS.md found in project root."

**Multiple bootstrap lines.** Use the first one. Warn that subsequent ones are ignored — this is malformed input.

**Bootstrap line points to a file outside \`.datamitsu/\`.** Abort. This skill is only for datamitsu-managed projects.

**Active chunk file does not exist on disk** (\`.datamitsu/\` was deleted or never generated). Abort: "Active chunk file \`.datamitsu/ai/agents/agents-XXX.md\` not found. Run \`pnpm dm\` (or your equivalent) to regenerate \`.datamitsu/\`, then re-run this skill."

**\`AGENTS.md\` is empty or has only the bootstrap line.** Nothing to clean. Print: "AGENTS.md has no project content beyond the bootstrap. Nothing to do." Exit cleanly.

**Pitfall section without explicit "Known Pitfalls" parent heading.** If individual sections describe specific bugs/footguns scattered through the file (not under a "Known Pitfalls" parent), still classify them as \`pitfall\` based on content. Pitfalls are content-defined, not structurally-defined.

**Section in project content matches a chunk rule but adds a project-specific exception.** This is \`partial-duplicate\`. Rewrite to keep only the exception.

**Extraction target directory does not exist.** Create it. The skill creates \`docs/architecture/\`, \`docs/templates/\`, etc. as needed.

**Extraction target file already exists.** Append to it — never overwrite. Add a blank line separator and a \`## <heading>\` before the appended content.

**All sections are project-unique rules and pitfalls.** Nothing to delete, extract, or clean up. Print: "AGENTS.md is already clean — all content is project-specific rules or pitfalls. Nothing to do." Exit cleanly.

---

## Interaction style

- Be terse. Reports are scannable, not narrative.
- Quote line numbers from the current \`AGENTS.md\` exactly.
- Quote chunk section names exactly as they appear in the chunk.
- One-line "why" justifications. Do not explain the obvious.
- Never apologize for findings. The duplicates are facts, not the author's failure.`;

const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CLAUDE = `---
name: cleanup-agents-md
description: Cleanup the project AGENTS.md by removing chunk duplicates, extracting non-rule content (architecture docs, templates, release notes) to separate files, and stripping migration cruft. Use this skill whenever the user asks to compress, clean up, deduplicate, slim down, sync, or compact AGENTS.md against the datamitsu config — even if they describe it informally as "AGENTS.md got too big", "remove duplicates from AGENTS.md", "fix my agents file", or "extract architecture from AGENTS.md".
---

# Cleanup AGENTS.md

Read \`.datamitsu/ai/skills/cleanup-agents-md/instructions.md\` from the project root and follow it precisely.

The instructions file is the source of truth for this skill — it is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current chunks.`;

const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CODEX = `# /cleanup-agents-md

Cleanup the project AGENTS.md by removing chunk duplicates, extracting non-rule content (architecture docs, templates, release notes) to separate files, and stripping migration cruft.

Read \`.datamitsu/ai/skills/cleanup-agents-md/instructions.md\` from the project root and follow it precisely.

The instructions file is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current chunks.`;

// ── Skill: setup-tsconfig ──────────────────────────────────────────────────

const SKILL_SETUP_TSCONFIG_INSTRUCTIONS = `# Setup TypeScript Config

You are about to configure or fix \`tsconfig.json\` in this project so that it extends the correct preset from \`@shibanet0/datamitsu-config/tsconfig/*\` according to the rules in \`.datamitsu/tsconfig.md\`.

\`.datamitsu/tsconfig.md\` is the **source of truth** for which preset applies to which project type. It is regenerated from the central \`datamitsu-config\` repository and may be more current than these instructions — when in doubt, defer to its preset table and warnings.

This skill is destructive — it writes \`tsconfig.json\`. Always follow the propose → confirm → apply order. Never apply without explicit confirmation.

---

## Step 1 — Read the source of truth

1. Read \`.datamitsu/tsconfig.md\` from the project root.
2. If the file is missing, abort:
   > \`.datamitsu/tsconfig.md\` not found. Run \`pnpm dm init\` (or your equivalent) to regenerate \`.datamitsu/\`, then re-run this skill.
3. Parse the "Quick Selection" table — it maps project type + monorepo flag → preset filename.
4. Parse the "Configuration Descriptions" section — it lists what each preset adds on top of \`base.json\`.
5. Parse the "Common Mistakes" section — these are the negative checks you will apply in Step 3.

Do **not** hardcode the preset list from memory. Read it from the file every run. If \`.datamitsu/tsconfig.md\` adds a new preset or removes one, this skill must pick that up automatically.

---

## Step 2 — Inspect the project

Gather these signals (do all reads in parallel where possible):

**\`package.json\` (project root):**

- \`dependencies\` + \`devDependencies\` + \`peerDependencies\` — look for: \`next\`, \`react\`, \`react-dom\`, \`vite\`, \`express\`, \`fastify\`, \`hono\`, \`@nestjs/core\`, \`aws-lambda\`, \`@aws-sdk/*\`, \`@pulumi/pulumi\`, \`@pulumi/*\`, \`@cloudflare/workers-types\`, \`wrangler\`, \`vitest\`, \`playwright\`, \`@playwright/test\`, \`tsx\`, \`tsdown\`, \`tsup\`.
- \`bin\` field — CLI tool.
- \`main\` / \`module\` / \`exports\` / \`types\` fields — library that publishes artifacts.
- \`private: true\` + \`workspaces\` field — monorepo root.
- \`peerDependencies\` containing \`react\` (without it being in \`dependencies\`) — strong signal of a React library.

**Workspace detection (monorepo or not):**

- Walk up from the project to find the nearest of: \`pnpm-workspace.yaml\`, \`lerna.json\`, \`nx.json\`, \`turbo.json\`, or a parent \`package.json\` with a \`workspaces\` field.
- If found and the current \`package.json\` is one of the workspace members, this is a **package inside a monorepo**.
- The monorepo flag affects library presets: \`library.json\` → \`shared-library.json\`, \`react-library.json\` → \`shared-react-library.json\`.

**File markers (project root):**

- \`next.config.{js,mjs,ts,cjs}\` → Next.js app
- \`vite.config.{js,mjs,ts,cjs}\` → Vite-based app
- \`Pulumi.yaml\` / \`Pulumi.*.yaml\` at the root → Pulumi IaC project
- \`wrangler.toml\` / \`wrangler.jsonc\` → Cloudflare Workers service
- \`astro.config.*\` → Astro app (not in the table — flag, do not auto-pick a preset)
- \`playwright.config.*\` without app code under \`src/\` → E2E test project
- \`index.html\` at the root with a Vite config → SPA

**Existing \`tsconfig.json\`:**

- If present, read it. Capture the current \`extends\`, \`compilerOptions.types\`, \`compilerOptions.jsx\`, \`compilerOptions.noEmit\`, \`compilerOptions.composite\`, \`include\`, \`exclude\`.
- If \`extends\` already points to a \`@shibanet0/datamitsu-config/tsconfig/*.json\`, that is the current preset.
- If \`extends\` points to anything else (\`@tsconfig/*\`, a local file, nothing), note it — this is a candidate for replacement.

**Source code spot-check (only if needed to disambiguate):**

- If you cannot tell service vs library from \`package.json\` alone, grep for \`node:\` imports in \`src/\` — their presence + no React strongly suggests \`service.json\`.

Do **not** read more files than needed to make the call. The signals above are usually enough.

---

## Step 3 — Pick the preset

Apply the rules from \`.datamitsu/tsconfig.md\` to the signals you gathered. The canonical decision order:

1. **Pulumi / IaC** (\`Pulumi.yaml\`/\`Pulumi.*.yaml\` at the root, or \`@pulumi/*\` in deps) → \`infra-pulumi.json\`. This is a **standalone** preset (does not extend \`base.json\`) and is the **only** preset that permits non-erasable syntax — Pulumi compiles via its own ts-node runtime, so decorators/\`enum\` are legal here.
2. **Next.js** (any \`next.config.*\` or \`next\` in deps) → \`nextjs.json\`.
3. **React library** (peerDep on \`react\` + no app markers + has \`main\`/\`exports\`):
   - monorepo → \`shared-react-library.json\`
   - standalone → \`react-library.json\`
4. **React app** (dep on \`react\` + Vite/CRA markers, no \`peerDep\` on react) → \`base.json\`.
5. **Backend service** (server framework dep, or Lambda/serverless markers, or \`node:*\` imports without React):
   - Cloudflare Workers (\`wrangler.toml\`/\`wrangler.jsonc\`, or \`@cloudflare/workers-types\` in deps) → \`service-worker.json\`
   - otherwise (Node.js runtime) → \`service.json\`
6. **Node library** (publishes artifacts via \`exports\`/\`main\`/\`types\`, no React, no server framework):
   - monorepo → \`shared-library.json\`
   - standalone → \`library.json\`
7. **Node CLI** (\`bin\` field, no other strong signals):
   - if it imports \`node:*\` heavily → \`service.json\`
   - otherwise → \`base.json\`
8. **E2E tests** (only test code, no app source) → \`base.json\`.
9. **Cannot determine** → do not guess. Ask the user which category their project falls into and re-run the decision with that input.

### Apply the "Common Mistakes" checks

Before finalizing the preset, validate against the negative rules in \`.datamitsu/tsconfig.md\`:

- **DOM types in a Node project.** If picked preset is \`react-library.json\`/\`shared-react-library.json\` but no React deps exist, downgrade to \`library.json\`/\`shared-library.json\` and note the correction.
- **\`library.json\` in a monorepo.** If picked preset is \`library.json\` but the project is inside a monorepo, upgrade to \`shared-library.json\` (so project references work). Same for \`react-library.json\` → \`shared-react-library.json\`.
- **Missing \`types: ["node"]\`.** If the picked preset is \`base.json\` or one of the library presets, but the source imports \`node:*\` modules, add \`compilerOptions.types: ["node"]\` to the override block of \`tsconfig.json\`.
- **Node types in a Cloudflare Worker.** If the project has \`wrangler.*\` or \`@cloudflare/workers-types\` but was assigned \`service.json\` (Node types), switch to \`service-worker.json\`. \`@types/node\` globals (\`process\`, \`Buffer\`, etc.) don't exist on the Workers runtime.
- **TypeScript version.** If \`typescript\` in devDependencies is \`< 6.0.0\`, flag it — \`.datamitsu/tsconfig.md\` requires TS 6.0+. Do not bump it automatically; surface it in the report so the user can update intentionally.

### Compute the override block

The presets in \`@shibanet0/datamitsu-config/tsconfig/*\` are designed to be extended with minimal overrides. Default to just:

\`\`\`json
{
  "extends": "@shibanet0/datamitsu-config/tsconfig/<preset>.json"
}
\`\`\`

Only add \`compilerOptions\` overrides when one of these applies:

- \`types: ["node"]\` required (per the mistake check above).
- Project layout deviates from \`src/\` → \`dist/\` and needs explicit \`rootDir\`/\`outDir\`.
- \`include\`/\`exclude\` need to deviate from the preset defaults (e.g., include a generated \`.d.ts\` file).

Never add overrides that just restate the preset defaults. The "Explicit Configuration" philosophy lives **inside** the preset, not in each consumer.

---

## Step 4 — Propose

Build a report and present it to the user. Do not write yet.

Structure the report exactly like this:

\`\`\`
## tsconfig setup plan

Detected project type: <human-readable label, e.g. "React library inside a pnpm monorepo">
Signals:
- <signal 1, e.g. "package.json peerDependencies: react ^19">
- <signal 2, e.g. "parent pnpm-workspace.yaml at ../../pnpm-workspace.yaml">
- <signal 3, e.g. "no next.config.* or vite.config.* found">

Picked preset: \`@shibanet0/datamitsu-config/tsconfig/<preset>.json\`
Why: <one-sentence justification, citing the row in the table>

### Current tsconfig.json

<one of:>
- Does not exist — will create.
- Extends \`<current extends>\` — will switch to \`<picked preset>\`.
- Already extends \`<picked preset>\` — no \`extends\` change needed.

### Override block (compilerOptions etc.)

<show the exact JSON that will be written, or "none — preset defaults are sufficient">

### Warnings

<list any of these that apply; omit section if none:>
- TypeScript version is \`<x.y.z>\`, preset requires >= 6.0.0. Update with \`pnpm add -D typescript@latest\`.
- Source imports \`node:*\` but \`types: ["node"]\` was not previously set. Will add it.
- Existing \`tsconfig.json\` had \`<surprising option>\` that the preset does not include. Will be removed unless you object.

### Diff

<unified diff of current vs proposed tsconfig.json, or full file if creating new>

Apply changes? Reply: yes / no / show details
\`\`\`

If the user replies \`show details\`, print the full proposed file content and the relevant excerpt from \`.datamitsu/tsconfig.md\` for the chosen preset. Then ask again.

If the user replies \`no\`, abort. Do not write anything.

If the user replies \`yes\`, proceed to Step 5.

---

## Step 5 — Apply

After explicit \`yes\`:

1. Write the new \`tsconfig.json\` content.
2. Preserve any keys from the existing \`tsconfig.json\` that are clearly user intent and not preset duplication: \`references\`, \`files\`, custom \`include\` patterns (e.g., generated \`.d.ts\` paths), \`ts-node\`/\`tsx\`-specific sections.
3. Drop keys that the preset already sets to the same value — the philosophy is explicit-in-preset, minimal-in-consumer.
4. Sort \`compilerOptions\` keys alphabetically and root-level keys in this order: \`$schema\`, \`extends\`, \`compilerOptions\`, \`include\`, \`exclude\`, \`references\`, \`files\`. This matches the project's existing style (see the project's own \`tsconfig.json\`).
5. Do not create backup files. Git is the backup.

Do not touch any other tsconfig files in the repo (\`tsconfig.eslint.json\`, \`tsconfig.build.json\`, package-level configs in a monorepo) unless the user explicitly asked you to set those up too. Each is a separate run.

---

## Step 6 — Report

After writing, print a final summary:

\`\`\`
Done.

tsconfig.json: <created | updated>
Preset: \`@shibanet0/datamitsu-config/tsconfig/<preset>.json\`

Next steps:
- Run \`pnpm tsc --noEmit\` to verify the new config compiles.
- <if monorepo + shared-*:> Add a \`references\` entry from consumer packages to this package.
- <if TS version was flagged:> Update TypeScript: \`pnpm add -D typescript@latest\`.
\`\`\`

---

## What this skill does NOT do

- Does **not** install or update TypeScript itself. The version check is informational.
- Does **not** modify \`package.json\`, \`tsdown.config.*\`, bundler configs, ESLint configs, or any other file. tsconfig only.
- Does **not** set up project \`references\` in a monorepo. Reports the recommendation; the user wires the references because correct wiring requires knowing the dependency graph.
- Does **not** delete or modify alternate tsconfig files (\`tsconfig.build.json\`, etc.).
- Does **not** add path aliases. Per \`.datamitsu/tsconfig.md\`, the presets intentionally avoid path aliases — use relative paths.
- Does **not** modify anything under \`.datamitsu/\`. That directory is read-only from this skill's perspective.

---

## Edge cases

**No \`package.json\` in project root.** Abort: "No \`package.json\` found. This skill expects a Node/TypeScript project."

**Multiple \`tsconfig*.json\` files in root.** Operate only on \`tsconfig.json\`. If it does not exist but \`tsconfig.base.json\` does, surface it in the report and ask whether the user wants \`tsconfig.json\` created as a thin extender of the picked preset, or whether \`tsconfig.base.json\` should be modified instead.

**\`tsconfig.json\` is a JSON5 file with comments.** Preserve user comments where possible by treating the file as text rather than re-serializing. If overrides need to be added/removed, do minimal textual edits.

**Project already has the correct preset and no warnings apply.** Print: "tsconfig.json already extends the correct preset. Nothing to do." Exit cleanly.

**Project is inside a monorepo but the user wants standalone behavior** (e.g., the package is published independently from a turborepo). Surface the monorepo detection in the proposal and let the user override the preset choice when they reply.

**Mixed signals (React + server framework, e.g. Next.js API routes).** Next.js wins — use \`nextjs.json\`. The Next plugin handles both client and server.

**Astro / SvelteKit / SolidStart / other frameworks not in the table.** Do not pick a preset. Report the detected framework and ask the user to either pick manually from the table or open an issue against \`datamitsu-config\` to add a preset.

---

## Interaction style

- Be terse. Reports are scannable, not narrative.
- Quote the row of the "Quick Selection" table verbatim when justifying a preset choice.
- One-line "why" justifications. Do not restate what the preset adds — the user can read \`.datamitsu/tsconfig.md\`.
- Never apologize for warnings. They are facts, not the author's failure.`;

const SKILL_SETUP_TSCONFIG_ADAPTER_CLAUDE = `---
name: setup-tsconfig
description: Configure or fix the project's tsconfig.json to extend the correct preset from @shibanet0/datamitsu-config/tsconfig/* based on the rules in .datamitsu/tsconfig.md. Detects project type (Next.js app, React app, React library, Node library, backend service, CLI, E2E tests) and monorepo status, picks the matching preset (base/library/service/nextjs/react-library/shared-library/shared-react-library), and rewrites tsconfig.json with a minimal override block. Use this skill whenever the user asks to set up, configure, fix, switch, migrate, or pick a TypeScript config — even if they describe it informally as "what tsconfig should I use", "my tsconfig is wrong", "extend datamitsu tsconfig", "set up TS for this package".
---

# Setup TypeScript Config

Read \`.datamitsu/ai/skills/setup-tsconfig/instructions.md\` from the project root and follow it precisely.

The instructions file is the source of truth for this skill — it is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current presets and rules in \`.datamitsu/tsconfig.md\`.`;

const SKILL_SETUP_TSCONFIG_ADAPTER_CODEX = `# /setup-tsconfig

Configure or fix the project's \`tsconfig.json\` to extend the correct preset from \`@shibanet0/datamitsu-config/tsconfig/*\` based on the rules in \`.datamitsu/tsconfig.md\`.

Read \`.datamitsu/ai/skills/setup-tsconfig/instructions.md\` from the project root and follow it precisely.

The instructions file is regenerated automatically by \`datamitsu\` from the central \`datamitsu-config\` repository, so it is always up to date with the current presets and rules.`;

// ── Exports ─────────────────────────────────────────────────────────────────

export interface SkillDefinition {
  adapters: {
    claude: string;
    codex: string;
  };
  instructions: string;
  name: string;
}

export const SKILLS: SkillDefinition[] = [
  {
    adapters: {
      claude: SKILL_CLEANUP_AGENTS_MD_ADAPTER_CLAUDE,
      codex: SKILL_CLEANUP_AGENTS_MD_ADAPTER_CODEX,
    },
    instructions: SKILL_CLEANUP_AGENTS_MD_INSTRUCTIONS,
    name: "cleanup-agents-md",
  },
  {
    adapters: {
      claude: SKILL_SETUP_TSCONFIG_ADAPTER_CLAUDE,
      codex: SKILL_SETUP_TSCONFIG_ADAPTER_CODEX,
    },
    instructions: SKILL_SETUP_TSCONFIG_INSTRUCTIONS,
    name: "setup-tsconfig",
  },
];

// ── Removed skills (auto-cleanup on dm init) ────────────────────────────────

export const REMOVED_SKILLS: string[] = [];

// ── Hashes (sha256, computed at build time) ────────────────────────────────
export const SKILL_CLEANUP_AGENTS_MD_INSTRUCTIONS_HASH = "9fffca22fdb8a19166396dc675b13aece38d573bf2a1fd08573947cff644439d"; // prettier-ignore
export const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CLAUDE_HASH = "4c55061f8d18f4b5edf1b4478bec06da032694bccb627dc861a2dc31fd9cc167"; // prettier-ignore
export const SKILL_CLEANUP_AGENTS_MD_ADAPTER_CODEX_HASH = "c36f9ae1e4fa2d15f434c300dbe0995b8cb2a60fc5e632bb516f37488e68a300"; // prettier-ignore
export const SKILL_SETUP_TSCONFIG_INSTRUCTIONS_HASH = "749b019af80df9646f8d1f1491c091b93cf9a7f1dbf2966943aa31c76160eaf9"; // prettier-ignore
export const SKILL_SETUP_TSCONFIG_ADAPTER_CLAUDE_HASH = "923a388c3ec8d1ab8bb8859c2c4ed13ead607d253aec01a428d0df654bc23911"; // prettier-ignore
export const SKILL_SETUP_TSCONFIG_ADAPTER_CODEX_HASH = "b47e306d7f1804b6907cd262893d71b39ba82c13f7cdbb810fc695526f4a519c"; // prettier-ignore
