updates:
  - commit-message:
      include: scope
      prefix: chore
    directory: /docker
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - docker
    open-pull-requests-limit: 10
    package-ecosystem: docker
    schedule:
      interval: weekly
  - commit-message:
      prefix: ci
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - ci
    open-pull-requests-limit: 10
    package-ecosystem: github-actions
    schedule:
      interval: weekly
  - commit-message:
      include: scope
      prefix: chore
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: weekly
    versioning-strategy: auto
version: 2
