import fnmVersions from "../registries/fnmVersions.json";

export const eslintDeps = {
  "@antebudimir/eslint-plugin-vanilla-extract":
    fnmVersions["@antebudimir/eslint-plugin-vanilla-extract"].version,
  "@e18e/eslint-plugin": fnmVersions["@e18e/eslint-plugin"].version,
  "@eslint/config-helpers": fnmVersions["@eslint/config-helpers"].version,
  "@eslint/js": fnmVersions["@eslint/js"].version,
  "@next/eslint-plugin-next": fnmVersions["@next/eslint-plugin-next"].version,
  "@stylistic/eslint-plugin": fnmVersions["@stylistic/eslint-plugin"].version,
  "@vitest/eslint-plugin": fnmVersions["@vitest/eslint-plugin"].version,
  eslint: fnmVersions["eslint"].version,
  "eslint-config-prettier": fnmVersions["eslint-config-prettier"].version,
  "eslint-flat-config-utils": fnmVersions["eslint-flat-config-utils"].version,
  "eslint-import-resolver-typescript": fnmVersions["eslint-import-resolver-typescript"].version,
  "eslint-plugin-array-func": fnmVersions["eslint-plugin-array-func"].version,
  "eslint-plugin-arrow-return-style": fnmVersions["eslint-plugin-arrow-return-style"].version,
  "eslint-plugin-baseline-js": fnmVersions["eslint-plugin-baseline-js"].version,
  "eslint-plugin-boundaries": fnmVersions["eslint-plugin-boundaries"].version,
  "eslint-plugin-clsx": fnmVersions["eslint-plugin-clsx"].version,
  "eslint-plugin-command": fnmVersions["eslint-plugin-command"].version,
  "eslint-plugin-compat": fnmVersions["eslint-plugin-compat"].version,
  "eslint-plugin-de-morgan": fnmVersions["eslint-plugin-de-morgan"].version,
  "eslint-plugin-decorator-position": fnmVersions["eslint-plugin-decorator-position"].version,
  "eslint-plugin-depend": fnmVersions["eslint-plugin-depend"].version,
  "eslint-plugin-es-x": fnmVersions["eslint-plugin-es-x"].version,
  "eslint-plugin-escompat": fnmVersions["eslint-plugin-escompat"].version,
  "eslint-plugin-eslint-comments": fnmVersions["eslint-plugin-eslint-comments"].version,
  "eslint-plugin-filenames": fnmVersions["eslint-plugin-filenames"].version,
  "eslint-plugin-fsecond": fnmVersions["eslint-plugin-fsecond"].version,
  "eslint-plugin-functional": fnmVersions["eslint-plugin-functional"].version,
  "eslint-plugin-html": fnmVersions["eslint-plugin-html"].version,
  "eslint-plugin-i18next": fnmVersions["eslint-plugin-i18next"].version,
  "eslint-plugin-import": fnmVersions["eslint-plugin-import"].version,
  "eslint-plugin-jsdoc": fnmVersions["eslint-plugin-jsdoc"].version,
  "eslint-plugin-json": fnmVersions["eslint-plugin-json"].version,
  "eslint-plugin-json-schema-validator": fnmVersions["eslint-plugin-json-schema-validator"].version,
  "eslint-plugin-jsonc": fnmVersions["eslint-plugin-jsonc"].version,
  "eslint-plugin-jsx-a11y": fnmVersions["eslint-plugin-jsx-a11y"].version,
  "eslint-plugin-n": fnmVersions["eslint-plugin-n"].version,
  "eslint-plugin-no-unsanitized": fnmVersions["eslint-plugin-no-unsanitized"].version,
  "eslint-plugin-no-use-extend-native": fnmVersions["eslint-plugin-no-use-extend-native"].version,
  "eslint-plugin-oxlint": fnmVersions["eslint-plugin-oxlint"].version,
  "eslint-plugin-perfectionist": fnmVersions["eslint-plugin-perfectionist"].version,
  "eslint-plugin-playwright": fnmVersions["eslint-plugin-playwright"].version,
  "eslint-plugin-pnpm": fnmVersions["eslint-plugin-pnpm"].version,
  "eslint-plugin-promise": fnmVersions["eslint-plugin-promise"].version,
  "eslint-plugin-react": fnmVersions["eslint-plugin-react"].version,
  "eslint-plugin-react-hooks": fnmVersions["eslint-plugin-react-hooks"].version,
  "eslint-plugin-react-perf": fnmVersions["eslint-plugin-react-perf"].version,
  "eslint-plugin-react-prefer-function-component":
    fnmVersions["eslint-plugin-react-prefer-function-component"].version,
  "eslint-plugin-react-refresh": fnmVersions["eslint-plugin-react-refresh"].version,
  "eslint-plugin-react-you-might-not-need-an-effect":
    fnmVersions["eslint-plugin-react-you-might-not-need-an-effect"].version,
  "eslint-plugin-regexp": fnmVersions["eslint-plugin-regexp"].version,
  "eslint-plugin-security": fnmVersions["eslint-plugin-security"].version,
  "eslint-plugin-sonarjs": fnmVersions["eslint-plugin-sonarjs"].version,
  "eslint-plugin-storybook": fnmVersions["eslint-plugin-storybook"].version,
  "eslint-plugin-toml": fnmVersions["eslint-plugin-toml"].version,
  "eslint-plugin-turbo": fnmVersions["eslint-plugin-turbo"].version,
  "eslint-plugin-unicorn": fnmVersions["eslint-plugin-unicorn"].version,
  "eslint-plugin-unused-imports": fnmVersions["eslint-plugin-unused-imports"].version,
  "eslint-plugin-yml": fnmVersions["eslint-plugin-yml"].version,
  globals: fnmVersions["globals"].version,
  "typescript-eslint": fnmVersions["typescript-eslint"].version,
} as const;
