import nodeVersions from "../registries/nodeVersions.json";

export const eslintDeps = {
  "@antebudimir/eslint-plugin-vanilla-extract":
    nodeVersions["@antebudimir/eslint-plugin-vanilla-extract"].version,
  "@e18e/eslint-plugin": nodeVersions["@e18e/eslint-plugin"].version,
  "@eslint-community/eslint-plugin-eslint-comments":
    nodeVersions["@eslint-community/eslint-plugin-eslint-comments"].version,
  "@eslint-react/eslint-plugin": nodeVersions["@eslint-react/eslint-plugin"].version,
  "@eslint/config-helpers": nodeVersions["@eslint/config-helpers"].version,
  "@eslint/js": nodeVersions["@eslint/js"].version,
  "@next/eslint-plugin-next": nodeVersions["@next/eslint-plugin-next"].version,
  "@stylistic/eslint-plugin": nodeVersions["@stylistic/eslint-plugin"].version,
  "@vitest/eslint-plugin": nodeVersions["@vitest/eslint-plugin"].version,
  eslint: nodeVersions["eslint"].version,
  "eslint-config-prettier": nodeVersions["eslint-config-prettier"].version,
  "eslint-flat-config-utils": nodeVersions["eslint-flat-config-utils"].version,
  "eslint-import-resolver-typescript": nodeVersions["eslint-import-resolver-typescript"].version,
  "eslint-plugin-array-func": nodeVersions["eslint-plugin-array-func"].version,
  "eslint-plugin-arrow-return-style": nodeVersions["eslint-plugin-arrow-return-style"].version,
  "eslint-plugin-baseline-js": nodeVersions["eslint-plugin-baseline-js"].version,
  "eslint-plugin-boundaries": nodeVersions["eslint-plugin-boundaries"].version,
  "eslint-plugin-clsx": nodeVersions["eslint-plugin-clsx"].version,
  "eslint-plugin-command": nodeVersions["eslint-plugin-command"].version,
  "eslint-plugin-compat": nodeVersions["eslint-plugin-compat"].version,
  "eslint-plugin-de-morgan": nodeVersions["eslint-plugin-de-morgan"].version,
  "eslint-plugin-decorator-position": nodeVersions["eslint-plugin-decorator-position"].version,
  "eslint-plugin-depend": nodeVersions["eslint-plugin-depend"].version,
  "eslint-plugin-es-x": nodeVersions["eslint-plugin-es-x"].version,
  "eslint-plugin-escompat": nodeVersions["eslint-plugin-escompat"].version,
  "eslint-plugin-fsecond": nodeVersions["eslint-plugin-fsecond"].version,
  "eslint-plugin-functional": nodeVersions["eslint-plugin-functional"].version,
  "eslint-plugin-html": nodeVersions["eslint-plugin-html"].version,
  "eslint-plugin-i18next": nodeVersions["eslint-plugin-i18next"].version,
  "eslint-plugin-import-x": nodeVersions["eslint-plugin-import-x"].version,
  "eslint-plugin-jsdoc": nodeVersions["eslint-plugin-jsdoc"].version,
  "eslint-plugin-json": nodeVersions["eslint-plugin-json"].version,
  "eslint-plugin-json-schema-validator":
    nodeVersions["eslint-plugin-json-schema-validator"].version,
  "eslint-plugin-jsonc": nodeVersions["eslint-plugin-jsonc"].version,
  "eslint-plugin-jsx-a11y-x": nodeVersions["eslint-plugin-jsx-a11y-x"].version,
  "eslint-plugin-n": nodeVersions["eslint-plugin-n"].version,
  "eslint-plugin-no-unsanitized": nodeVersions["eslint-plugin-no-unsanitized"].version,
  "eslint-plugin-no-use-extend-native": nodeVersions["eslint-plugin-no-use-extend-native"].version,
  "eslint-plugin-oxlint": nodeVersions["eslint-plugin-oxlint"].version,
  "eslint-plugin-perfectionist": nodeVersions["eslint-plugin-perfectionist"].version,
  "eslint-plugin-playwright": nodeVersions["eslint-plugin-playwright"].version,
  "eslint-plugin-pnpm": nodeVersions["eslint-plugin-pnpm"].version,
  "eslint-plugin-promise": nodeVersions["eslint-plugin-promise"].version,
  "eslint-plugin-react-hooks": nodeVersions["eslint-plugin-react-hooks"].version,
  "eslint-plugin-react-prefer-function-component":
    nodeVersions["eslint-plugin-react-prefer-function-component"].version,
  "eslint-plugin-react-refresh": nodeVersions["eslint-plugin-react-refresh"].version,
  "eslint-plugin-react-you-might-not-need-an-effect":
    nodeVersions["eslint-plugin-react-you-might-not-need-an-effect"].version,
  "eslint-plugin-regexp": nodeVersions["eslint-plugin-regexp"].version,
  "eslint-plugin-security": nodeVersions["eslint-plugin-security"].version,
  "eslint-plugin-sonarjs": nodeVersions["eslint-plugin-sonarjs"].version,
  "eslint-plugin-storybook": nodeVersions["eslint-plugin-storybook"].version,
  "eslint-plugin-turbo": nodeVersions["eslint-plugin-turbo"].version,
  "eslint-plugin-unicorn": nodeVersions["eslint-plugin-unicorn"].version,
  "eslint-plugin-unused-imports": nodeVersions["eslint-plugin-unused-imports"].version,
  globals: nodeVersions["globals"].version,
  "typescript-eslint": nodeVersions["typescript-eslint"].version,
} as const;
