rules:
  no-build-and-image: 2
  no-duplicate-container-names: 2
  no-duplicate-exported-ports: 2
  no-quotes-in-volumes: 2
  no-unbound-port-interfaces: 2
  no-version-field: 2
  require-project-name-field: 2
  require-quotes-in-ports:
    - 2
    - quoteType: double
  service-container-name-regex: 2
  service-dependencies-alphabetical-order: 2
  service-image-require-explicit-tag:
    - 2
    - prohibitedTags:
        - latest
        - stable
        - edge
        - test
        - nightly
        - dev
        - beta
        - canary
        - lts
        - alpha
        - current
        - develop
        - development
        - experimental
        - main
        - master
        - next
        - preview
        - rc
        - snapshot
        - unstable
  service-keys-order: 2
  service-ports-alphabetical-order: 2
  services-alphabetical-order: 2
  top-level-properties-order: 2
