import { defineConfig } from "./.datamitsu/knip.config.js";

export default defineConfig((previous) => ({
  ...previous,
  ignoreBinaries: ["bin/datamitsu.js"],
  ignoreDependencies: [
    "@e18e/eslint-plugin",
    "@commitlint/cli",
    "syncpack",
    "type-fest",
    "yaml",
    "@octokit/rest",
    "publint",
    "sort-package-json",
    "eslint-config-prettier",
    "eslint-plugin-array-func",
    "eslint-plugin-import-x",
    "eslint-plugin-json",
    "eslint-plugin-json-schema-validator",
    "eslint-plugin-jsx-a11y-x",
    "eslint-plugin-n",
    "eslint-plugin-no-use-extend-native",
    "eslint-plugin-perfectionist",
    "eslint-plugin-playwright",
    "eslint-plugin-promise",
    "@eslint-react/eslint-plugin",
    "eslint-plugin-react-hooks",
    "prettier-plugin-embed",
    "prettier-plugin-jsdoc",
    "prettier-plugin-sql",
    "eslint-plugin-react-prefer-function-component",
    "eslint-plugin-react-refresh",
    "eslint-plugin-security",
    "eslint-plugin-sonarjs",
    "eslint-plugin-storybook",
    "eslint-plugin-turbo",
    "@prettier/plugin-xml",
    "eslint-plugin-unicorn",
    "eslint-plugin-unused-imports",
    "@antebudimir/eslint-plugin-vanilla-extract",
  ],
}));
