enableGlobalVirtualStore: true
enablePrePostScripts: false
hoistPattern: []
ignorePatchFailures: false
optimisticRepeatInstall: true
overrides:
  debug@4.4.3: npm:debug@3.2.7
resolutionMode: lowest-direct
verifyDepsBeforeRun: install
