import { describe, expect, it } from "vitest";

import { resolve } from "../profile";
import { lsLintProfile } from "../profiles/ls-lint";

describe("ls-lint profile", () => {
  it("skips dependency, build, cache, generated and tool directories", () => {
    expect(resolve(lsLintProfile)).toEqual([
      "**/node_modules",
      "**/vendor",
      "**/.yarn",
      "**/dist",
      "**/build",
      "**/out",
      "**/output",
      "**/.next",
      "**/.nuxt",
      "**/.svelte-kit",
      "**/.output",
      "**/public/build",
      "**/.vercel",
      "**/coverage",
      "**/.cover",
      "**/storybook-static",
      "**/playwright-report",
      "**/playwright-results",
      "**/playwright-report-html",
      "**/playwright-report-allure",
      "**/playwright-report-*",
      "**/test-results",
      "**/allure-report",
      "**/.nyc_output",
      "**/e2e/screenshots",
      "**/e2e/videos",
      "**/.datamitsu",
      "**/.turbo",
      "**/.cache",
      "**/.parcel-cache",
      "**/.temp",
      "**/.tmp",
      "**/temp",
      "**/tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.vite-inspect",
      "**/playwright/.cache",
      "**/.terraform",
      "**/.terragrunt-cache",
      "**/.pnpm-store",
      "**/generated",
      "**/ios",
      "**/android",
      "**/.venv",
      "**/venv",
      "**/.tox",
      "**/.ruff_cache",
      "**/.mypy_cache",
      "**/.pytest_cache",
      "**/*.egg-info",
      "**/.git",
      "**/.github",
      "**/.husky",
      "**/.changeset",
    ]);
  });
});
