import { describe, expect, it } from "vitest";

import { ignorePaths } from "../../apps/cspell/ignore";
import { jsonExcludeGlobs, yamlExcludeGlobs } from "../../datamitsu-config/globs";
import { filterIgnore, ignoreGroups } from "../../datamitsu-config/ignore";
import { trufflehogExcludePaths } from "../../datamitsu-config/managed-configs/_trufflehog_exclude_paths_txt";
import { yamlIgnore } from "../../datamitsu-config/managed-configs/shared";
import { GLOB_EXCLUDE, toOxlintIgnorePatterns } from "../../globs/globs";

describe("consumer ignore pins", () => {
  it("pins gitignore groups", () => {
    expect(ignoreGroups).toEqual({
      "Build outputs": [
        "**/.next/",
        "**/build/",
        "**/dist/",
        "**/out/",
        "**/.turbo/",
        "**/.vercel/",
        "**/.output/",
        "**/public/build/",
      ],
      "Cache & temporary files": [
        ".datamitsu/",
        "**/tsconfig.tsbuildinfo",
        "**/.eslintcache",
        "**/.prettiercache",
        "**/.stylelintcache",
        "**/*.tmp",
        "**/*.swp",
        "**/*.swo",
        "**/*~",
        "**/.cache/",
        "**/.parcel-cache/",
        "**/.temp/",
        "**/.tmp/",
      ],
      "Claude Code project files": [".claude/*", "!.claude/skills/"],
      "Codex CLI project files": [".codex/*", "!.codex/prompts/"],
      Dependencies: [
        "**/node_modules/",
        "**/.pnpm-store/",
        "**/vendor/",
        "**/.pnp.*",
        "**/.yarn/cache",
        "**/.yarn/unplugged",
        "**/.yarn/build-state.yml",
        "**/.yarn/install-state.gz",
      ],
      Environment: [
        ".env",
        ".env.local",
        ".env.*.local",
        ".env.development.local",
        ".env.test.local",
        ".env.production.local",
        "**/.env",
        "**/.env*.bak",
        "**/.env.local",
        "**/.env.*.local",
      ],
      "Golang specific": [
        "**/*.exe",
        "**/*.exe~",
        "**/*.dll",
        "**/*.so",
        "**/*.dylib",
        "**/*.test",
        "**/*.out",
        "**/go.work",
        "**/go.work.sum",
      ],
      "IDE & OS": [
        "**/.DS_Store",
        "**/Thumbs.db",
        "**/.idea/*",
        "**/.fleet/*",
        "**/.vscode/*",
        "!**/.vscode/launch.json",
        "!**/.vscode/settings.json",
        "!**/.vscode/extensions.json",
        "**/*.sublime-workspace",
        "**/*.iml",
        "**/.project",
        "**/.classpath",
        "**/.settings/*",
      ],
      Logs: [
        "**/.pnpm-debug.log*",
        "**/npm-debug.log*",
        "**/yarn-debug.log*",
        "**/yarn-error.log*",
        "**/lerna-debug.log*",
        "**/*.log",
      ],
      Other: ["**/*.gpg"],
      Pulumi: [
        "**/.pulumi/**/*.attrs",
        "**/.pulumi/locks/",
        "**/.pulumi/backups/",
        "**/.pulumi/history/",
        "**/.pulumi/**/*.bak",
        "**/.pulumi/**/*.json",
        "**/.pulumi/**/*.json.tmp",
        "**/.pulumi/**/*.yaml.tmp",
        "!**/.pulumi/**/*.enc.json",
        "!**/.pulumi/**/*.json.enc",
        "**/.pulumi/**/*.yaml",
        "!**/.pulumi/**/*.enc.yaml",
        "!**/.pulumi/**/*.yaml.enc",
        "**/.pulumi/**/*.yml",
        "!**/.pulumi/**/*.enc.yml",
        "!**/.pulumi/**/*.yml.enc",
      ],
      "ralphex progress logs": [
        ".ralphex/progress/",
        "**/progress.txt",
        "**/progress-*.txt",
        ".ralphex/worktrees/",
      ],
      "Security & Secrets": [
        "**/*.key",
        "**/*.pem",
        "**/*.p12",
        "**/*.pfx",
        "**/*.cer",
        "**/*.crt",
        "**/secrets.yml",
        "**/secrets.json",
      ],
      "Terraform & Terragrunt": [
        "**/.terraform/",
        "**/.terragrunt-cache/",
        "**/*.tfstate",
        "**/*.tfstate.backup",
        "**/crash.log",
        "**/override.tf",
        "**/override.tf.json",
        "**/*_override.tf",
        "**/*_override.tf.json",
      ],
      Testing: [
        "**/coverage/",
        "**/*.cov",
        "**/coverage.out",
        "**/.cover/",
        "**/storybook-static/",
        "**/playwright-report/",
        "**/playwright-results/",
        "**/playwright/.cache/",
        "**/test-results/",
        "**/allure-report/",
        "**/.nyc_output/",
        "**/e2e/screenshots/",
        "**/e2e/videos/",
      ],
    });
  });

  it("pins gitignore group order", () => {
    expect(Object.keys(ignoreGroups)).toEqual([
      "Build outputs",
      "Cache & temporary files",
      "Claude Code project files",
      "Codex CLI project files",
      "Dependencies",
      "Environment",
      "Golang specific",
      "IDE & OS",
      "Logs",
      "Other",
      "Pulumi",
      "ralphex progress logs",
      "Security & Secrets",
      "Terraform & Terragrunt",
      "Testing",
    ]);
  });

  it("pins ESLint", () => {
    expect(GLOB_EXCLUDE).toEqual([
      "**/node_modules",
      "**/dist",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/bun.lock",
      "**/npm-shrinkwrap.json",
      "**/go.sum",
      "**/Cargo.lock",
      "**/poetry.lock",
      "**/uv.lock",
      "**/Pipfile.lock",
      "**/Gemfile.lock",
      "**/composer.lock",
      "**/mix.lock",
      "**/flake.lock",
      "**/pubspec.lock",
      "**/Podfile.lock",
      "**/vendor",
      "**/.pnpm-store",
      "**/.pnp.*",
      "**/generated",
      "**/output",
      "**/coverage",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/build",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.nuxt",
      "**/.turbo",
      "**/playwright-report-html",
      "**/playwright-report-allure",
      "**/playwright-report-*/**",
      "**/.git",
      "**/.next",
      "**/out",
      "**/storybook-static",
      "**/.svelte-kit",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.cache",
      "**/.output",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import?(s).d.ts",
      "**/components.d.ts",
      "**/.datamitsu",
      "**/*.json.enc",
      "**/*.yaml.enc",
      "**/*.yml.enc",
    ]);
  });

  it("pins oxlint", () => {
    expect(toOxlintIgnorePatterns(GLOB_EXCLUDE)).toEqual([
      "**/node_modules",
      "**/dist",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/bun.lock",
      "**/npm-shrinkwrap.json",
      "**/go.sum",
      "**/Cargo.lock",
      "**/poetry.lock",
      "**/uv.lock",
      "**/Pipfile.lock",
      "**/Gemfile.lock",
      "**/composer.lock",
      "**/mix.lock",
      "**/flake.lock",
      "**/pubspec.lock",
      "**/Podfile.lock",
      "**/vendor",
      "**/.pnpm-store",
      "**/.pnp.*",
      "**/generated",
      "**/output",
      "**/coverage",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/build",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.nuxt",
      "**/.turbo",
      "**/playwright-report-html",
      "**/playwright-report-allure",
      "**/playwright-report-*/**",
      "**/.git",
      "**/.next",
      "**/out",
      "**/storybook-static",
      "**/.svelte-kit",
      "**/.vercel",
      "**/.changeset",
      "**/.idea",
      "**/.cache",
      "**/.output",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import.d.ts",
      "**/auto-imports.d.ts",
      "**/components.d.ts",
      "**/.datamitsu",
      "**/*.json.enc",
      "**/*.yaml.enc",
      "**/*.yml.enc",
    ]);
  });

  it("pins cspell", () => {
    expect(ignorePaths).toEqual([
      "**/coverage",
      "**/node_modules",
      "**/dist",
      "**/.git",
      "**/.gitignore",
      "**/.dockerignore",
      "**/.gitattributes",
      "**/__tests__/**",
      "**/out",
      "**/*.cast",
      "**/storybook-static",
      "**/vendor",
      "cspell.config.js",
      "datamitsu.config.js",
      "**/pnpm-lock.yaml",
      "go.mod",
      "**/go.sum",
      "**/.pnpm-store",
      "**/.pnp.*",
      "**/.yarn",
      "**/.next",
      "**/.nuxt",
      "**/.svelte-kit",
      "**/.output",
      "**/.vercel",
      "**/.turbo",
      "**/.cache",
      "**/.datamitsu",
      "**/package-lock.json",
      "**/npm-shrinkwrap.json",
      "**/yarn.lock",
      "**/bun.lock",
      "**/bun.lockb",
      "**/Cargo.lock",
      "**/poetry.lock",
      "**/uv.lock",
      "**/Pipfile.lock",
      "**/Gemfile.lock",
      "**/composer.lock",
      "**/mix.lock",
      "**/flake.lock",
      "**/pubspec.lock",
      "**/Podfile.lock",
    ]);
  });

  it("pins YAML", () => {
    expect(yamlIgnore).toEqual(["**/pnpm-lock.yaml", "**/*.sops.yaml", "**/.sops.yml"]);
  });

  it("pins the JSON and YAML planner excludes", () => {
    expect(jsonExcludeGlobs).toEqual([
      "**/package.json",
      "**/package-lock.json",
      "**/*.json.enc",
      "**/*.enc.json",
    ]);
    expect(yamlExcludeGlobs).toEqual([
      "**/pnpm-lock.yaml",
      "**/*.sops.yaml",
      "**/*.sops.yml",
      "**/.sops.yml",
      "**/*.yaml.enc",
      "**/*.yml.enc",
      "**/*.enc.yaml",
      "**/*.enc.yml",
    ]);
  });

  it("pins trufflehog", () => {
    expect(trufflehogExcludePaths).toEqual([
      "(?:^|/)(?:package-lock\\.json|pnpm-lock\\.yaml|yarn\\.lock|npm-shrinkwrap\\.json|bun\\.lockb?|go\\.sum|Cargo\\.lock|poetry\\.lock|uv\\.lock|Pipfile\\.lock|Gemfile\\.lock|composer\\.lock|mix\\.lock|flake\\.lock|pubspec\\.lock|Podfile\\.lock)$",
      "(?:^|/)__snapshots__/",
      "(?:^|/)testdata/",
      "(?:^|/)fixtures?/",
      "\\.min\\.(?:js|css)$",
      "\\.bundle\\.(?:js|css)$",
    ]);
  });

  it("strips only the exact Claude directory line", () => {
    expect(filterIgnore(".claude/\n.claude/*\n!.claude/skills/\nnode_modules/\n .claude/\n")).toBe(
      ".claude/*\n!.claude/skills/\nnode_modules/\n .claude/\n",
    );
  });
});
