export const formatTerraformSpacingSh: config.ConfigSetup = {
  content: () => {
    return [
      "#!/usr/bin/env bash",
      "",
      "# Terraform entities that should have blank lines before them",
      "TERRAFORM_ENTITIES=(",
      '  "variable"',
      '  "resource"',
      '  "data"',
      '  "output"',
      '  "locals"',
      '  "module"',
      '  "terraform"',
      '  "provider"',
      ")",
      "",
      "# Cross-platform sed in-place",
      "if sed --version 2>/dev/null | grep -q GNU; then",
      '  sed_inplace() { sed -i "$@"; }',
      "else",
      `  sed_inplace() { sed -i '' "$@"; }`,
      "fi",
      "",
      'for file in "$@"; do',
      "  # Step 1: Add 3 blank lines before each Terraform entity",
      "  temp_file=$(mktemp)",
      '  cp "$file" "$temp_file"',
      "",
      // oxlint-disable-next-line no-template-curly-in-string -- shell script syntax, not JS template
      '  for entity in "${TERRAFORM_ENTITIES[@]}"; do',
      "    # Match entity at the beginning of line (with optional spaces)",
      "    # Replace with 3 newlines + the matched line",
      `    sed_inplace "s/^[[:space:]]*\${entity}[[:space:]]*\\"/\\n\\n\\n\${entity} \\"/g" "$temp_file"`,
      "  done",
      "",
      "  # Step 2: Remove duplicate blank lines (keep max 1 consecutive blank line)",
      `  awk 'BEGIN{blank=0} /^[[:space:]]*$/{blank++; if(blank<=1) print; next} {blank=0; print}' "$temp_file" > "$temp_file.2"`,
      "",
      "  # Step 3: Remove leading blank lines",
      `  sed_inplace '1{/^[[:space:]]*$/d;}' "$temp_file.2"`,
      "",
      "  # Move the result back to the original file",
      '  mv "$temp_file.2" "$file"',
      '  rm -f "$temp_file"',
      "done",
      "",
    ].join("\n");
  },
  projectTypes: ["terraform-project", "terragrunt-project"],
  scope: "git-root",
};
