import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(import.meta.dirname, "../..");
const BIN = join(ROOT, "bin/datamitsu.js");
const BASE_CONFIG = join(ROOT, "datamitsu.config.base.js");

describe("bin/datamitsu.js", () => {
  // The wrapper must always inject --before-config so every datamitsu
  // invocation resolves the same base config (and configHash). Dropping this
  // flag is the root cause of the "wrong configHash → offline exec fails" class
  // of bugs.
  it("injects the --before-config flag", () => {
    expect(readFileSync(BIN, "utf8")).toContain("--before-config");
  });

  it("points --before-config at an existing datamitsu.config.base.js", () => {
    // Generated by `pnpm build`; present after setup-environment runs prepare.
    expect(existsSync(BASE_CONFIG)).toBe(true);
  });
});
