import { describe, expect, it } from "vitest";

import {
  type ConfigShowOutput,
  extractToolsInfo,
  generateToolsMarkdown,
  parseConfigJson,
  type ToolDocInfo,
} from "../generate-docs-tools.ts";

const validConfig: ConfigShowOutput = {
  tools: {
    eslint: {
      name: "ESLint",
      operations: {
        check: {
          app: "eslint",
          args: ["--max-warnings=0", "."],
          scope: "per-project",
        },
        fix: {
          app: "eslint",
          args: ["--fix", "."],
          scope: "per-project",
        },
      },
      projectTypes: ["typescript-project", "javascript-project"],
    },
    prettier: {
      name: "Prettier",
      operations: {
        check: {
          app: "prettier",
          args: ["--check", "."],
          globs: ["**/*.{ts,js,json,md}"],
          scope: "per-project",
        },
        fix: {
          app: "prettier",
          args: ["--write", "."],
          globs: ["**/*.{ts,js,json,md}"],
          scope: "per-project",
        },
      },
    },
    tsc: {
      name: "TypeScript Compiler",
      operations: {
        check: {
          app: "tsc",
          args: ["--noEmit"],
          scope: "per-project",
        },
      },
      projectTypes: ["typescript-project"],
    },
  },
};

describe("parseConfigJson", () => {
  it("should parse valid JSON with tools field", () => {
    const result = parseConfigJson(JSON.stringify(validConfig));
    expect(result.tools).toBeDefined();
    expect(Object.keys(result.tools)).toHaveLength(3);
  });

  it("should throw on invalid JSON", () => {
    expect(() => parseConfigJson("not json")).toThrow();
  });

  it("should throw on missing tools field", () => {
    expect(() => parseConfigJson(JSON.stringify({ apps: {} }))).toThrow("missing 'tools' field");
  });

  it("should throw on null tools field", () => {
    expect(() => parseConfigJson(JSON.stringify({ tools: null }))).toThrow("missing 'tools' field");
  });

  it("should throw on non-object input", () => {
    expect(() => parseConfigJson(JSON.stringify("string"))).toThrow("missing 'tools' field");
  });

  it("should throw on array input", () => {
    expect(() => parseConfigJson(JSON.stringify([]))).toThrow("missing 'tools' field");
  });
});

describe("extractToolsInfo", () => {
  it("should extract and sort all tools alphabetically", () => {
    const result = extractToolsInfo(validConfig);
    expect(result).toHaveLength(3);
    expect(result.map((t) => t.name)).toEqual(["eslint", "prettier", "tsc"]);
  });

  it("should return empty array for empty tools", () => {
    const result = extractToolsInfo({ tools: {} });
    expect(result).toEqual([]);
  });

  it("should extract tool with correct display name", () => {
    const result = extractToolsInfo(validConfig);
    const eslint = result.find((t) => t.name === "eslint");
    expect(eslint?.displayName).toBe("ESLint");
  });

  it("should extract operations correctly", () => {
    const result = extractToolsInfo(validConfig);
    const eslint = result.find((t) => t.name === "eslint");
    expect(eslint?.operations).toEqual(["check", "fix"]);
  });

  it("should extract unique globs from operations", () => {
    const result = extractToolsInfo(validConfig);
    const prettier = result.find((t) => t.name === "prettier");
    expect(prettier?.globs).toEqual(["**/*.{ts,js,json,md}"]);
  });

  it("should extract scope from operations", () => {
    const result = extractToolsInfo(validConfig);
    const eslint = result.find((t) => t.name === "eslint");
    expect(eslint?.scope).toBe("per-project");
  });

  it("should handle tools without project types", () => {
    const result = extractToolsInfo(validConfig);
    const prettier = result.find((t) => t.name === "prettier");
    expect(prettier?.projectTypes).toEqual([]);
  });

  it("should handle tools with project types", () => {
    const result = extractToolsInfo(validConfig);
    const eslint = result.find((t) => t.name === "eslint");
    expect(eslint?.projectTypes).toEqual(["typescript-project", "javascript-project"]);
  });
});

const sampleTools: ToolDocInfo[] = [
  {
    displayName: "ESLint",
    globs: [],
    name: "eslint",
    operations: ["check", "fix"],
    projectTypes: ["typescript-project"],
    scope: "per-project",
  },
  {
    displayName: "Prettier",
    globs: ["**/*.{ts,js,json,md}"],
    name: "prettier",
    operations: ["check", "fix"],
    projectTypes: [],
    scope: "per-project",
  },
];

describe("generateToolsMarkdown", () => {
  it("should include the title and auto-generation notice", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("# Configured Tools");
    expect(result).toContain("This file is automatically generated from the config");
    expect(result).toContain("Do not edit manually");
    expect(result).toContain("pnpm dm exec task -- docs:generate");
  });

  it("should include tools table with headers", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("| Tool | Operations | File Patterns | Project Types | Scope |");
    expect(result).toContain("| --- | --- | --- | --- | --- |");
  });

  it("should include tool names in the table", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("**eslint**");
    expect(result).toContain("**prettier**");
  });

  it("should not include a timestamp to avoid perpetual diffs", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).not.toContain("Last generated:");
    expect(result).not.toMatch(/\d{4}-\d{2}-\d{2}/);
  });

  it("should include tool count", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("**2 tools**");
  });

  it("should handle empty tool list", () => {
    const result = generateToolsMarkdown([]);
    expect(result).toContain("# Configured Tools");
    expect(result).toContain("**0 tools**");
    expect(result).toContain("| Tool | Operations | File Patterns | Project Types | Scope |");
  });

  it("should show 'all' for tools without specific globs", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("| **eslint** | check<br>fix | all |");
  });

  it("should show 'all' for tools without project types", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("| **prettier** | check<br>fix | `**/*.{ts,js,json,md}` | all |");
  });

  it("should include overview section", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("## Overview");
    expect(result).toContain("dm check");
    expect(result).toContain("dm fix");
  });

  it("should include Tools vs Apps explanation", () => {
    const result = generateToolsMarkdown(sampleTools);
    expect(result).toContain("## Understanding Tools vs Apps");
    expect(result).toContain("**Apps** are the actual applications");
    expect(result).toContain("**Tools** are configurations");
  });
});
