import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { generatedSourceBanner } from "../tsdown.config-banner.ts";

const sourceFile = path.join(import.meta.dirname, "../docs/reference/tsconfig.md");
const outFile = path.join(import.meta.dirname, "../src/datamitsu-config/tsconfig.md.ts");

// Read source
const content = await fs.readFile(sourceFile, "utf8").then((r) => r.trim());

// Escape backticks and template literals
/**
 * Escapes markdown for embedding in a template literal.
 *
 * The backslash pass has to come first, and it was missing: a chunk containing `C:\Users\…` emitted
 * `\U` into the literal, which evaluates to `U` — so the AGENTS.md shipped to consumers read
 * `C:Users…`. The blanket `/* eslint-disable *\/` this file used to carry hid it, because
 * `no-useless-escape` is exactly the rule that spots it.
 */
const escape = (s: string) =>
  s.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");

// Generate SHA256 hash
const sha256 = (s: string) => createHash("sha256").update(s).digest("hex");

// Build output
const lines: string[] = [
  generatedSourceBanner,
  "",
  "// AUTO-GENERATED by scripts/gen-tsconfig-md.ts — do not edit manually",
  "",
  `export const TSCONFIG_MD = \`${escape(content)}\`;`,
  "",
  `export const TSCONFIG_MD_HASH = "${sha256(content)}";`,
  "",
];

await fs.writeFile(outFile, lines.join("\n"), "utf8");
console.log(`Generated ${outFile}`);
