import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { tsdownConfigBanner } from "../tsdown.config-banner.ts";

const chunksDir = path.join(import.meta.dirname, "../agents-md-chunks");
const outFile = path.join(import.meta.dirname, "../src/datamitsu-config/agents.md.ts");

const entries = await fs.readdir(chunksDir);
const mdFiles = entries.filter((f) => f.endsWith(".md") && !f.startsWith(".example")).sort();

interface Chunk {
  content: string;
  file: string;
  name: string;
  prefix: string;
  varName: string;
}

const chunks: Chunk[] = await Promise.all(
  mdFiles.map(async (file) => {
    const content = await fs.readFile(path.join(chunksDir, file), "utf8").then((r) => r.trim());
    const stem = file.replace(/\.md$/, "");
    const match = /^(\d+)-(.+)$/.exec(stem);
    if (!match) {
      throw new Error(`Unexpected chunk filename: ${file}`);
    }
    const [, prefix, slug] = match as [string, string, string];
    const name = slug.replaceAll("-", "_").toUpperCase();
    return { content, file, name, prefix, varName: `CHUNK_${prefix}_${name}` };
  }),
);

interface Combination {
  exportName: string;
  parts: Chunk[];
}

// Layered system: prefix number determines the layer.
// AGENTS_BASE = all chunks at the minimum prefix (00).
// Terminal combos = all chunks below maxPrefix + each maxPrefix chunk individually.
// Adding a new layer (e.g. 30-*) automatically includes 00+10+20 chunks before it.
const prefixNums = [...new Set(chunks.map((c) => parseInt(c.prefix, 10)))].sort((a, b) => a - b);
const minPrefix = prefixNums.at(0)!;
const maxPrefix = prefixNums.at(-1)!;

const combinations: Combination[] = [
  {
    exportName: "AGENTS_BASE",
    parts: chunks.filter((c) => parseInt(c.prefix, 10) === minPrefix),
  },
];

const belowMax = chunks.filter((c) => parseInt(c.prefix, 10) < maxPrefix);
for (const terminal of chunks.filter((c) => parseInt(c.prefix, 10) === maxPrefix)) {
  combinations.push({
    exportName: `AGENTS_${terminal.name}`,
    parts: [...belowMax, terminal],
  });
}

const escape = (s: string) => s.replaceAll("`", "\\`").replaceAll("${", "\\${");

const sha256 = (s: string) => createHash("sha256").update(s).digest("hex");

const lines: string[] = [
  ...tsdownConfigBanner.split("\n").filter((el) => el !== `// @ts-nocheck`),
  "",
  "// AUTO-GENERATED by scripts/gen-agents-md.ts — do not edit manually",
  "",
  "// ── Chunks ──────────────────────────────────────────────────────────────────",
];

for (const chunk of chunks) {
  lines.push("", `const ${chunk.varName} = \`${escape(chunk.content)}\`;`);
}

lines.push("", "// ── Joined combinations ─────────────────────────────────────────────────────");

const joinedValues: Record<string, string> = {};

for (const combo of combinations) {
  const joined = combo.parts.map((p) => p.content).join("\n\n");
  joinedValues[combo.exportName] = joined;
  const partsExpr = combo.parts.map((p) => p.varName).join(", ");
  lines.push(
    `export const ${combo.exportName} = [${partsExpr}].join("\\n\\n"); // prettier-ignore`,
  );
}

lines.push("", "// ── Chunk hashes (sha256, computed at build time) ────────────────────────────");

for (const chunk of chunks) {
  lines.push(`export const ${chunk.varName}_HASH = "${sha256(chunk.content)}"; // prettier-ignore`);
}

const allChunkHashNames = chunks.map((c) => `${c.varName}_HASH`).join(", ");
lines.push("", `export const ALL_AGENTS_HASHES = [${allChunkHashNames}]; // prettier-ignore`);

lines.push("");

await fs.writeFile(outFile, lines.join("\n"), "utf8");

const names = combinations.map((c) => c.exportName).join(", ");
console.log(`Generated ${outFile} — exports: ${names}`);
