import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { tsdownConfigBanner } from "../tsdown.config-banner.ts";

const skillsDir = path.join(import.meta.dirname, "../skills-chunks");
const outFile = path.join(import.meta.dirname, "../src/datamitsu-config/skills.ts");

const entries = await fs.readdir(skillsDir, { withFileTypes: true });
const skillDirs = entries
  .filter((e) => e.isDirectory())
  .sort((a, b) => a.name.localeCompare(b.name));

const removedPath = path.join(skillsDir, ".removed.json");
const removedSkills: string[] = JSON.parse(await fs.readFile(removedPath, "utf8"));

for (const name of removedSkills) {
  if (skillDirs.some((d) => d.name === name)) {
    throw new Error(`Skill "${name}" is in both skills-chunks/ and .removed.json — remove one`);
  }
}

interface SkillSource {
  adapters: {
    claude: string;
    codex: string;
  };
  instructions: string;
  name: string;
  varName: string;
}

const skills: SkillSource[] = await Promise.all(
  skillDirs.map(async (dir) => {
    const skillPath = path.join(skillsDir, dir.name);

    const instructions = await fs
      .readFile(path.join(skillPath, "instructions.md"), "utf8")
      .then((r) => r.trim());
    const claude = await fs
      .readFile(path.join(skillPath, "adapters/claude.md"), "utf8")
      .then((r) => r.trim());
    const codex = await fs
      .readFile(path.join(skillPath, "adapters/codex.md"), "utf8")
      .then((r) => r.trim());

    const varName = `SKILL_${dir.name.replaceAll("-", "_").toUpperCase()}`;

    return { adapters: { claude, codex }, instructions, name: dir.name, varName };
  }),
);

const escape = (s: string) => s.replaceAll("`", "\\`").replaceAll("${", "\\${");

const sha256 = (s: string) => createHash("sha256").update(s).digest("hex");

const lines: string[] = [
  ...tsdownConfigBanner.split("\n").filter((el) => el !== `// @ts-nocheck`),
  "",
  "// AUTO-GENERATED by scripts/gen-skills.ts — do not edit manually",
  "",
];

for (const skill of skills) {
  lines.push(
    `// ── Skill: ${skill.name} ${"─".repeat(Math.max(1, 64 - skill.name.length))}`,
    "",
    `const ${skill.varName}_INSTRUCTIONS = \`${escape(skill.instructions)}\`;`,
    "",
    `const ${skill.varName}_ADAPTER_CLAUDE = \`${escape(skill.adapters.claude)}\`;`,
    "",
    `const ${skill.varName}_ADAPTER_CODEX = \`${escape(skill.adapters.codex)}\`;`,
    "",
  );
}

lines.push(
  "// ── Exports ─────────────────────────────────────────────────────────────────",
  "",
  "export interface SkillDefinition {",
  "  adapters: {",
  "    claude: string;",
  "    codex: string;",
  "  };",
  "  instructions: string;",
  "  name: string;",
  "}",
  "",
  "export const SKILLS: SkillDefinition[] = [",
);

for (const skill of skills) {
  lines.push(
    "  {",
    `    adapters: {`,
    `      claude: ${skill.varName}_ADAPTER_CLAUDE,`,
    `      codex: ${skill.varName}_ADAPTER_CODEX,`,
    `    },`,
    `    instructions: ${skill.varName}_INSTRUCTIONS,`,
    `    name: "${skill.name}",`,
    "  },",
  );
}

lines.push("];", "");

lines.push(
  "// ── Removed skills (auto-cleanup on dm init) ────────────────────────────────",
  "",
  `export const REMOVED_SKILLS: string[] = ${JSON.stringify(removedSkills)};`,
  "",
);

lines.push("// ── Hashes (sha256, computed at build time) ────────────────────────────────");

for (const skill of skills) {
  lines.push(
    `export const ${skill.varName}_INSTRUCTIONS_HASH = "${sha256(skill.instructions)}"; // prettier-ignore`,
  );
  lines.push(
    `export const ${skill.varName}_ADAPTER_CLAUDE_HASH = "${sha256(skill.adapters.claude)}"; // prettier-ignore`,
  );
  lines.push(
    `export const ${skill.varName}_ADAPTER_CODEX_HASH = "${sha256(skill.adapters.codex)}"; // prettier-ignore`,
  );
}

lines.push("");

await fs.writeFile(outFile, lines.join("\n"), "utf8");

const names = skills.map((s) => s.name).join(", ");
console.log(`Generated ${outFile} — skills: ${names}`);
