import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

import { tsdownConfigBanner } from "../tsdown.config-banner.ts";

const sourceFile = path.join(import.meta.dirname, "../docs/reference/tsconfig.md");
const outFile = path.join(import.meta.dirname, "../src/datamitsu-config/tsconfig.md.ts");

// Read source
const content = await fs.readFile(sourceFile, "utf8").then((r) => r.trim());

// Escape backticks and template literals
const escape = (s: string) => s.replaceAll("`", "\\`").replaceAll("${", "\\${");

// Generate SHA256 hash
const sha256 = (s: string) => createHash("sha256").update(s).digest("hex");

// Build output
const lines: string[] = [
  ...tsdownConfigBanner.split("\n").filter((el) => el !== `// @ts-nocheck`),
  "",
  "// AUTO-GENERATED by scripts/gen-tsconfig-md.ts — do not edit manually",
  "",
  `export const TSCONFIG_MD = \`${escape(content)}\`;`,
  "",
  `export const TSCONFIG_MD_HASH = "${sha256(content)}";`,
  "",
];

await fs.writeFile(outFile, lines.join("\n"), "utf8");
console.log(`Generated ${outFile}`);
