import { execSync } from "node:child_process";

import { writeAndFix } from "./lib/write-and-fix.ts";

export interface ConfigSetupData {
  deleteOnly?: boolean;
  linkTarget?: string;
  otherFileNameList?: string[];
  projectTypes?: string[];
  scope?: "git-root" | "project";
}

export interface ConfigShowOutput {
  setup: Record<string, ConfigSetupData>;
}

export interface SetupConfigDocInfo {
  deleteOnly: boolean;
  linkTarget: string;
  name: string;
  otherFileNameList: string[];
  projectTypes: string[];
  scope: string;
}

export function executeConfigShow(): string {
  return execSync("pnpm --silent dm config show", {
    encoding: "utf8",
    stdio: ["pipe", "pipe", "ignore"], // Ignore stderr to avoid pnpm lockfile messages
    timeout: 30_000,
  });
}

export function extractInitConfigsInfo(config: ConfigShowOutput): SetupConfigDocInfo[] {
  return Object.entries(config.setup)
    .map(([name, initConfig]) => ({
      deleteOnly: initConfig.deleteOnly ?? false,
      linkTarget: initConfig.linkTarget ?? "",
      name,
      otherFileNameList: initConfig.otherFileNameList ?? [],
      projectTypes: initConfig.projectTypes ?? [],
      scope: initConfig.scope ?? "project",
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function generateInitConfigsMarkdown(configs: SetupConfigDocInfo[]): string {
  const lines = [
    "# Setup Configurations",
    "",
    "<!-- Auto-generated list of setup configs in @shibanet0/datamitsu-config. -->",
    "",
    "<!--",
    "Note: This file is automatically generated from the config.",
    "Do not edit manually. To update, run: `pnpm dm exec task -- docs:generate`",
    "-->",
    "",
    "## Overview",
    "",
    "Setup configurations define which files datamitsu creates when you run `dm setup`.",
    "These include dotfiles, tool configurations, AI instructions, and IDE settings.",
    "",
    `This configuration includes **${configs.length} setup configs**.`,
    "",
    "## Setup Configs Reference",
    "",
    generateInitConfigsTable(configs),
    "",
    "## Field Descriptions",
    "",
    "- **File**: The filename or path that will be created or managed",
    "- **Scope**: Where the file is created:",
    "  - `git-root`: Created at the repository root",
    "  - `project`: Created in each project directory (for monorepos)",
    "- **Project Types**: Which project types this config applies to (empty = all projects)",
    "- **Link Target**: If present, creates a symlink to this target instead of a file",
    "- **Delete Only**: If checked (✓), only removes files without creating new ones",
    "- **Also Deletes**: Other filenames that will be removed when this config is applied",
    "",
    "## How Setup Works",
    "",
    "When you run `dm setup`, datamitsu:",
    "",
    "1. Detects your project type (npm, Go, TypeScript, etc.)",
    "2. Filters configs by project type (configs with empty project types apply to all)",
    "3. For each config:",
    "   - If **Delete Only** is checked: removes the file and any files in **Also Deletes**",
    "   - If **Link Target** is set: creates a symlink to the target",
    "   - Otherwise: generates content and merges with existing files",
    "4. Preserves your customizations during updates",
    "",
  ];
  return lines.join("\n");
}

export async function main(): Promise<void> {
  const outputPath = "docs/reference/init-configs.md";
  const jsonStr = executeConfigShow();
  const config = parseConfigJson(jsonStr);
  const configs = extractInitConfigsInfo(config);
  const markdown = generateInitConfigsMarkdown(configs);

  const result = await writeAndFix({
    content: markdown,
    filePath: outputPath,
    verbose: true,
  });

  if (!result.success) {
    console.error(`Failed to write or fix ${outputPath}`);
    if (result.fixResult?.error) {
      console.error(`Error: ${result.fixResult.error}`);
    }
    process.exit(1);
  }

  console.log(`Generated ${outputPath} with ${configs.length} setup configs`);
}

export function parseConfigJson(jsonStr: string): ConfigShowOutput {
  const data: unknown = JSON.parse(jsonStr);
  if (typeof data !== "object" || data === null || !("setup" in data)) {
    throw new Error("Invalid config output: missing 'setup' field");
  }
  return data as ConfigShowOutput;
}

function formatFileList(files: string[]): string {
  if (files.length === 0) {
    return "—";
  }
  return files.map((f) => `\`${f}\``).join("<br>");
}

function generateInitConfigsTable(configs: SetupConfigDocInfo[]): string {
  const header = "| File | Scope | Project Types | Link Target | Delete Only | Also Deletes |";
  const separator = "| --- | --- | --- | --- | --- | --- |";

  const rows = configs.map((c) => {
    const file = `\`${c.name}\``;
    const scope = c.scope;
    const projectTypes = c.projectTypes.length > 0 ? c.projectTypes.join(", ") : "all";
    const linkTarget = c.linkTarget ? `\`${c.linkTarget}\`` : "—";
    const alsoDeletes = formatFileList(c.otherFileNameList);
    const deleteOnly = c.deleteOnly ? "✓" : "";

    return `| ${file} | ${scope} | ${projectTypes} | ${linkTarget} | ${deleteOnly} | ${alsoDeletes} |`;
  });

  return [header, separator, ...rows].join("\n");
}

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/generate-docs-init-configs.ts");

if (isDirectRun) {
  try {
    await main();
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
