import { execSync } from "node:child_process";

import { writeAndFix } from "./lib/write-and-fix.ts";

export interface ConfigShowOutput {
  tools: Record<string, ToolConfig>;
}

export interface ToolConfig {
  name: string;
  operations: Record<string, ToolOperation>;
  projectTypes?: string[];
}

export interface ToolDocInfo {
  displayName: string;
  globs: string[];
  name: string;
  operations: string[];
  projectTypes: string[];
  scope: string;
}

export interface ToolOperation {
  app: string;
  args: string[];
  globs?: string[];
  priority?: number;
  scope?: string;
}

export function executeConfigShow(): string {
  return execSync("pnpm --silent dm config show", {
    encoding: "utf8",
    stdio: ["pipe", "pipe", "ignore"], // Ignore stderr to avoid pnpm lockfile messages
    timeout: 30_000,
  });
}

export function extractToolsInfo(config: ConfigShowOutput): ToolDocInfo[] {
  return Object.entries(config.tools)
    .map(([name, toolConfig]) => ({
      displayName: toolConfig.name,
      globs: extractUniqueGlobs(toolConfig.operations),
      name,
      operations: Object.keys(toolConfig.operations),
      projectTypes: toolConfig.projectTypes || [],
      scope: extractScope(toolConfig.operations),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function generateToolsMarkdown(tools: ToolDocInfo[]): string {
  const lines = [
    "# Configured Tools",
    "",
    "<!-- Auto-generated list of tools configured in @shibanet0/datamitsu-config. -->",
    "",
    "<!--",
    "Note: This file is automatically generated from the config.",
    "Do not edit manually. To update, run: `pnpm dm exec task -- docs:generate`",
    "-->",
    "",
    "## Overview",
    "",
    "Tools are configurations that define how to run [apps](apps.md) automatically via `dm check` and `dm fix`.",
    "Each tool references an app with specific arguments, file globs, and execution scope.",
    "",
    `This configuration includes **${tools.length} tools**.`,
    "",
    "## Tools Reference",
    "",
    generateToolsTable(tools),
    "",
    "## Understanding Tools vs Apps",
    "",
    "- **Apps** are the actual applications installed by datamitsu (eslint, prettier, etc.)",
    "- **Tools** are configurations that tell datamitsu how to run those apps",
    "- When you run `dm check`, datamitsu executes all configured tools",
    "- When you run `dm fix`, datamitsu executes tools with fix operations",
    "",
  ];
  return lines.join("\n");
}

export async function main(): Promise<void> {
  const outputPath = "docs/reference/tools.md";
  const jsonStr = executeConfigShow();
  const config = parseConfigJson(jsonStr);
  const tools = extractToolsInfo(config);
  const markdown = generateToolsMarkdown(tools);

  const result = await writeAndFix({
    content: markdown,
    filePath: outputPath,
    verbose: true,
  });

  if (!result.success) {
    console.error(`Failed to write or fix ${outputPath}`);
    if (result.fixResult?.error) {
      console.error(`Error: ${result.fixResult.error}`);
    }
    process.exit(1);
  }

  console.log(`Generated ${outputPath} with ${tools.length} tools`);
}

export function parseConfigJson(jsonStr: string): ConfigShowOutput {
  const data: unknown = JSON.parse(jsonStr);
  if (typeof data !== "object" || data === null || !("tools" in data) || data.tools === null) {
    throw new Error("Invalid config output: missing 'tools' field");
  }
  return data as ConfigShowOutput;
}

function extractScope(operations: Record<string, ToolOperation>): string {
  const scopes = new Set<string>();
  for (const op of Object.values(operations)) {
    if (op.scope) {
      scopes.add(op.scope);
    }
  }
  return [...scopes].join(", ");
}

function extractUniqueGlobs(operations: Record<string, ToolOperation>): string[] {
  const globsSet = new Set<string>();
  for (const op of Object.values(operations)) {
    if (op.globs) {
      for (const glob of op.globs) {
        globsSet.add(glob);
      }
    }
  }
  return [...globsSet].sort();
}

function generateToolsTable(tools: ToolDocInfo[]): string {
  const header = "| Tool | Operations | File Patterns | Project Types | Scope |";
  const separator = "| --- | --- | --- | --- | --- |";
  const rows = tools.map((t) => {
    const operations = t.operations.join("<br>");
    const globs = t.globs.length > 0 ? t.globs.map((g) => `\`${g}\``).join("<br>") : "all";
    const projectTypes = t.projectTypes.length > 0 ? t.projectTypes.join("<br>") : "all";
    const scope = t.scope;
    return `| **${t.name}** | ${operations} | ${globs} | ${projectTypes} | ${scope} |`;
  });
  return [header, separator, ...rows].join("\n");
}

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/generate-docs-tools.ts");

if (isDirectRun) {
  try {
    await main();
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
