/**
 * Regenerates `src/apps/oxlint/plugins.generated.ts`.
 *
 * Oxlint ships with three plugins on — `unicorn`, `typescript`, `oxc` — and twelve off. A config
 * that omits the `plugins` key gets those three and nothing else, which is not a decision anyone
 * made here: it is the default leaking through a key we never wrote. The other twelve carry ~370
 * rules that this config already has opinions about, recorded in `src/lint-rules` and censused in
 * `rule-inventory.json`, and none of them were running.
 *
 * So enumerate them instead of listing them by hand. The names come from the pinned build's own
 * configuration schema (`definitions.LintPluginOptionsSchema.enum`) — the same file `json2ts` turns
 * into `src/apps/oxlint/schema.d.ts`, so the array and the type union cannot describe different
 * plugin sets. A plugin added upstream appears here on the next `task oxlint:sync:schema`, and the
 * validator in `scripts/generate-rule-inventory.ts` fails until its rules have been triaged.
 *
 * The generated file also asserts exhaustiveness at the type level: dropping a plugin from the
 * array is a `tsc` error, not a silently smaller rule set.
 *
 * Runs as part of `task oxlint:sync:schema`, alongside the known-rules probe.
 */
import fsPromise from "node:fs/promises";
import path from "node:path";

const repoRoot = path.join(import.meta.dirname, "..");

/**
 * The exceptions, with the reason each one is off. Anything not listed here is on.
 *
 * A plugin belongs here only when its rules cannot be reconciled with another plugin's by turning
 * individual rules off — otherwise the decision goes in `src/lint-rules`, at rule granularity,
 * where the inventory can see it.
 */
const EXCLUDED_PLUGINS: Record<string, string> = {
  jest: "vitest owns the test rules; the two plugins report the same finding on the same line under two names (jest/prefer-expect-assertions and vitest/prefer-expect-assertions were 264 each on this repository), and the overlap is the rule set, not a handful of rules",
};

const schema = JSON.parse(
  await fsPromise.readFile(path.join(repoRoot, "oxlint_configuration_schema.json"), "utf8"),
) as { definitions: { LintPluginOptionsSchema?: { enum?: string[] } } };

const plugins = schema.definitions.LintPluginOptionsSchema?.enum;

if (!Array.isArray(plugins) || plugins.length === 0) {
  throw new Error(
    "oxlint_configuration_schema.json has no `definitions.LintPluginOptionsSchema.enum`. " +
      "The schema moved the plugin list; update this script rather than shipping an empty one.",
  );
}

const unknownExclusion = Object.keys(EXCLUDED_PLUGINS).find((name) => !plugins.includes(name));

if (unknownExclusion) {
  throw new Error(
    `EXCLUDED_PLUGINS names "${unknownExclusion}", which the pinned oxlint build does not have. ` +
      `Drop the entry: excluding a plugin that no longer exists hides the fact that it is gone.`,
  );
}

const enabled = [...plugins].filter((name) => !(name in EXCLUDED_PLUGINS)).sort();
const excluded = Object.keys(EXCLUDED_PLUGINS).sort();

await fsPromise.writeFile(
  path.join(repoRoot, "src/apps/oxlint/plugins.generated.ts"),
  `// Generated by scripts/generate-oxlint-plugins.ts — do not edit.
//
// Every built-in plugin the pinned oxlint build knows about, minus the exceptions recorded in the
// generator. \`src/apps/oxlint/index.ts\` enables all of these: a plugin left off is a whole rule
// set switched off silently, which is the thing \`src/lint-rules\` exists to replace. Rules that are
// not wanted are turned off by name, with a reason.
import type { LintPluginOptionsSchema } from "./schema";

// prettier-ignore
export const OXLINT_PLUGINS = ${JSON.stringify(enabled, null, 2)} as const satisfies readonly LintPluginOptionsSchema[];

/**
 * Plugins deliberately left off. The reasons live in scripts/generate-oxlint-plugins.ts; they are
 * exported so the inventory validator can tell a decision apart from an oversight.
 */
// prettier-ignore
export const OXLINT_EXCLUDED_PLUGINS = ${JSON.stringify(excluded, null, 2)} as const satisfies readonly LintPluginOptionsSchema[];

/**
 * Fails the typecheck if a plugin is neither enabled nor deliberately excluded — including one the
 * next oxlint bump adds. Dropping a plugin from the array by hand is a compile error rather than a
 * quietly narrower lint.
 */
export type _EveryOxlintPluginIsAccountedFor = AssertNever<
  Exclude<
    LintPluginOptionsSchema,
    (typeof OXLINT_EXCLUDED_PLUGINS)[number] | (typeof OXLINT_PLUGINS)[number]
  >
>;

type AssertNever<T extends never> = T;
`,
  "utf8",
);

console.log(
  `oxlint-plugins: ${enabled.length} enabled (${enabled.join(", ")})` +
    (excluded.length > 0 ? `, ${excluded.length} excluded (${excluded.join(", ")})` : ""),
);
