/**
 * Regenerates `src/lint-rules/oxlint-known-rules.generated.ts`.
 *
 * Oxlint rejects the entire config file when it meets a rule or a plugin name it does not know —
 * even at `"off"`, and even inside a plugin it does know. The shared disabled-rules lists are
 * deliberately larger than oxlint's rule set (they also cover ESLint-only plugins such as sonarjs,
 * perfectionist and security), so the names have to be filtered before they reach oxlint.
 *
 * The filter is derived by asking the pinned oxlint binary rather than by reading its JSON schema:
 * the schema is a subset, and misses rules oxlint accepts (`react-hooks/exhaustive-deps`,
 * `jsdoc/require-param`, …). So: hand oxlint every candidate name at once, parse the names it
 * rejects out of the diagnostics, drop those, and confirm the survivors parse clean.
 *
 * Runs as part of `task oxlint:sync:schema`, so the list is regenerated whenever oxlint is bumped.
 */
import { execFile } from "node:child_process";
import fsPromise from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";

import { PERMANENTLY_DISABLED_RULES } from "../src/lint-rules/permanent.ts";
import { TEMPORARILY_DISABLED_RULES } from "../src/lint-rules/temporary.ts";

const execFileAsync = promisify(execFile);

const repoRoot = path.join(import.meta.dirname, "..");
const oxlintBin = path.join(repoRoot, "node_modules/.bin/oxlint");

/**
 * Same rewrite as `src/lint-rules/index.ts`, duplicated so this script does not import the module
 * it generates a dependency of.
 */
const ESLINT_TO_OXLINT_PREFIX: [string, string][] = [
  ["@typescript-eslint/", "typescript/"],
  ["import-x/", "import/"],
  ["jsx-a11y-x/", "jsx-a11y/"],
];

function toOxlintRuleName(name: string): string {
  for (const [eslintPrefix, oxlintPrefix] of ESLINT_TO_OXLINT_PREFIX) {
    if (name.startsWith(eslintPrefix)) {
      return oxlintPrefix + name.slice(eslintPrefix.length);
    }
  }
  return name;
}

const schema = JSON.parse(
  await fsPromise.readFile(path.join(repoRoot, "oxlint_configuration_schema.json"), "utf8"),
) as { definitions: { DummyRuleMap: { properties: Record<string, unknown> } } };

// The candidates: everything the schema advertises, plus every name the shared lists will hand to
// oxlint. The second half is what the schema misses.
const candidates = new Set<string>(Object.keys(schema.definitions.DummyRuleMap.properties));
for (const name of [
  ...Object.keys(PERMANENTLY_DISABLED_RULES),
  ...Object.keys(TEMPORARILY_DISABLED_RULES),
]) {
  candidates.add(toOxlintRuleName(name));
}

const workDir = await fsPromise.mkdtemp(path.join(os.tmpdir(), "oxlint-known-rules-"));
await fsPromise.writeFile(path.join(workDir, "probe.js"), "export const probe = 1;\n", "utf8");

/**
 * Runs oxlint over `names` and returns the ones it refused.
 */
async function reject(names: Iterable<string>): Promise<Set<string>> {
  const rules: Record<string, string> = {};
  for (const name of names) {
    rules[name] = "off";
  }

  await fsPromise.writeFile(
    path.join(workDir, ".oxlintrc.json"),
    JSON.stringify({ rules }, null, 2),
    "utf8",
  );

  const { stderr, stdout } = await execFileAsync(oxlintBin, ["-c", ".oxlintrc.json", "probe.js"], {
    cwd: workDir,
  }).catch((error: { stderr?: string; stdout?: string }) => ({
    stderr: error.stderr ?? "",
    stdout: error.stdout ?? "",
  }));

  const output = `${stdout}\n${stderr}`;
  const rejected = new Set<string>();

  for (const [, plugin] of output.matchAll(/Plugin '([^']+)' not found/g)) {
    for (const name of names) {
      if (name.startsWith(`${plugin}/`)) {
        rejected.add(name);
      }
    }
  }

  for (const [, rule, plugin] of output.matchAll(/Rule '([^']+)' not found in plugin '([^']+)'/g)) {
    rejected.add(plugin === "eslint" ? rule : `${plugin}/${rule}`);
  }

  return rejected;
}

const rejected = await reject(candidates);
const known = [...candidates].filter((name) => !rejected.has(name)).sort();

if (known.length === 0) {
  throw new Error("oxlint rejected every candidate rule — is the binary installed?");
}

// Confirm the survivors really do parse: a diagnostic shape this script does not know about would
// otherwise be silently baked into the generated list.
const stillRejected = await reject(known);
if (stillRejected.size > 0) {
  throw new Error(
    `oxlint still rejects ${stillRejected.size} rule(s) after filtering: ${[...stillRejected].sort().join(", ")}`,
  );
}

await fsPromise.rm(workDir, { force: true, recursive: true });

const { stdout: version } = await execFileAsync(oxlintBin, ["--version"]);

await fsPromise.writeFile(
  path.join(repoRoot, "src/lint-rules/oxlint-known-rules.generated.ts"),
  `// Generated by scripts/generate-oxlint-known-rules.ts — do not edit.
// Source: ${version.trim()}
//
// Every rule name the pinned oxlint build accepts. \`src/lint-rules/index.ts\` filters the shared
// disabled-rules lists through this, because oxlint rejects the whole config file over one unknown
// name — see the script for the full reasoning.
// prettier-ignore\nexport const OXLINT_KNOWN_RULES: string[] = ${JSON.stringify(known, null, 2)};
`,
  "utf8",
);

console.log(
  `oxlint-known-rules: ${known.length} accepted, ${rejected.size} rejected (${version.trim()})`,
);
