import { execSync } from "node:child_process";

import { sanitizeDescription } from "./lib/sanitize-markdown.ts";
import { writeAndFix } from "./lib/write-and-fix.ts";

export interface AppConfig {
  binary?: {
    binaries?: BinaryPlatforms;
  };
  description: string | undefined;
  fnm?: {
    packageName?: string;
    version?: string;
  };
  jvm?: {
    jarHash?: string;
    jarUrl?: string;
    version?: string;
  };
  uv?: {
    packageName?: string;
    version?: string;
  };
}

export interface AppInfo {
  description: string | undefined;
  name: string;
  repository: string | undefined;
  runtime: string;
}

export interface ConfigShowOutput {
  apps: Record<string, AppConfig>;
}

type BinaryPlatforms = Record<
  string,
  Record<
    string,
    Record<
      string,
      {
        url?: string;
      }
    >
  >
>;

export function categorizeApps(apps: AppInfo[]): Map<string, AppInfo[]> {
  const categories = new Map<string, AppInfo[]>();

  const categoryMap: Record<string, string[]> = {
    "Build Tools": ["tsc", "buf", "protoc", "swag", "openapi-generator", "quicktype", "sqlc"],
    "Documentation & Spelling": [
      "cspell",
      "vale",
      "markdown-link-check",
      "mmdc",
      "lychee",
      "slidev",
      "zensical",
      "typst",
    ],
    "Git Hooks": ["commitlint", "lefthook", "pre-commit"],
    "Linters & Formatters": [
      "eslint",
      "prettier",
      "oxlint",
      "ruff",
      "ktlint",
      "shfmt",
      "golangci-lint",
      "hadolint",
      "shellcheck",
      "markdownlint-cli2",
      "yamllint",
      "dotenv-linter",
      "editorconfig-checker",
      "checkmake",
      "protolint",
      "tflint",
      "typos",
      "typstyle",
      "sqlfluff",
    ],
    "Security Scanners": [
      "semgrep",
      "trivy",
      "grype",
      "gitleaks",
      "detect-secrets",
      "bearer",
      "checkov",
      "kube-linter",
      "osv-scanner",
      "scorecard",
      "snyk",
      "trufflehog",
    ],
  };

  // Initialize categories
  for (const categoryName of Object.keys(categoryMap)) {
    categories.set(categoryName, []);
  }
  categories.set("Utilities", []);

  // Categorize each app
  for (const app of apps) {
    let categorized = false;
    for (const [categoryName, appNames] of Object.entries(categoryMap)) {
      if (appNames.includes(app.name)) {
        categories.get(categoryName)?.push(app);
        categorized = true;
        break;
      }
    }
    if (!categorized) {
      categories.get("Utilities")?.push(app);
    }
  }

  // Remove empty categories
  for (const [categoryName, categoryApps] of categories.entries()) {
    if (categoryApps.length === 0) {
      categories.delete(categoryName);
    }
  }

  return categories;
}

export function executeConfigShow(): string {
  return execSync("pnpm --silent datamitsu config show", {
    encoding: "utf8",
    stdio: ["pipe", "pipe", "ignore"], // Ignore stderr to avoid pnpm lockfile messages
    timeout: 30_000,
  });
}

export function extractAllApps(config: ConfigShowOutput): AppInfo[] {
  return Object.entries(config.apps)
    .map(([name, app]) => extractAppInfo(name, app))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function extractAppInfo(name: string, app: AppConfig): AppInfo {
  const runtime = detectRuntime(app);
  let repository: string | undefined;

  if (app.binary) {
    repository = extractRepositoryFromBinary(app);
  } else if (app.fnm) {
    repository = extractRepositoryFromFnm(app);
  } else if (app.uv) {
    repository = extractRepositoryFromUv(app);
  } else if (app.jvm) {
    repository = extractRepositoryFromJvm(app);
  }

  return { description: app.description, name, repository, runtime };
}

export function generateAppsMarkdown(apps: AppInfo[]): string {
  const categories = categorizeApps(apps);

  const lines = [
    "# Apps",
    "",
    "<!-- Auto-generated list of apps managed by @shibanet0/datamitsu-config. -->",
    "",
    "<!--",
    "Note: This file is automatically generated from the config. Do not edit manually.",
    "To update, run: `pnpm dm exec task -- docs:generate`",
    "-->",
    "",
    "## Overview",
    "",
    "Apps are the actual applications managed by datamitsu. Unlike [Tools](tools.md) which are configurations, Apps are the binaries and packages that get installed and executed.",
    "",
    `This configuration manages **${apps.length} apps** across multiple runtimes (binary, node, python).`,
    "",
    "## Apps by Category",
    "",
    ...generateCategorySummary(categories),
    "",
    "## Apps Reference",
    "",
    generateMarkdownTable(apps),
    "",
    "## How Apps Work",
    "",
    "When you run `dm init`, datamitsu:",
    "",
    "1. Downloads and caches app binaries based on your project types",
    "2. Supports multiple runtimes:",
    "   - **binary** — Native executables (Go, Rust compiled tools)",
    "   - **node** — npm packages executed via Node.js",
    "   - **python** — Python packages installed via pip/uv",
    "3. Apps are referenced by [Tools](tools.md) configurations",
    "",
    "When you run `dm check`, datamitsu executes [Tools](tools.md), which invoke Apps with configured arguments and file globs.",
    "",
  ];
  return lines.join("\n");
}

export function generateCategorySummary(categories: Map<string, AppInfo[]>): string[] {
  const lines: string[] = [];
  for (const [categoryName, apps] of categories.entries()) {
    const examples = apps
      .slice(0, 3)
      .map((a) => a.name)
      .join(", ");
    const suffix = apps.length > 3 ? ", etc." : "";
    lines.push(`- **${categoryName}** (${apps.length} apps): ${examples}${suffix}`);
  }
  return lines;
}

export function generateMarkdownTable(apps: AppInfo[]): string {
  const header = "| App | Runtime | Info | Description |";
  const separator = "| --- | --- | --- | --- |";
  const rows = apps.map(
    (t) =>
      `| ${t.name} | ${t.runtime} | ${formatRepositoryLink(t.repository)} | ${formatDescription(t.description)} |`,
  );
  return [header, separator, ...rows].join("\n");
}

export async function main(): Promise<void> {
  const outputPath = "docs/reference/apps.md";
  const jsonStr = executeConfigShow();
  const config = parseConfigJson(jsonStr);
  const apps = extractAllApps(config);
  const markdown = generateAppsMarkdown(apps);

  const result = await writeAndFix({
    content: markdown,
    filePath: outputPath,
    verbose: true,
  });

  if (!result.success) {
    console.error(`Failed to write or fix ${outputPath}`);
    if (result.fixResult?.error) {
      console.error(`Error: ${result.fixResult.error}`);
    }
    process.exit(1);
  }

  console.log(`Generated ${outputPath} with ${apps.length} apps`);
}

export function parseConfigJson(jsonStr: string): ConfigShowOutput {
  const data: unknown = JSON.parse(jsonStr);
  if (typeof data !== "object" || data === null || !("apps" in data)) {
    throw new Error("Invalid config output: missing 'apps' field");
  }
  const config = data as ConfigShowOutput;
  if (typeof config.apps !== "object" || config.apps === null || Array.isArray(config.apps)) {
    throw new Error("Invalid config output: 'apps' is not an object");
  }
  return config;
}

function detectRuntime(app: AppConfig): string {
  if (app.fnm) {
    return "node";
  }
  if (app.uv) {
    return "python";
  }
  if (app.binary) {
    return "binary";
  }
  if (app.jvm) {
    return "jvm";
  }
  return "unknown";
}

function extractRepositoryFromBinary(app: AppConfig): string | undefined {
  const binaries = app.binary?.binaries;
  if (!binaries) {
    return undefined;
  }

  for (const os of Object.values(binaries)) {
    for (const arch of Object.values(os)) {
      for (const variant of Object.values(arch)) {
        const url = variant.url;
        if (!url) {
          continue;
        }
        const match = url.match(/github\.com\/([^/]+\/[^/]+)/);
        if (match) {
          return `https://github.com/${match[1]}`;
        }
      }
    }
  }
  return undefined;
}

function extractRepositoryFromFnm(app: AppConfig): string | undefined {
  const packageName = app.fnm?.packageName;
  if (!packageName) {
    return undefined;
  }
  return `https://www.npmjs.com/package/${packageName}`;
}

function extractRepositoryFromJvm(app: AppConfig): string | undefined {
  const jarUrl = app.jvm?.jarUrl;
  if (!jarUrl) {
    return undefined;
  }
  return jarUrl;
}

function extractRepositoryFromUv(app: AppConfig): string | undefined {
  const packageName = app.uv?.packageName;
  if (!packageName) {
    return undefined;
  }
  return `https://pypi.org/project/${packageName}`;
}

function formatDescription(description: string | undefined): string {
  return sanitizeDescription(description);
}

function formatRepositoryLink(repository: string | undefined): string {
  if (!repository) {
    return "N/A";
  }
  return `[Info](${repository}){:target="_blank"}`;
}

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/generate-docs-apps.ts");

if (isDirectRun) {
  try {
    await main();
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
