import { execSync } from "node:child_process";

import { sanitizeDescription } from "./lib/sanitize-markdown.ts";
import { writeAndFix } from "./lib/write-and-fix.ts";

export interface ConfigShowOutput {
  projectTypes: Record<string, ProjectTypeConfig>;
}

export interface ProjectTypeConfig {
  description: string;
  markers: string[];
}

export interface ProjectTypeDocInfo {
  description: string;
  markers: string[];
  name: string;
}

export function executeConfigShow(): string {
  return execSync("pnpm --silent dm config show", {
    encoding: "utf8",
    stdio: ["pipe", "pipe", "ignore"], // Ignore stderr to avoid pnpm lockfile messages
    timeout: 30_000,
  });
}

export function extractProjectTypesInfo(config: ConfigShowOutput): ProjectTypeDocInfo[] {
  return Object.entries(config.projectTypes)
    .map(([name, projectTypeConfig]) => ({
      description: projectTypeConfig.description,
      markers: projectTypeConfig.markers,
      name,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function generateProjectTypesMarkdown(types: ProjectTypeDocInfo[]): string {
  const lines = [
    "# Project Types",
    "",
    "<!-- Auto-generated list of project types configured in @shibanet0/datamitsu-config. -->",
    "",
    "<!--",
    "Note: This file is automatically generated from the config.",
    "Do not edit manually. To update, run: `pnpm dm exec task -- docs:generate`",
    "-->",
    "",
    "## Overview",
    "",
    "Project types define how datamitsu detects different kinds of projects in your repository.",
    "Each type has marker files or patterns that datamitsu uses for automatic detection.",
    "",
    `This configuration includes **${types.length} project types**.`,
    "",
    "## Project Types Reference",
    "",
    generateProjectTypesTable(types),
    "",
    "## How Project Type Detection Works",
    "",
    "When you run `dm init` or `dm check`, datamitsu:",
    "",
    "1. Scans your repository for marker files matching the patterns above",
    "2. Automatically detects which project types are present",
    "3. Enables the appropriate [tools](tools.md) for each detected project type",
    "",
    "For example, if your repository contains `package.json` files, datamitsu will:",
    "- Detect it as an `npm-package` project type",
    "- Enable tools like `eslint`, `prettier`, `oxlint`, and `sort-package-json`",
    "",
  ];
  return lines.join("\n");
}

export async function main(): Promise<void> {
  const outputPath = "docs/reference/project-types.md";
  const jsonStr = executeConfigShow();
  const config = parseConfigJson(jsonStr);
  const types = extractProjectTypesInfo(config);
  const markdown = generateProjectTypesMarkdown(types);

  const result = await writeAndFix({
    content: markdown,
    filePath: outputPath,
    verbose: true,
  });

  if (!result.success) {
    console.error(`Failed to write or fix ${outputPath}`);
    if (result.fixResult?.error) {
      console.error(`Error: ${result.fixResult.error}`);
    }
    process.exit(1);
  }

  console.log(`Generated ${outputPath} with ${types.length} project types`);
}

export function parseConfigJson(jsonStr: string): ConfigShowOutput {
  const data: unknown = JSON.parse(jsonStr);
  if (typeof data !== "object" || data === null || !("projectTypes" in data)) {
    throw new Error("Invalid config output: missing 'projectTypes' field");
  }
  return data as ConfigShowOutput;
}

function generateProjectTypesTable(types: ProjectTypeDocInfo[]): string {
  const header = "| Project Type | Description | Marker Files |";
  const separator = "| --- | --- | --- |";
  const rows = types.map((t) => {
    const markers = t.markers.map((m) => `\`${m}\``).join("<br>");
    return `| **${t.name}** | ${sanitizeDescription(t.description)} | ${markers} |`;
  });
  return [header, separator, ...rows].join("\n");
}

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/generate-docs-project-types.ts");

if (isDirectRun) {
  try {
    await main();
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
