import { execSync } from "node:child_process";

import { writeAndFix } from "./lib/write-and-fix.ts";

export interface ConfigShowOutput {
  managedConfigs: Record<string, ManagedConfigData>;
}

export interface ManagedConfigData {
  deleteOnly?: boolean;
  linkTarget?: string;
  otherFileNameList?: string[];
  projectTypes?: string[];
  scope?: "git-root" | "project";
  tools?: string[];
}

export interface ManagedConfigDocInfo {
  deleteOnly: boolean;
  linkTarget: string;
  name: string;
  otherFileNameList: string[];
  projectTypes: string[];
  scope: string;
  tools: string[];
}

export function executeConfigShow(): string {
  return execSync("pnpm --silent dm config show", {
    encoding: "utf8",
    maxBuffer: 256 * 1024 * 1024, // config show output exceeds the 1MB default
    stdio: ["pipe", "pipe", "ignore"], // Ignore stderr to avoid pnpm lockfile messages
    timeout: 30_000,
  });
}

export function extractManagedConfigsInfo(config: ConfigShowOutput): ManagedConfigDocInfo[] {
  return Object.entries(config.managedConfigs)
    .map(([name, managedConfig]) => ({
      deleteOnly: managedConfig.deleteOnly ?? false,
      linkTarget: managedConfig.linkTarget ?? "",
      name,
      otherFileNameList: managedConfig.otherFileNameList ?? [],
      projectTypes: managedConfig.projectTypes ?? [],
      scope: managedConfig.scope ?? "project",
      tools: managedConfig.tools ?? [],
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function generateManagedConfigsMarkdown(configs: ManagedConfigDocInfo[]): string {
  const lines = [
    "# Managed Configurations",
    "",
    "<!-- Auto-generated list of managed configs in @shibanet0/datamitsu-config. -->",
    "",
    "<!--",
    "Note: This file is automatically generated from the config.",
    "Do not edit manually. To update, run: `pnpm dm exec task -- docs:generate`",
    "-->",
    "",
    "## Overview",
    "",
    "Managed configurations define which files datamitsu writes when you run `dm config reconcile`.",
    "These include dotfiles, tool configurations, AI instructions, and IDE settings.",
    "",
    `This configuration includes **${configs.length} managed configs**.`,
    "",
    "## Managed Configs Reference",
    "",
    generateManagedConfigsTable(configs),
    "",
    "## Field Descriptions",
    "",
    "- **File**: The filename or path that will be created or managed",
    "- **Tools**: The tool(s) this config belongs to. `dm config reconcile --tools <name>` writes",
    "  only configs whose Tools include a selected name; configs with no Tools (—) are",
    "  infrastructure — always written by a plain `dm config reconcile`, skipped under `--tools`",
    "- **Scope**: Where the file is created:",
    "  - `git-root`: Created at the repository root",
    "  - `project`: Created in each project directory (for monorepos)",
    "- **Project Types**: Which project types this config applies to (empty = all projects)",
    "- **Link Target**: If present, creates a symlink to this target instead of a file",
    "- **Delete Only**: If checked (✓), only removes files without creating new ones",
    "- **Also Deletes**: Other filenames that will be removed when this config is applied",
    "",
    "## How Reconciliation Works",
    "",
    "When you run `dm config reconcile`, datamitsu:",
    "",
    "1. Detects your project type (npm, Go, TypeScript, etc.)",
    "2. Filters configs by project type (configs with empty project types apply to all)",
    "3. For each config:",
    "   - If **Delete Only** is checked: removes the file and any files in **Also Deletes**",
    "   - If **Link Target** is set: creates a symlink to the target",
    "   - Otherwise: generates content and merges with existing files",
    "4. Preserves your customizations during updates",
    "",
  ];
  return lines.join("\n");
}

export async function main(): Promise<void> {
  const outputPath = "docs/reference/managed-configs.md";
  const jsonStr = executeConfigShow();
  const config = parseConfigJson(jsonStr);
  const configs = extractManagedConfigsInfo(config);
  const markdown = generateManagedConfigsMarkdown(configs);

  const result = await writeAndFix({
    content: markdown,
    filePath: outputPath,
    verbose: true,
  });

  if (!result.success) {
    console.error(`Failed to write or fix ${outputPath}`);
    if (result.fixResult?.error) {
      console.error(`Error: ${result.fixResult.error}`);
    }
    process.exit(1);
  }

  console.log(`Generated ${outputPath} with ${configs.length} managed configs`);
}

export function parseConfigJson(jsonStr: string): ConfigShowOutput {
  const data: unknown = JSON.parse(jsonStr);
  if (typeof data !== "object" || data === null || !("managedConfigs" in data)) {
    throw new Error("Invalid config output: missing 'managedConfigs' field");
  }
  return data as ConfigShowOutput;
}

function formatFileList(files: string[]): string {
  if (files.length === 0) {
    return "—";
  }
  return files.map((f) => `\`${f}\``).join("<br>");
}

function formatToolList(toolNames: string[]): string {
  if (toolNames.length === 0) {
    return "—";
  }
  return toolNames.map((t) => `\`${t}\``).join(", ");
}

function generateManagedConfigsTable(configs: ManagedConfigDocInfo[]): string {
  const header =
    "| File | Tools | Scope | Project Types | Link Target | Delete Only | Also Deletes |";
  const separator = "| --- | --- | --- | --- | --- | --- | --- |";

  const rows = configs.map((c) => {
    const file = `\`${c.name}\``;
    const toolsList = formatToolList(c.tools);
    const scope = c.scope;
    const projectTypes = c.projectTypes.length > 0 ? c.projectTypes.join(", ") : "all";
    const linkTarget = c.linkTarget ? `\`${c.linkTarget}\`` : "—";
    const alsoDeletes = formatFileList(c.otherFileNameList);
    const deleteOnly = c.deleteOnly ? "✓" : "";

    return `| ${file} | ${toolsList} | ${scope} | ${projectTypes} | ${linkTarget} | ${deleteOnly} | ${alsoDeletes} |`;
  });

  return [header, separator, ...rows].join("\n");
}

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/generate-docs-managed-configs.ts");

if (isDirectRun) {
  try {
    await main();
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
