import fsPromise from "node:fs/promises";
import path from "node:path";

// --- Types ---

export interface SyncResult {
  minVersionUpdated: boolean;
  skipped: boolean;
  skipReason?: string;
  version: string;
}

// --- Constants ---

const UNSTABLE_PATTERN = /^0\.0\.0-unstable\./;

const MIN_VERSION_REGEX = /(return\s+")([\w.-]+)(")/;

// --- Exported functions (testable) ---

/**
 * Check if a version is unstable (0.0.0-unstable.*).
 */
export function isUnstableVersion(version: string): boolean {
  return UNSTABLE_PATTERN.test(version);
}

/**
 * Read the @datamitsu/datamitsu version from package.json.
 */
export async function readDatamitsuVersion(packageJsonPath: string): Promise<string> {
  const content = await fsPromise.readFile(packageJsonPath, "utf8");
  const pkg = JSON.parse(content) as {
    dependencies?: Record<string, string>;
  };

  const version = pkg.dependencies?.["@datamitsu/datamitsu"];
  if (!version) {
    throw new Error("Could not find @datamitsu/datamitsu in package.json dependencies");
  }
  return version;
}

/**
 * Sync the minimum required datamitsu version into datamitsu.config.ts.
 *
 * The Dockerfile FROM lines are NOT synced here anymore — they are generated by `datamitsu devtools
 * dockerfile` (see scripts/generate-dockerfiles.ts), which derives the base image repo+tag from the
 * installed binary.
 */
export async function syncDatamitsuVersion(rootDir: string): Promise<SyncResult> {
  const packageJsonPath = path.join(rootDir, "package.json");
  const configTsPath = path.join(rootDir, "src/datamitsu-config/datamitsu.config.ts");

  const version = await readDatamitsuVersion(packageJsonPath);

  if (isUnstableVersion(version)) {
    return {
      minVersionUpdated: false,
      skipped: true,
      skipReason: `Unstable version ${version} — skipping min-version sync`,
      version,
    };
  }

  const configTsContent = await fsPromise.readFile(configTsPath, "utf8");
  const [updatedConfigTs, minVersionUpdated] = updateMinVersion(configTsContent, version);
  if (minVersionUpdated) {
    await fsPromise.writeFile(configTsPath, updatedConfigTs, "utf8");
  }

  return {
    minVersionUpdated,
    skipped: false,
    version,
  };
}

/**
 * Update the getMinVersion return value in datamitsu.config.ts. Returns [updatedContent,
 * wasChanged].
 */
export function updateMinVersion(content: string, version: string): [string, boolean] {
  const match = content.match(MIN_VERSION_REGEX);

  if (!match) {
    throw new Error('Could not find return "..." pattern in datamitsu.config.ts getMinVersion');
  }

  if (match[2] === version) {
    return [content, false];
  }

  const replaced = content.replace(MIN_VERSION_REGEX, `$1${version}$3`);
  return [replaced, true];
}

// --- Direct run ---

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/sync-datamitsu-version.ts");

if (isDirectRun) {
  try {
    const rootDir = path.join(import.meta.dirname, "..");
    const result = await syncDatamitsuVersion(rootDir);

    if (result.skipped) {
      console.log(result.skipReason);
    } else if (result.minVersionUpdated) {
      console.log(
        `Synced min version ${result.version} to src/datamitsu-config/datamitsu.config.ts`,
      );
    } else {
      console.log(`Min version already in sync with ${result.version}`);
    }
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
