import fsPromise from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";
// --- Types ---

export interface SyncResult {
  minVersionUpdated: boolean;
  selfPinUpdated: boolean;
  skipped: boolean;
  skipReason?: string;
  version: string;
}

// --- Constants ---

const UNSTABLE_PATTERN = /^0\.0\.0-unstable\./;

const MIN_VERSION_REGEX = /(return\s+")([\w.-]+)(")/;

// The root config emits the workspace catalog that resolves this repository's catalog: dependency.
const SELF_PIN_REGEX = /^(\s*"@datamitsu\/datamitsu":\s*)([\w.-]+)(\s*)$/m;

// --- Exported functions (testable) ---

/**
 * Check if a version is unstable (0.0.0-unstable.*).
 */
export function isUnstableVersion(version: string): boolean {
  return UNSTABLE_PATTERN.test(version);
}

/**
 * Read the @datamitsu/datamitsu version from the pnpm workspace catalog.
 */
export function readDatamitsuVersion(content: string): string {
  const workspace = parse(content) as {
    catalog?: Record<string, unknown>;
  };
  const version = workspace.catalog?.["@datamitsu/datamitsu"];

  if (typeof version !== "string" || version.length === 0) {
    throw new Error("Could not find @datamitsu/datamitsu in the pnpm workspace catalog");
  }

  return version;
}

/**
 * Sync the minimum required datamitsu version into datamitsu.config.ts.
 *
 * The Dockerfile FROM lines are NOT synced here anymore — they are generated by `datamitsu devtools
 * dockerfile` (see scripts/generate-dockerfiles.ts), which derives the base image repo+tag from the
 * installed binary.
 */
export async function syncDatamitsuVersion(rootDir: string): Promise<SyncResult> {
  const workspaceYamlPath = path.join(rootDir, "pnpm-workspace.yaml");
  const configTsPath = path.join(rootDir, "src/datamitsu-config/datamitsu.config.ts");

  const workspaceYaml = await fsPromise.readFile(workspaceYamlPath, "utf8");
  const version = readDatamitsuVersion(workspaceYaml);

  const rootConfigTsPath = path.join(rootDir, "datamitsu.config.ts");
  const rootConfigTs = await fsPromise.readFile(rootConfigTsPath, "utf8");
  const [updatedRootConfigTs, selfPinUpdated] = updateSelfPin(rootConfigTs, version);
  if (selfPinUpdated) {
    await fsPromise.writeFile(rootConfigTsPath, updatedRootConfigTs, "utf8");
  }

  if (isUnstableVersion(version)) {
    return {
      minVersionUpdated: false,
      selfPinUpdated,
      skipped: true,
      skipReason: `Unstable version ${version} — skipping min-version sync`,
      version,
    };
  }

  const configTsContent = await fsPromise.readFile(configTsPath, "utf8");
  const [updatedConfigTs, minVersionUpdated] = updateMinVersion(configTsContent, version);
  if (minVersionUpdated) {
    await fsPromise.writeFile(configTsPath, updatedConfigTs, "utf8");
  }

  return {
    minVersionUpdated,
    selfPinUpdated,
    skipped: false,
    version,
  };
}

/**
 * Update the getMinVersion return value in datamitsu.config.ts. Returns [updatedContent,
 * wasChanged].
 */
export function updateMinVersion(content: string, version: string): [string, boolean] {
  const match = content.match(MIN_VERSION_REGEX);

  if (!match) {
    throw new Error('Could not find return "..." pattern in datamitsu.config.ts getMinVersion');
  }

  if (match[2] === version) {
    return [content, false];
  }

  const replaced = content.replace(MIN_VERSION_REGEX, `$1${version}$3`);
  return [replaced, true];
}

/**
 * Update the `@datamitsu/datamitsu` pin in the workspace catalog emitted by the root
 * datamitsu.config.ts. Returns [updatedContent, wasChanged].
 */
export function updateSelfPin(content: string, version: string): [string, boolean] {
  const match = content.match(SELF_PIN_REGEX);

  if (!match) {
    throw new Error('Could not find the "@datamitsu/datamitsu" catalog pin in datamitsu.config.ts');
  }

  if (match[2] === version) {
    return [content, false];
  }

  return [content.replace(SELF_PIN_REGEX, `$1${version}$3`), true];
}

// --- Direct run ---

const isDirectRun =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/sync-datamitsu-version.ts");

if (isDirectRun) {
  try {
    const rootDir = path.join(import.meta.dirname, "..");
    const result = await syncDatamitsuVersion(rootDir);

    if (result.selfPinUpdated) {
      console.log(
        `Synced the @datamitsu/datamitsu workspace catalog pin in datamitsu.config.ts to ${result.version}`,
      );
    }

    if (result.skipped) {
      console.log(result.skipReason);
    } else if (result.minVersionUpdated) {
      console.log(
        `Synced min version ${result.version} to src/datamitsu-config/datamitsu.config.ts`,
      );
    } else {
      console.log(`Min version already in sync with ${result.version}`);
    }
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}
