/**
 * Regenerates `src/datamitsu-config/parsers.ts` from the installed datamitsu build.
 *
 * The WASM output-parser module is pinned by digest and content hash, and both change on every
 * datamitsu release — the module's version string is compiled in, so its bytes differ even when the
 * parser sources do not. Until now those three values were copied by hand out of
 * `node_modules/@datamitsu/datamitsu/parsers-oci.json` on every bump, which is a step that is easy
 * to skip and produces no error when skipped: the config keeps pointing at the previous release's
 * artifact, which still exists in the registry and still verifies. The pin silently lags the
 * binary.
 *
 * So derive it. The published `parsers-oci.json` is the same file the binary itself ships, which
 * makes it the one source that cannot disagree with the build being targeted.
 *
 * The header below is wrapped the way the formatters leave it, not the way it reads best. Both
 * prettier and oxfmt claim `.ts` here and disagree about where to break those lines, and oxfmt runs
 * last — anything else leaves the file dirty after every run and fails `validate:parsers` on a
 * clean tree. This block is fenced for the same reason: unfenced, the jsdoc formatter reflows the
 * two commands into one paragraph.
 *
 * ```sh
 * node scripts/sync-parsers.ts          # rewrite the pin from the installed build
 * node scripts/sync-parsers.ts --check  # fail if the committed pin has drifted
 * ```
 *
 * Runs as part of `task sync:datamitsu-version`, so a `@datamitsu/datamitsu` bump carries its
 * parser pin with it.
 */
import fsPromise from "node:fs/promises";
import path from "node:path";

const repoRoot = path.join(import.meta.dirname, "..");
const parsersPath = path.join(repoRoot, "src/datamitsu-config/parsers.ts");
const sourcePath = path.join(repoRoot, "node_modules/@datamitsu/datamitsu/parsers-oci.json");

interface ParsersOCI {
  digest: string;
  module: string;
  ref: string;
  sha256: string;
  version: string;
}

const HEX64 = /^[\da-f]{64}$/;

function assertShape(source: ParsersOCI): void {
  if (source.module !== "core") {
    throw new Error(
      `parsers-oci.json declares module ${JSON.stringify(source.module)}; this config only wires up "core". ` +
        `A second module means parsers.ts needs a real entry for it, not a renamed one.`,
    );
  }
  if (!source.ref) {
    throw new Error("parsers-oci.json has no OCI ref");
  }
  // The digest guards the manifest and the hash guards the payload; a malformed either one would be
  // written into the config and only fail much later, at download time, on a consumer's machine.
  if (!HEX64.test(source.digest.replace(/^sha256:/, ""))) {
    throw new Error(`parsers-oci.json digest is not a sha256 hex digest: ${source.digest}`);
  }
  if (!HEX64.test(source.sha256)) {
    throw new Error(`parsers-oci.json sha256 is not a 64-character hex hash: ${source.sha256}`);
  }
}

function render(source: ParsersOCI): string {
  const digest = source.digest.startsWith("sha256:") ? source.digest : `sha256:${source.digest}`;

  return `/**
 * WASM output-parser module pin.
 *
 * Datamitsu turns a tool's machine-readable output into structured diagnostics with a signed
 * Rust→WASM parser module. Tools opt in by name via \`outputParser\` (see ./tools.ts); a module
 * declared but unreferenced is harmless.
 *
 * The single module dispatches every tool's parser by name, so one \`parsers\` entry ("core") serves
 * all of them. It is downloaded once and SHA-256 verified against \`hash\` before it is loaded into
 * the sandboxed WASM runtime.
 *
 * Sourced from the registry rather than a release asset. The module is delivered over two channels
 * — a GitHub release asset (\`url\`) and an OCI artifact (\`oci\`) — and an entry declares exactly one;
 * there is no fallback chain. \`oci\` is used because the registry copy always exists: unstable
 * builds reach npm and the registry without always getting a GitHub release cut, so the release
 * asset can 404 for a version that otherwise exists.
 *
 * \`hash\` does double duty on this channel: it is the module's SHA-256 _and_ the expected digest of
 * the artifact's single layer, so a manifest pointing at other content is rejected before a single
 * payload byte is requested.
 *
 * Generated by scripts/sync-parsers.ts from the pinned build's own \`parsers-oci.json\` — do not
 * edit. Both values change on every release even when the parser sources do not, because the
 * module's version string is compiled into it.
 *
 * Pinned to datamitsu ${source.version}.
 */

const PARSERS_OCI_REF = "${source.ref}";
// Wrapped because prettier does: "sha256:" plus 64 hex characters always overruns the line width,
// and an unwrapped line here would leave every \`task refresh\` with a file the formatter rewrites
// and \`validate:parsers\` then rejects.
const PARSERS_OCI_DIGEST =
  "${JSON.stringify(digest).slice(1, -1)}";

const CORE_PARSER_HASH = "${source.sha256}";

export const parsers: config.MapOfParsers = {
  core: {
    hash: CORE_PARSER_HASH,
    oci: {
      digest: PARSERS_OCI_DIGEST,
      ref: PARSERS_OCI_REF,
    },
  },
};
`;
}

const raw = await fsPromise.readFile(sourcePath, "utf8").catch(() => {
  throw new Error(
    `Missing ${path.relative(repoRoot, sourcePath)}. Install dependencies first: pnpm install`,
  );
});

const source = JSON.parse(raw) as ParsersOCI;
assertShape(source);

const rendered = render(source);

if (process.argv.includes("--check")) {
  const committed = await fsPromise.readFile(parsersPath, "utf8").catch(() => null);

  if (committed !== rendered) {
    console.error(
      [
        `The WASM parser pin has drifted from the installed datamitsu build (${source.version}).`,
        "",
        "Accept it with:",
        "",
        "  pnpm dm exec task -- sync:datamitsu-version",
      ].join("\n"),
    );
    process.exit(1);
  }

  console.log(`parsers: pin matches datamitsu ${source.version}`);
} else {
  await fsPromise.writeFile(parsersPath, rendered, "utf8");
  console.log(`parsers: pinned to datamitsu ${source.version} (${source.digest})`);
}
