import type { FlatProfile } from "../profile";

export const cspellProfile: FlatProfile = {
  refs: [
    "coverage",
    "nodeModules",
    "dist",
    "git",
    "gitignore",
    "dockerignore",
    "gitattributes",
    "tests",
    "out",
    "cast",
    "storybookStatic",
    "vendor",
    "cspellConfig",
    "datamitsuConfig",
    "pnpmLock",
    "goMod",
    "goSum",
    "pnpmStore",
    "pnp",
    "yarn",
    "next",
    "nuxt",
    "svelteKit",
    "output",
    "vercel",
    "turbo",
    "cache",
    "datamitsu",
    // cspell reads every file (`globs: ["**/*"]`), so a lockfile it does not skip is spell-checked.
    "packageLock",
    "npmShrinkwrap",
    "yarnLock",
    "bunLock",
    "bunLockBinary",
    "cargoLock",
    "poetryLock",
    "uvLock",
    "pipfileLock",
    "gemfileLock",
    "composerLock",
    "mixLock",
    "flakeLock",
    "pubspecLock",
    "podfileLock",
  ],
  syntax: "glob",
};
