import type { FlatProfile } from "../profile";

export const eslintProfile: FlatProfile = {
  refs: [
    "nodeModules",
    "dist",
    // One lockfile set across the ESLint and cspell profiles: change them together.
    "packageLock",
    "yarnLock",
    "pnpmLock",
    "bunLockBinary",
    "bunLock",
    "npmShrinkwrap",
    "goSum",
    "cargoLock",
    "poetryLock",
    "uvLock",
    "pipfileLock",
    "gemfileLock",
    "composerLock",
    "mixLock",
    "flakeLock",
    "pubspecLock",
    "podfileLock",
    "vendor",
    "pnpmStore",
    "pnp",
    "generated",
    "outputDirectory",
    "coverage",
    "temp",
    "dotTemp",
    "tmp",
    "build",
    "dotTmp",
    "history",
    "vitepressCache",
    "nuxt",
    "turbo",
    "playwrightReportHtml",
    "playwrightReportAllure",
    "playwrightReportWildcard",
    "git",
    "next",
    "out",
    "storybookStatic",
    "svelteKit",
    "vercel",
    "changeset",
    "idea",
    "cache",
    "output",
    "viteInspect",
    "yarn",
    "viteTimestamp",
    "changelog",
    "minified",
    "license",
    "snapshots",
    "autoImports",
    "components",
    "datamitsu",
    "jsonEncrypted",
    "yamlEncrypted",
    "ymlEncrypted",
  ],
  syntax: "glob",
};
