import type { GitignoreProfile } from "../profile";

export const gitignoreProfile: GitignoreProfile = {
  groups: {
    "Build outputs": ["next", "build", "dist", "out", "turbo", "vercel", "output", "publicBuild"],
    "Cache & temporary files": [
      "datamitsu",
      "tsBuildInfo",
      "eslintCache",
      "prettierCache",
      "stylelintCache",
      "tempFiles",
      "swapFiles",
      "swapOldFiles",
      "backupFiles",
      "cache",
      "parcelCache",
      "dotTemp",
      "dotTmp",
    ],
    "Claude Code project files": ["claude", "claudeSkills"],
    "Codex CLI project files": ["codex", "codexPrompts"],
    Dependencies: [
      "nodeModules",
      "pnpmStore",
      "vendor",
      "pnp",
      "yarnCache",
      "yarnUnplugged",
      "yarnBuildState",
      "yarnInstallState",
    ],
    Environment: [
      "env",
      "envLocal",
      "envWildcardLocal",
      "envDevelopmentLocal",
      "envTestLocal",
      "envProductionLocal",
      "nestedEnv",
      "envBackup",
      "nestedEnvLocal",
      "nestedEnvWildcardLocal",
    ],
    "Golang specific": [
      "executables",
      "executableBackups",
      "dll",
      "sharedLibraries",
      "dynamicLibraries",
      "goTestBinaries",
      "goOutput",
      "goWork",
      "goWorkSum",
    ],
    "IDE & OS": [
      "dsStore",
      "thumbsDb",
      "idea",
      "fleet",
      "vscode",
      "vscodeLaunch",
      "vscodeSettings",
      "vscodeExtensions",
      "sublimeWorkspace",
      "iml",
      "eclipseProject",
      "eclipseClasspath",
      "eclipseSettings",
    ],
    Logs: ["pnpmDebugLog", "npmDebugLog", "yarnDebugLog", "yarnErrorLog", "lernaDebugLog", "logs"],
    Other: ["gpg"],
    Pulumi: [
      "pulumiAttrs",
      "pulumiLocks",
      "pulumiBackups",
      "pulumiHistory",
      "pulumiBak",
      "pulumiJson",
      "pulumiJsonTmp",
      "pulumiYamlTmp",
      "pulumiEncJson",
      "pulumiJsonEnc",
      "pulumiYaml",
      "pulumiEncYaml",
      "pulumiYamlEnc",
      "pulumiYml",
      "pulumiEncYml",
      "pulumiYmlEnc",
    ],
    "ralphex progress logs": ["ralphexProgress", "progress", "progressLogs", "ralphexWorktrees"],
    "Security & Secrets": [
      "privateKeys",
      "pem",
      "pkcs12",
      "pfx",
      "certificates",
      "certificatesCrt",
      "secretsYaml",
      "secretsJson",
    ],
    "Terraform & Terragrunt": [
      "terraform",
      "terragruntCache",
      "terraformState",
      "terraformStateBackup",
      "crashLog",
      "terraformOverride",
      "terraformOverrideJson",
      "terraformWildcardOverride",
      "terraformWildcardOverrideJson",
    ],
    Testing: [
      "coverage",
      "cov",
      "coverageOut",
      "cover",
      "storybookStatic",
      "playwrightReport",
      "playwrightResults",
      "playwrightCache",
      "testResults",
      "allureReport",
      "nycOutput",
      "e2eScreenshots",
      "e2eVideos",
    ],
  },
  syntax: "gitignore",
};
