import type { FlatProfile } from "../profile";

export const lsLintProfile: FlatProfile = {
  refs: [
    "nodeModules",
    "vendor",
    "yarn",
    "dist",
    "build",
    "out",
    "outputDirectory",
    "next",
    "nuxt",
    "svelteKit",
    "output",
    "publicBuild",
    "vercel",
    "coverage",
    "cover",
    "storybookStatic",
    "playwrightReport",
    "playwrightResults",
    "playwrightReportHtml",
    "playwrightReportAllure",
    { as: "**/playwright-report-*", id: "playwrightReportWildcard" },
    "testResults",
    "allureReport",
    "nycOutput",
    "e2eScreenshots",
    "e2eVideos",
    "datamitsu",
    "turbo",
    "cache",
    "parcelCache",
    "dotTemp",
    "dotTmp",
    "temp",
    "tmp",
    "history",
    "vitepressCache",
    "viteInspect",
    "playwrightCache",
    "terraform",
    "terragruntCache",
    "pnpmStore",
    "generated",
    "iosProject",
    "androidProject",
    "venvDot",
    "venv",
    "tox",
    "ruffCache",
    "mypyCache",
    "pytestCache",
    "eggInfo",
    "git",
    "github",
    "husky",
    "changeset",
  ],
  syntax: "glob",
};
