// Generated by scripts/generate-oxlint-plugins.ts — do not edit.
//
// Every built-in plugin the pinned oxlint build knows about, minus the exceptions recorded in the
// generator. `src/apps/oxlint/index.ts` enables all of these: a plugin left off is a whole rule
// set switched off silently, which is the thing `src/lint-rules` exists to replace. Rules that are
// not wanted are turned off by name, with a reason.
import type { LintPluginOptionsSchema } from "./schema";

// prettier-ignore
export const OXLINT_PLUGINS = [
  "eslint",
  "import",
  "jsdoc",
  "jsx-a11y",
  "nextjs",
  "node",
  "oxc",
  "promise",
  "react",
  "react-perf",
  "typescript",
  "unicorn",
  "vitest",
  "vue"
] as const satisfies readonly LintPluginOptionsSchema[];

/**
 * Plugins deliberately left off. The reasons live in scripts/generate-oxlint-plugins.ts; they are
 * exported so the inventory validator can tell a decision apart from an oversight.
 */
// prettier-ignore
export const OXLINT_EXCLUDED_PLUGINS = [
  "jest"
] as const satisfies readonly LintPluginOptionsSchema[];

/**
 * Fails the typecheck if a plugin is neither enabled nor deliberately excluded — including one the
 * next oxlint bump adds. Dropping a plugin from the array by hand is a compile error rather than a
 * quietly narrower lint.
 */
export type _EveryOxlintPluginIsAccountedFor = AssertNever<
  Exclude<
    LintPluginOptionsSchema,
    (typeof OXLINT_EXCLUDED_PLUGINS)[number] | (typeof OXLINT_PLUGINS)[number]
  >
>;

type AssertNever<T extends never> = T;
